asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-63123))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-65594))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-18370))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(8748))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-49693))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-23327))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-42315))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(20798))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-27984))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-40359))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(4854))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(7720))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-13645))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-14443))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-3370))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-13612))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-77650))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-8496))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-1407))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2511))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(-1112))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-13825))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-32423))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(22476))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(25967))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-14872))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-1410))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(8691))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-21008))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-19746))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-33436))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(7247))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(4683))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-8825))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-13642))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-2734))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-1384))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(2268))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-4518))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1349))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(33676))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-34545))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(29787))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10184))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(14897))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(1091))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(8135))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(4137))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(6984))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(2775))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(23788))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(522))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(5430))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(4077))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(-672))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-4589))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-18871))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(372))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(4462))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(2474))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-8546))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-13298))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-6005))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(3726))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2238))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(5081))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(5202))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(6))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(515))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(9929))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-7417))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-7370))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-2774))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-8260))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-3271))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8505))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(9731))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-5727))).
playerSensor(player,objectIndex(1),intPair(rotationZ(980))).
playerSensor(player,objectIndex(1),player(velocityY(440))).
playerSensor(player,objectIndex(1),player(velocityX(834))).
playerSensor(player,objectIndex(1),intPair(y(-2546))).
playerSensor(player,objectIndex(1),intPair(x(-3586))).
