asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-33576))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-24996))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-12918))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-38024))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(5891))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-44126))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-5532))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(43989))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(7035))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(14892))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-15648))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-24058))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(52126))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(41601))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(20099))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-20881))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(15110))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-4293))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-24977))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-10249))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-10757))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(693))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-2133))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-22981))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-16933))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-23562))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(9297))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(12896))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(12796))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-3591))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(765))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-18912))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(5861))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(7057))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(17945))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-5773))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(x(6965))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(y(1576))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(y(1256))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-35338))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-58890))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-19045))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(21141))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-21275))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-6372))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-2279))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(31636))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(20923))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-12264))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-14371))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3138))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(-2217))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(256))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(-7918))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(-106))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(3257))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(x(6795))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(y(3288))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(x(8467))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(y(3523))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(x(-9068))).
asteroidSensor(asteroidClone,objectIndex(136),intPair(y(-9066))).
asteroidSensor(asteroidClone,objectIndex(139),intPair(y(-8844))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(54007))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(49679))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(20807))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-36297))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(2899))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-20724))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-5574))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-9361))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-24621))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-1036))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-17924))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(10760))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-11268))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(-4471))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(7680))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-13905))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(-1068))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(y(10670))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(x(3795))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(y(-3974))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(x(3090))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(y(2102))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(x(-1094))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(y(193))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(x(5226))).
asteroidSensor(asteroidClone,objectIndex(136),intPair(x(-1773))).
asteroidSensor(asteroidCloneClone,objectIndex(137),intPair(y(-3509))).
asteroidSensor(asteroidCloneClone,objectIndex(137),intPair(x(5460))).
asteroidSensor(asteroidCloneClone,objectIndex(138),intPair(y(-3468))).
asteroidSensor(asteroidCloneClone,objectIndex(138),intPair(x(5711))).
asteroidSensor(asteroidClone,objectIndex(139),intPair(x(-7581))).
playerSensor(player,objectIndex(1),intPair(rotationZ(55))).
playerSensor(player,objectIndex(1),player(velocityY(52))).
playerSensor(player,objectIndex(1),player(velocityX(-151))).
playerSensor(player,objectIndex(1),intPair(y(1357))).
playerSensor(player,objectIndex(1),intPair(x(-6360))).
