asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-1729))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(8805))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(3260))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(1542))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(16277))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-2943))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(4633))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(578))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3660))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(1429))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-18765))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1315))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3251))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(6391))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-1266))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-5625))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-987))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3871))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-576))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2629))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-8663))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-375))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(5929))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-8046))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(7663))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3751))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-2207))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(7986))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-481))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(7067))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-573))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(6746))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(9839))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(3698))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(833))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-967))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(868))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-1159))).
playerSensor(player,objectIndex(1),intPair(rotationZ(277))).
playerSensor(player,objectIndex(1),player(velocityY(-922))).
playerSensor(player,objectIndex(1),player(velocityX(1355))).
playerSensor(player,objectIndex(1),intPair(y(-2140))).
playerSensor(player,objectIndex(1),intPair(x(1297))).
