asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-25599))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2465))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-673))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(8942))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(8519))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1871))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-14709))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-3654))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(12277))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-3812))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(829))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-391))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-6486))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(12062))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(827))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-2005))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(2561))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-6875))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(14859))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-5667))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-3049))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-6402))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-3398))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-8302))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4921))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-4480))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-6371))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(11827))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(10417))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(22394))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-3015))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(2075))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4541))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(5654))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-1774))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(11915))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-2899))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(6685))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(6376))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-3447))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(1809))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-4899))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(-791))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(10240))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-1125))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(6099))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(7947))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-1588))).
playerSensor(player,objectIndex(1),intPair(rotationZ(926))).
playerSensor(player,objectIndex(1),player(velocityY(210))).
playerSensor(player,objectIndex(1),player(velocityX(-2524))).
playerSensor(player,objectIndex(1),intPair(y(-1235))).
playerSensor(player,objectIndex(1),intPair(x(474))).
