asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-13823))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(17470))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(42839))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-14260))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-48441))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(6309))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(6896))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-21647))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(12077))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(15807))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-33321))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1415))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-22480))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(37835))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(566))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-9487))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-17792))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(29692))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-14637))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(29194))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-29287))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-14063))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-40200))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-11904))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4573))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(3764))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(38922))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-663))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-34919))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7484))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(25807))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-49640))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(1183))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(18681))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-41720))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-12760))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-6397))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-21342))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(14650))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9600))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(1253))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-898))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(1811))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-11185))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(10250))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(-189))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(5710))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-6472))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(50447))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-27513))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-9365))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-5909))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(672))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(588))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(2178))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3561))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(5062))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(12111))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-5833))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-5924))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(5777))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-5400))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-204))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(910))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-9566))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-7929))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(695))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-10717))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-4383))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-12380))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(328))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(-1340))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-2421))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(10739))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(10767))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(3924))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-541))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
