asteroidSensor(asteroidClone,objectIndex(19),intPair(x(9019))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-28517))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-35153))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(49555))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1550))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-11574))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(63871))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-44354))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2805))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-123))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(35237))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-39819))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-18844))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11616))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-64097))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(1875))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-27937))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(45870))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-17969))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(35782))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-18423))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-10313))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-1465))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(327))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3019))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-10231))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-28156))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-10498))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-41986))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8513))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(32856))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(26420))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-54042))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-15656))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-52031))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(16578))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(22463))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9901))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(8295))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(3550))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-979))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-3595))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(3359))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1585))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(2036))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-232))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(3899))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(11629))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-902))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(7999))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(7314))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-402))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-13088))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1724))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(8761))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-9461))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-20203))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6728))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-29439))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(2830))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-4100))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-1543))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-22147))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(16561))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(19263))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1341))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(4822))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-16029))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-12312))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-23247))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(1551))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-5468))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-3910))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6050))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(7424))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-3157))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-11042))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(9067))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(4775))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-7366))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(3807))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-9149))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-981))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
