asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7902))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(45744))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(6950))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-30616))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(28671))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-37803))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-55513))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-24697))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(41099))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-15767))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(32166))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-258))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-10352))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3341))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1024))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-37790))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1980))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-10262))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-7698))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(3768))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-7954))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-15638))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-16175))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(31649))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-33566))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-16005))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(17824))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9722))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(4114))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(909))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(12814))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(15017))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-4802))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(18681))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(13906))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-15275))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(5449))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-22524))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(1549))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-24110))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(677))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(1607))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(432))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(2372))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-12875))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-7604))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-1804))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(9626))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6975))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-7686))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(55900))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(7758))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-24438))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(43241))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(652))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(21825))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-46726))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-13937))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-45006))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-1316))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(1426))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-7728))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-4978))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(4795))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-2562))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(706))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-16795))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(1779))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(3928))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(9364))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(2960))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-8752))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-4931))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(9160))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(431))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-9395))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(1074))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-9426))).
playerSensor(player,objectIndex(1),intPair(rotationZ(970))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
