asteroidSensor(asteroidClone,objectIndex(8),intPair(y(2854))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(5464))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-6033))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(4923))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(8847))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(4611))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(4784))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-9060))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(113))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(9062))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-6294))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(743))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(7868))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(6515))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-317))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(9712))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-4852))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(2768))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(7590))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(y(1867))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(x(4203))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-9485))).
playerSensor(player,objectIndex(1),intPair(rotationZ(734))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
