asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-22167))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1887))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4099))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(19321))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-4326))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(3950))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2251))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3159))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-4530))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-8734))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(3360))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6294))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(11407))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-2060))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(9319))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(5355))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(5483))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(1302))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(7661))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(2625))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(2965))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(1663))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-2384))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-4296))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(8577))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-6773))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(4797))).
playerSensor(player,objectIndex(1),intPair(rotationZ(639))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(9607))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-84))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(946))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-11672))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(9660))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-2185))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-2099))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(7249))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-2483))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-2091))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6463))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-1191))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-3236))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-1287))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(-2725))).
playerSensor(player,objectIndex(1),player(velocityY(526))).
playerSensor(player,objectIndex(1),player(velocityX(-217))).
playerSensor(player,objectIndex(1),intPair(y(-2623))).
playerSensor(player,objectIndex(1),intPair(x(2304))).
