asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(8400))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(1730))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-577))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(4248))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(2872))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(14741))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-3536))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(5275))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-2305))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-2861))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2819))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-8811))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(10033))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(239))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-623))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(2047))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-17049))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1026))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3534))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(5750))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2719))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-6281))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-1443))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(5347))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-7144))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3439))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-1889))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(6284))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(4050))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-1034))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(6259))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(315))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(5759))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(5447))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-380))).
playerSensor(player,objectIndex(1),player(velocityY(-1663))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-736))).
playerSensor(player,objectIndex(1),intPair(x(0))).
