asteroidSensor(asteroidClone,objectIndex(18),intPair(y(3719))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-4522))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(41690))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-22416))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(5512))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-17166))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(31986))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-85))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-7924))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-3035))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-734))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-30308))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6813))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(21209))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-26124))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-10944))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-22529))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-10871))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-32482))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3915))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-43230))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5432))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-10823))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(15524))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(25719))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-12167))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(25252))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(13632))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-33681))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(3647))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(3385))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(3633))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(38175))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-507))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-18920))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(32593))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11840))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(9141))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-6489))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(3167))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-10194))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(7141))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-3896))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-16896))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(9553))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(7226))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-4034))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(-546))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(14578))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1892))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-8098))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-40209))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2036))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9403))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1347))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-8431))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-3340))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-3799))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(6134))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(7446))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-2790))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-2251))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-7444))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(7355))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-9958))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-1665))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(1107))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-11726))).
playerSensor(player,objectIndex(1),intPair(rotationZ(378))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
