asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(34246))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(44552))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-17361))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-27528))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-38091))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-18060))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(21181))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-42544))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2577))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-27042))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-50090))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(15839))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-18841))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6375))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-9602))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-27038))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(18089))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(47810))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1405))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-40827))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8344))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(31699))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(34783))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-17802))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-3331))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(631))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3108))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(2398))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9852))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(7140))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1089))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-61725))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(90))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(25150))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-52020))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-15181))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(2476))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-9733))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-3977))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(3755))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(439))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(4145))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-15157))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-1151))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(8261))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-8971))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(61668))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(8670))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-27390))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-33899))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-11212))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-9591))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-1131))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11266))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(2820))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-521))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-672))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-20348))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(15525))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(1668))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-1495))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-11011))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-21464))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(3313))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(9501))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(8449))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(7881))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(1941))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-6376))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-4192))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6306))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(7904))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-2166))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-10587))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(5))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-12076))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1961))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(9873))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(6000))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-8337))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-669))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
