asteroidSensor(asteroidClone,objectIndex(18),intPair(y(4804))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(35449))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(16584))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(40717))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-13513))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-5584))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(46462))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(6266))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-19608))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13159))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(27884))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-14334))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(23715))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-30046))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1002))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-20860))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(32))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(1980))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-7930))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(27400))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-26160))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-12643))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-25245))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(3933))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(6008))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-5259))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-10549))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(35765))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-400))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-32821))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7178))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-11900))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-36688))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(10741))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-9440))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(2728))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3722))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-2218))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(2640))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(5339))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-4448))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-6616))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-529))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-12457))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-45348))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(1571))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(16383))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-38061))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(6495))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-7474))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-869))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(1000))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-10215))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(-643))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-751))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(15248))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-46070))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5910))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-8709))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-4601))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1169))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-8854))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-19319))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(12330))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9510))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-837))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(8377))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(9988))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-9140))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-2029))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-9153))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(-731))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(-5191))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-2873))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(11553))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
