asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-12151))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(19239))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(2004))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-35239))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-2644))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-21269))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(5398))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-3914))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-16420))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-42222))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-5087))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-14132))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-22348))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(48367))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-15681))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-21813))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(40123))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-1663))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(28600))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(18296))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-10514))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-706))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-15206))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(-2304))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(38651))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-33318))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-55453))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-18062))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(19206))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-33610))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-13209))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(13134))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(8389))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(11167))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(11478))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(8907))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-7694))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(1492))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(5785))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(6386))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-31710))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-24140))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-22823))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(5426))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(13525))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(18370))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-18752))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-8354))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-10095))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(4312))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(6331))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(13897))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(y(-4792))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(-4287))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(89))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(223))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(y(6920))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(y(490))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-19390))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-6060))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(50319))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(46326))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-18984))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-4840))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-7419))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-21180))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-8896))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-4618))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(456))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(x(6586))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-7182))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3385))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(115))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(3400))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(x(3174))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(y(-774))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(x(4914))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(y(4391))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(x(6037))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(y(3969))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(x(5822))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(y(4464))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(x(6720))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(x(-173))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(y(-668))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(x(2175))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(y(1091))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(x(-10964))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-986))).
playerSensor(player,objectIndex(1),player(velocityY(249))).
playerSensor(player,objectIndex(1),player(velocityX(-725))).
playerSensor(player,objectIndex(1),intPair(y(1160))).
playerSensor(player,objectIndex(1),intPair(x(-5786))).
