asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-50431))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-3571))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-30943))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(50296))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-20013))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-58547))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(19057))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-24774))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(7915))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-35854))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-31910))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(26766))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10067))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(12174))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(3270))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(4007))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(5412))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-39360))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-12791))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-12739))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-2584))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-12788))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(6000))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-28184))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(20036))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(23202))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-13068))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(245))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-5192))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(5813))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-6487))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-12570))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-1772))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-8991))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-4773))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-1848))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(39137))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-20508))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(38566))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-45620))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-21478))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(4019))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-6683))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-691))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2720))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(120))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-12342))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-2311))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(2026))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(5433))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(5866))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(18772))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-64))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(6490))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-16486))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(930))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(6361))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(757))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-6942))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(6088))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(11476))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-72059))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-843))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(30683))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-60829))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-17251))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(2183))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(7095))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-18954))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-16680))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-29233))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-2441))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(-551))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(-9807))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(-1221))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-6015))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(459))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(1001))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(-1958))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(862))).
playerSensor(player,objectIndex(1),intPair(rotationZ(219))).
playerSensor(player,objectIndex(1),player(velocityY(-994))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3858))).
playerSensor(player,objectIndex(1),intPair(x(-6682))).
