asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-43180))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-15509))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-3862))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-14127))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-81151))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1666))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-29994))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(9270))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(5376))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-9632))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(505))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(35550))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-68578))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-19072))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-65988))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(21888))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-1855))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-14753))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-36195))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(31680))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10257))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-16001))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-846))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(9827))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(4680))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(4767))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(16603))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(8797))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-35078))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(24004))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(27699))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(8848))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(3146))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(9690))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-22295))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-21666))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-36068))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(8112))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(26929))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(890))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(3241))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(-1246))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-4212))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(3974))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-10290))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-14314))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-3336))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-20366))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(23))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(3272))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-2725))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(5217))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(4789))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-10131))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-15995))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-6776))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-3000))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(2247))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2483))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(7975))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(7833))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(1237))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(298))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(8961))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-6761))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-6318))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-4757))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-7600))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-5327))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8128))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(8351))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-5188))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-11023))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(1873))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-2875))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-2238))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-3037))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(-1392))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(y(-2455))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(x(-2190))).
playerSensor(player,objectIndex(1),intPair(rotationZ(745))).
playerSensor(player,objectIndex(1),player(velocityY(1932))).
playerSensor(player,objectIndex(1),player(velocityX(-938))).
playerSensor(player,objectIndex(1),intPair(y(-860))).
playerSensor(player,objectIndex(1),intPair(x(-3236))).
