asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-41553))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2452))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-26552))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(43830))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-17028))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-37145))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-17630))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(2282))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(46855))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1325))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-40192))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8252))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(31066))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-33213))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-11013))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-9195))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-949))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11075))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-2909))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(797))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3157))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(2684))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9825))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(6507))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-188))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-49027))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(15435))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-18096))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6181))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-26482))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(2420))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-270))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-195))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-19363))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(14958))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(1467))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-2186))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(952))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(3774))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-14680))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(8191))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(2154))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-6873))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-4347))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-10338))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(229))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-8869))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(7987))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-8702))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(60462))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(8480))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-26773))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(34236))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-17462))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(33703))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-60426))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(208))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(24455))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-50913))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-14921))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-9257))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-26426))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(20479))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(17447))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-9314))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-4186))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(3973))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-10299))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-20488))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(2992))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(8335))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-1288))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(8695))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6446))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(8166))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-1622))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-11522))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(2090))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(10314))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(6670))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-339))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
