asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-33775))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(3841))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5594))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(107))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-983))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(25801))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(963))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-21943))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-7686))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(18100))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(426))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-5379))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(11994))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(29712))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(12867))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-13066))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(1138))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(18510))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-5284))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-13486))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-5577))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(12347))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(3000))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-9035))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(19401))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-12460))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(23083))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-7450))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-9950))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-5309))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-850))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(2177))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(4296))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-23098))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3583))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(4472))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-19097))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7444))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-18479))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(3814))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(5942))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-341))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-434))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(375))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(3333))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(617))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3591))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-3289))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(333))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-8653))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(9197))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(5576))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4557))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(10914))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(641))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-8831))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(306))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9046))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-380))).
playerSensor(player,objectIndex(1),player(velocityY(119))).
playerSensor(player,objectIndex(1),player(velocityX(240))).
playerSensor(player,objectIndex(1),intPair(y(-3192))).
playerSensor(player,objectIndex(1),intPair(x(-6011))).
