asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-31744))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-16438))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(18088))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-71178))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-19683))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-68483))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(22837))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(33328))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10320))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-38360))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-37390))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(25336))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(29208))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-16985))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(8865))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(29665))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-11565))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-4290))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-14577))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-84201))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1941))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(37182))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-15562))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-37633))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-23415))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-23339))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-3883))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(3358))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-18345))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(11301))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(5152))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(10472))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(3469))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(10561))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(1211))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(4189))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-3894))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(7786))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(6805))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-11512))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2696))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(10496))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-6190))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(9725))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-45637))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(5831))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-10621))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-2246))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(9736))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-14899))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-3861))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-21667))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-281))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(2236))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-7448))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-1677))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(959))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(10125))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(2309))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(108))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(8118))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-5401))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-6484))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-7025))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-7118))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-7800))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(7149))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-4719))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-10005))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(1587))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-3976))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-3043))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-4161))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(1092))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(y(-662))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(x(-4245))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-11122))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-81))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-1074))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(738))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(-274))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(919))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(2740))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-1423))).
asteroidSensor(asteroidCloneClone,objectIndex(96),intPair(y(2986))).
asteroidSensor(asteroidCloneClone,objectIndex(96),intPair(x(-1722))).
playerSensor(player,objectIndex(1),intPair(rotationZ(345))).
playerSensor(player,objectIndex(1),player(velocityY(495))).
playerSensor(player,objectIndex(1),player(velocityX(-2021))).
playerSensor(player,objectIndex(1),intPair(y(149))).
playerSensor(player,objectIndex(1),intPair(x(-4423))).
