asteroidSensor(asteroidClone,objectIndex(19),intPair(y(58522))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-25763))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(8173))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-8558))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-25780))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(45318))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1197))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-39170))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-32109))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-10694))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(1065))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(42669))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-16491))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(33356))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-16915))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(32830))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(5869))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-24799))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(1971))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-2232))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(132))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(571))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(731))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8103))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(30047))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-39958))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2251))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-49132))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-14502))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-47317))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(14785))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-16896))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9781))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(5489))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(1777))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(1143))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-3299))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(2476))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-655))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-10767))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-58336))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(397))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(23336))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-17779))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(14046))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(16413))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-8639))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-4523))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(3178))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-13912))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-9153))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-18917))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-7672))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-4595))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6671))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(8589))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-749))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(11024))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(19264))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(47141))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(7546))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-8270))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-35623))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-16939))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3235))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(3145))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-8703))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-25441))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(19350))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(4322))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-1197))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(6461))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-1507))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(9091))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(8690))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(2497))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-9937))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(589))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-10630))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(2299))).
playerSensor(player,objectIndex(1),intPair(rotationZ(775))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
