asteroidSensor(asteroidClone,objectIndex(5),intPair(y(1307))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-17954))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1178))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-784))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-778))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(1721))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(3728))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(2171))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-1953))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-5935))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3556))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-1184))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(8613))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3385))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(6088))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(15551))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-3223))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(4936))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-1203))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4569))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-1656))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2719))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-7945))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-1091))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(6096))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-8408))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(8783))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3892))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-1652))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(7169))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-104))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(6449))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-189))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(6132))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(10909))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(4184))).
playerSensor(player,objectIndex(1),intPair(rotationZ(70))).
playerSensor(player,objectIndex(1),player(velocityY(-1416))).
playerSensor(player,objectIndex(1),player(velocityX(1888))).
playerSensor(player,objectIndex(1),intPair(y(-1519))).
playerSensor(player,objectIndex(1),intPair(x(384))).
