asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(9129))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-6063))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2549))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-960))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(2474))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(22841))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-2824))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(1888))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-7216))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(15362))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-690))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(10535))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-26099))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4605))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(6094))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-2464))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(12658))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-4049))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(6249))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(12901))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(960))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-2434))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-3886))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-6144))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-3187))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-3531))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-9206))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4840))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-7256))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-4661))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-7110))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(11308))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(9183))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1815))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-15151))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(12293))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(171))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-2696))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(6410))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-2964))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(1374))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-4672))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(-510))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(9978))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-1078))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(5700))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(7484))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-1453))).
playerSensor(player,objectIndex(1),intPair(rotationZ(950))).
playerSensor(player,objectIndex(1),player(velocityY(153))).
playerSensor(player,objectIndex(1),player(velocityX(-1838))).
playerSensor(player,objectIndex(1),intPair(y(-1177))).
playerSensor(player,objectIndex(1),intPair(x(-210))).
