asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8095))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(29992))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-39872))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2240))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-25720))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-35540))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-58223))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(19240))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(47085))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(7522))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-8247))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(58417))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-16902))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-32049))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-10677))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-8524))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(407))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(23276))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(1079))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(42606))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-16462))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(33308))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-16885))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(32782))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-639))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-10751))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(5853))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-24708))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(1954))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-2195))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9779))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(5434))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(1743))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(154))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(612))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-4541))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(8156))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-25726))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(45235))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1190))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-39115))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-49036))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-14480))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-47225))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(14749))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-16831))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3239))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(3170))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-8673))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-25388))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(19289))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-17693))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(13997))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(16357))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-8603))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(4341))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-1252))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(1126))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-3359))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(719))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(3146))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-13871))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-9091))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-18832))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(2448))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(6360))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-1519))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(9112))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(8717))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(2515))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-7715))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-4609))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6683))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(8612))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-701))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-9916))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(608))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-10582))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(2310))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(11063))).
playerSensor(player,objectIndex(1),intPair(rotationZ(807))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
