asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-9511))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(14674))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(36136))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(2849))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-111))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-17364))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-20350))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-3669))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(37862))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4906))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-15207))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(19200))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-22978))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(23529))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-19412))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-9580))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-36086))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2409))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(11425))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-30168))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2553))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-6872))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-1350))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(4984))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8050))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-2803))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1314))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(14040))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-40952))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5048))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(28954))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(167))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-28293))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6519))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(30302))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10783))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(23982))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-11088))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-7294))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1779))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2471))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-7490))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-10045))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-29108))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(7858))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-4123))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(3913))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4070))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-14953))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(7325))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9317))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-9389))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-5349))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-5068))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(4429))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(8739))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(-88))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(-533))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-908))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(4334))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(5407))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-1459))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(1606))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-1115))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-8109))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(8045))).
playerSensor(player,objectIndex(1),intPair(rotationZ(997))).
playerSensor(player,objectIndex(1),player(velocityY(1))).
playerSensor(player,objectIndex(1),player(velocityX(2))).
playerSensor(player,objectIndex(1),intPair(y(-3073))).
playerSensor(player,objectIndex(1),intPair(x(-5773))).
