asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(13363))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(33566))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(1752))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-2595))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(33038))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-25753))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6149))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(16667))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-19013))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(27414))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9450))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2074))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-38081))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4565))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-7858))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(13602))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4144))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-12738))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(25132))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(485))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(388))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-15402))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(21793))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-9727))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(21357))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-15627))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-7862))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-17604))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-6500))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(2178))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-196))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3201))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-6725))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-30891))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2878))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(8644))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-25739))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9005))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-24857))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(6240))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(3678))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(71))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-1140))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1778))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-2687))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-2125))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(6669))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(4578))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4265))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(9196))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-1425))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-12504))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(4517))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9209))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1274))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-10597))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-7880))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-6667))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(5432))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(10647))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-171))).
playerSensor(player,objectIndex(1),player(velocityY(7))).
playerSensor(player,objectIndex(1),player(velocityX(15))).
playerSensor(player,objectIndex(1),intPair(y(-3080))).
playerSensor(player,objectIndex(1),intPair(x(-5786))).
