asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-5679))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(4880))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(4181))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(7441))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(3946))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-10308))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(8129))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(8966))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-4646))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(8707))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(y(2049))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(7797))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(529))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(2496))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(4473))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(6809))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-107))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-25))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(8095))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(3234))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(x(3006))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-5863))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-8427))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-8856))).
playerSensor(player,objectIndex(1),intPair(rotationZ(761))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
