asteroidSensor(asteroidClone,objectIndex(12),intPair(x(889))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-4052))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(9777))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-22884))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2008))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(7929))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(19964))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(3091))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7500))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(106))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(329))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(4905))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2172))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-12307))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4191))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(3258))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(1974))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3034))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-5021))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(12129))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-2393))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(10208))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-2525))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(9862))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(4408))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(1233))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-3071))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-2298))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-8246))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-4004))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(8182))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(7066))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-2675))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-3389))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(5366))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-6077))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(4172))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6136))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-2298))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-3496))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-2350))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(-2321))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(11668))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-1386))).
playerSensor(player,objectIndex(1),intPair(rotationZ(719))).
playerSensor(player,objectIndex(1),player(velocityY(1180))).
playerSensor(player,objectIndex(1),player(velocityX(-561))).
playerSensor(player,objectIndex(1),intPair(y(-2205))).
playerSensor(player,objectIndex(1),intPair(x(2111))).
