asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-11755))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(64972))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(9193))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-10675))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-1631))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2975))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-19236))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-35779))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-20884))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6905))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(1614))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-29080))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(50427))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1623))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-42566))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8598))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-30395))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(3007))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-4485))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(175))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-10545))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-28715))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(5161))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-15893))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-53001))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(16947))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(23104))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9926))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(12693))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(33434))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-45259))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2919))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-28385))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(46529))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(8873))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(3915))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-1208))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-1978))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-23046))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-16464))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-12963))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-24139))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(4192))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-3769))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(4163))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11790))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-65283))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-231))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(27055))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-55053))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(2158))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(2220))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(399))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1466))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-5922))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(7184))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-3653))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-11270))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1606))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(8664))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(-11813))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-18274))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(36282))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-18733))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(35733))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-40683))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(17078))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(19849))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-10881))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-3403))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(3160))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-777))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(7774))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(7031))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(1357))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-5014))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-606))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-13594))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-6881))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(3353))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-8150))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(-291))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-914))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
