asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(13562))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-2910))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(34454))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9841))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(34320))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(2074))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(241))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-15978))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(28262))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(21995))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-16738))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-26104))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-38924))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4707))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-8344))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(13917))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-26498))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6258))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(17410))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-20177))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-8366))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-18410))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-6733))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-661))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(9460))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-27039))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9310))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2006))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-3915))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(5341))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4368))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-13463))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(26254))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(392))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(22436))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-10127))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2987))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-6950))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-32415))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2741))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(6715))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-2015))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-1898))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(6175))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(4383))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4208))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8859))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-1829))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-13223))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9240))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1286))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-10243))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-7137))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-6197))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(5138))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(10087))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(1831))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(2040))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(1874))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(2732))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(3591))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-275))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(3524))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-103))).
playerSensor(player,objectIndex(1),intPair(rotationZ(473))).
playerSensor(player,objectIndex(1),player(velocityY(4))).
playerSensor(player,objectIndex(1),player(velocityX(9))).
playerSensor(player,objectIndex(1),intPair(y(-3076))).
playerSensor(player,objectIndex(1),intPair(x(-5780))).
