asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-46018))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(42941))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10691))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-2056))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(26754))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(15210))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-50879))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(33100))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(38007))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-6922))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-29257))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-3808))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-10709))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-54))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-4523))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-20279))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(15639))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-29951))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-33095))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-51732))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(13259))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(6034))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-6555))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-3938))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(25202))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(23494))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-3670))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-17564))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-5885))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-4066))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(2479))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(4851))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(3737))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-22726))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(19897))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(7910))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(19944))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(5352))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(22773))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(18565))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-19565))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-32049))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-11368))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(-78))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-10400))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-7737))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-10718))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(15590))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(7401))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-5243))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-7946))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-4323))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(2250))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(9342))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(1627))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(591))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-5835))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-9851))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-16390))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(45624))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(3081))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(817))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-19004))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-18312))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(8561))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(-996))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(3197))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-2859))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-16561))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-4985))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-1505))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-9153))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(655))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-305))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(1393))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-7480))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(6892))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(599))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(2625))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(195))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(3113))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(1029))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-11129))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-1504))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-10740))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(4606))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-779))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
