asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-41379))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-18098))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8425))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(32250))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-43406))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2686))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-38914))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-18433))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(16191))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(8499))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-9204))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-27468))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(45180))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-17651))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(35259))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(34718))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-34496))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-11384))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-3697))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(25755))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-52983))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-15407))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-51014))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(486))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3066))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(2149))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-9901))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-27571))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-1087))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-21204))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(16018))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(18648))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-10097))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1209))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(4467))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-15572))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-11631))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-22313))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(7611))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(62717))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(8836))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-27926))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(48641))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1474))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-9935))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-1290))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11433))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-62854))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-11))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-19490))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6543))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-28438))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(2645))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(21791))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9875))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(7690))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(3168))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-739))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-3795))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(3566))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(985))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(1844))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-893))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(3592))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(10514))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-1032))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(8235))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(1755))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-5944))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-4058))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6184))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(7675))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-2638))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-10804))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-188))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-12558))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1848))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(9489))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(5417))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-7875))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(4283))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-10196))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-901))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
