asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(9843))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-23165))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2055))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(727))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(2986))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(12411))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7972))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(181))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(4038))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(87))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(5279))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2141))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-2524))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(10422))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(8027))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-12556))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4227))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(3506))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(1065))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-3339))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-2375))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(6995))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-2749))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-3898))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-2731))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-3598))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(11520))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(8034))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(20215))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-3945))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(1586))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(2985))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-5212))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-2659))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(10074))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-8055))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-3890))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(5320))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-5805))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(3928))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6008))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-2766))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(-2163))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-1359))).
playerSensor(player,objectIndex(1),intPair(rotationZ(736))).
playerSensor(player,objectIndex(1),player(velocityY(988))).
playerSensor(player,objectIndex(1),player(velocityX(-469))).
playerSensor(player,objectIndex(1),intPair(y(-2012))).
playerSensor(player,objectIndex(1),intPair(x(2020))).
