asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3538))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(38))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(3194))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4865))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(1673))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(6458))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(3440))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(2019))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(7487))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-13179))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(375))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(6476))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-343))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(7250))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(5870))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-4173))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(4306))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(11277))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-4872))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-5996))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-7759))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(6723))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-8807))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-2471))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(8674))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-8011))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-423))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
