asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-21030))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(5436))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-6203))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(49241))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(6706))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7392))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(25174))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(17985))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-32330))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1290))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-21990))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(37113))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13927))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-48341))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(1300))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-40613))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-12500))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-6052))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(15638))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(37967))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-584))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-34284))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-26826))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-9167))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-5513))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(749))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-9295))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-39137))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(11673))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-11158))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4379))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-16745))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-20730))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(13948))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9573))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(620))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-10200))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(9683))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-6028))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-47723))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(6188))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-13409))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(17202))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(42197))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(29145))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-14297))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(28651))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-28340))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-13633))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(478))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(1009))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(2344))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3610))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(5349))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-1297))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(2062))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(4240))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(11469))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-5414))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-6134))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(5995))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-405))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(937))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-9863))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-8621))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(-326))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(325))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-10240))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-3671))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-11403))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(7))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(-2506))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-2558))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(10986))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(11077))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(4137))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-840))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
