asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-57080))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-36998))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(3829))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(30220))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(17399))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(15017))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(52008))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(28841))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(9012))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(23733))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(6105))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(17670))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-32565))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-37530))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-12936))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(9119))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-9561))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(11061))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-20591))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-12384))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-56274))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(36206))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(41527))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-25022))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(23336))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(-530))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-21980))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-19677))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-8147))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-32294))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-22786))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-2329))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-21742))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-5119))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-12969))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-9615))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(3176))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(6901))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(9994))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-8436))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-10556))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(3288))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(1325))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(13894))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(5568))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(3988))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(2788))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-1041))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-2766))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-6226))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-13435))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(28767))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(23270))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-4435))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(31085))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-13341))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(21390))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-2530))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-2074))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-2960))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(1519))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-4506))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-2336))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(1848))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-4791))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-2034))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-7578))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(3562))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(5091))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-7485))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(789))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-9590))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-7295))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(3528))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(4272))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(9108))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-4343))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(889))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(y(7634))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(x(8648))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-2037))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(-73))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-943))).
playerSensor(player,objectIndex(1),player(velocityY(143))).
playerSensor(player,objectIndex(1),player(velocityX(61))).
playerSensor(player,objectIndex(1),intPair(y(539))).
playerSensor(player,objectIndex(1),intPair(x(221))).
