asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-30156))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-66219))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(21976))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10263))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(35701))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-68819))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-19128))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-36328))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(31832))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(4723))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(9312))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-43407))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(5418))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-9723))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(24128))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(27839))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-10408))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-15595))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-3901))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-14169))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-81434))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1691))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-16092))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-801))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(458))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(9963))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(8999))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(3176))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(9771))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-22398))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-21821))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(3173))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(-1293))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-4181))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(3917))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-2834))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(5455))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(4976))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-10259))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-16213))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(1336))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(280))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(8883))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-6708))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-5493))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8098))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-2977))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-1891))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-14828))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(16740))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(8884))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-35292))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-36280))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(8181))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(27183))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(920))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(4713))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-14368))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-3385))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-20486))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-5))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(3176))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-6838))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-2877))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(2128))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2502))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(8209))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(8046))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-6233))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-4917))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-7546))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(8240))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-5145))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-10929))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(1846))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-2313))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-3141))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(-1162))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(y(-2289))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(x(-2380))).
playerSensor(player,objectIndex(1),intPair(rotationZ(713))).
playerSensor(player,objectIndex(1),player(velocityY(1750))).
playerSensor(player,objectIndex(1),player(velocityX(-850))).
playerSensor(player,objectIndex(1),intPair(y(-678))).
playerSensor(player,objectIndex(1),intPair(x(-3324))).
