asteroidSensor(asteroidClone,objectIndex(19),intPair(y(32304))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-12363))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(24551))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(464))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(1585))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-2431))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(16281))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-18410))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(2000))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(534))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-25366))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6093))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-15051))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-7600))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-17187))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3312))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-6609))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(29))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-7607))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(13439))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(33175))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(21460))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-9520))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(21027))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(43))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-25065))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8846))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-24209))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-2243))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(6926))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(4680))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(9370))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-1215))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-8265))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(13260))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-37644))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4492))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4028))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-15104))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(26975))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9247))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-6379))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1777))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-30100))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2950))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(8221))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(5994))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(3908))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-686))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1660))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-2050))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4294))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-12132))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(4090))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9192))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1267))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-10781))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-6910))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-350))).
playerSensor(player,objectIndex(1),player(velocityY(10))).
playerSensor(player,objectIndex(1),player(velocityX(20))).
playerSensor(player,objectIndex(1),intPair(y(-3082))).
playerSensor(player,objectIndex(1),intPair(x(-5791))).
