asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-81038))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1655))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10254))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(5359))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-9595))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(524))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(35489))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-68482))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-19049))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-65895))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(21852))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(8763))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-34993))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(23955))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(27643))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(9772))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(4662))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-3317))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-1841))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-14723))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-36142))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(31619))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(16548))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-15965))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-864))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(3997))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-10242))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-20317))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-29929))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(9253))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-43089))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(3268))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(-1228))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-4224))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-14292))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(34))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(3310))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(7749))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(8788))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(3134))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(9658))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-22253))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-21604))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-2682))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(5122))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(4714))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-10080))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-15908))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(1197))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(305))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(8992))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-6782))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-5261))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8140))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-2834))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-15475))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-3846))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-14111))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-35983))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(8084))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(26828))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(879))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(4788))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-6751))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-3049))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(2295))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2475))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(7882))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-6352))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-4693))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-7621))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(8395))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-5206))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-11061))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(1883))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-2208))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-2995))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(-1484))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(y(-2522))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(x(-2114))).
playerSensor(player,objectIndex(1),intPair(rotationZ(754))).
playerSensor(player,objectIndex(1),player(velocityY(2010))).
playerSensor(player,objectIndex(1),player(velocityX(-976))).
playerSensor(player,objectIndex(1),intPair(y(-938))).
playerSensor(player,objectIndex(1),intPair(x(-3198))).
