asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-6781))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(11728))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-31154))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1254))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-19624))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-10979))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(27366))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-893))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-2))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(15912))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-4584))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-2630))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-2369))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(21396))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(2303))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(1594))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-10670))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(20446))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-639))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(3622))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(4963))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(1933))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3025))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(1660))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(3400))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-3870))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(11016))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5257))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(10554))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-9446))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(16117))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-6494))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-3716))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-15053))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6494))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-14597))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(2802))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(6056))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(405))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-6233))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(16512))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-6444))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-4879))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-18354))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4012))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(2337))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(7320))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-593))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-89))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(540))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(-10000))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(7413))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-3997))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-11113))).
playerSensor(player,objectIndex(1),intPair(rotationZ(658))).
playerSensor(player,objectIndex(1),player(velocityY(87))).
playerSensor(player,objectIndex(1),player(velocityX(124))).
playerSensor(player,objectIndex(1),intPair(y(-3675))).
playerSensor(player,objectIndex(1),intPair(x(-6979))).
