asteroidSensor(asteroidClone,objectIndex(8),intPair(y(1155))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-271))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-543))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-14989))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(680))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3874))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(4982))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-5766))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(5838))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(2788))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(5434))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(12897))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-4247))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(6046))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-5602))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(3048))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(6710))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(2692))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(804))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(7914))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(6168))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(4468))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-4463))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-7068))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-1991))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(7118))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-5322))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3174))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-3707))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-9729))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-986))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
