asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-41138))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-4833))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-32168))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-13269))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-21375))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-20981))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(46226))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(36971))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-4490))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-33912))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-2887))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-20453))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-15085))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-17738))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-18156))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-13912))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-30647))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-23653))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-11713))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(38281))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(4619))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-3733))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-21797))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(5205))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(12874))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(17547))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-15233))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-549))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(y(-5114))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-53496))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-17502))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(18105))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-18316))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-5883))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(10343))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(10850))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-5106))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(309))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(8024))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-5993))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3503))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(48218))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(44416))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(18346))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-32331))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(1579))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-6494))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-19541))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-8251))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-7210))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-1369))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(7956))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(-1272))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(y(-1445))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(x(-1241))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(1872))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(4883))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(x(7000))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-7853))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(1226))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(4898))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(x(7440))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(27155))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(17045))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-9681))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-12656))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(12194))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-8281))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(3575))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(5985))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(11970))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(-2558))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(182))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(7875))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(839))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(y(5134))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(x(2879))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(y(748))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(x(3937))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(y(5731))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(y(4858))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(x(5358))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(y(5024))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(x(5888))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(y(-954))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(x(265))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(y(-1078))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(x(722))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(y(1012))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(x(-11867))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-875))).
playerSensor(player,objectIndex(1),player(velocityY(608))).
playerSensor(player,objectIndex(1),player(velocityX(-1768))).
playerSensor(player,objectIndex(1),intPair(y(801))).
playerSensor(player,objectIndex(1),intPair(x(-4743))).
