asteroidSensor(asteroidClone,objectIndex(20),intPair(x(42951))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-7605))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(55533))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(7700))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-24250))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-15665))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(31999))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-203))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1942))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-24548))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(40879))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-10293))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-55117))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-7849))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-16072))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(31484))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-33278))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-15875))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-30408))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-10202))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-7578))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-1188))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(1477))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3356))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(3855))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(3921))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(787))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-7388))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(18600))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(45549))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(6866))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(688))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(21613))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-46389))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-13857))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-44683))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-23924))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(17610))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9714))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-7601))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-5042))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(4861))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-2753))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(644))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-16497))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(1681))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(3573))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-1846))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(9701))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-7018))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-999))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-37597))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7874))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(28478))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-37502))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(13782))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-15048))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(5390))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-22205))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(1490))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(754))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(1752))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-15338))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(12641))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(14821))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-5013))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(390))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(2259))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-12730))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(9459))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(3025))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-8903))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-4978))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(9240))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(597))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-9320))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(1142))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-9257))).
playerSensor(player,objectIndex(1),intPair(rotationZ(894))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
