asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(36551))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(17642))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-56874))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(15212))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(30605))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(52717))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(3912))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(-680))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-22311))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-4490))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(31738))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-22206))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(6189))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(17895))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-32855))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-37431))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-57675))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-13110))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(9462))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-9895))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-21039))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-2179))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-10846))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-19828))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-8283))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-32631))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-2844))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-6495))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-5033))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-13255))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-9824))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-13632))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(22034))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(10282))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-8791))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-2808))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(1272))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-7772))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(41918))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-25277))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(23718))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(9135))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(24153))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-13738))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(29433))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(23792))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-23144))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-38139))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(29435))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(11339))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-2258))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-2137))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-12743))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(3254))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(7129))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-5079))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-2562))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(1899))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-4492))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(2887))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(1222))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(14400))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(6006))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-2325))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(3892))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(4139))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(3077))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(5310))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-7223))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(762))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-9419))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-989))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-6912))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(3409))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(4194))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(8801))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-4759))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(834))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(y(7525))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(x(8511))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-2490))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(235))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(9024))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(7834))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-843))).
playerSensor(player,objectIndex(1),player(velocityY(108))).
playerSensor(player,objectIndex(1),player(velocityX(46))).
playerSensor(player,objectIndex(1),intPair(y(574))).
playerSensor(player,objectIndex(1),intPair(x(236))).
