asteroidSensor(asteroidClone,objectIndex(19),intPair(y(29944))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(1049))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-1906))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-24124))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5912))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-15844))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(3655))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-11155))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(22682))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-14145))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(25562))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-8595))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-5991))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(823))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(1429))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-2404))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(12928))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-36240))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4256))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(15042))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-16470))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(709))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-13200))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-6760))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-27559))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3180))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(6861))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(5203))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(4646))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-105))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-1907))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(772))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4390))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-6799))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(12915))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(31918))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(690))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(20390))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-8855))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(19965))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(818))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3669))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-6235))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-22899))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8337))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-22130))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1282))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-2))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-2623))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(7750))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(5005))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(9930))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-541))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-10934))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(2717))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9139))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1247))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-11372))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-659))).
playerSensor(player,objectIndex(1),player(velocityY(25))).
playerSensor(player,objectIndex(1),player(velocityX(50))).
playerSensor(player,objectIndex(1),intPair(y(-3097))).
playerSensor(player,objectIndex(1),intPair(x(-5821))).
