asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5967))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-19903))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-33124))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7223))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-25573))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-12655))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(16712))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(41024))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(4935))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(28145))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-13676))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-38591))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-5713))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(47038))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(6357))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(35795))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13318))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-45969))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(1515))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(16716))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(124))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(1779))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-8401))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(36222))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-438))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(27660))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-26612))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-12849))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(2648))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3699))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(5872))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-5423))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9523))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-535))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(987))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(15329))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-46413))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-8804))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-4790))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1082))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-8946))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4026))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-14834))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-2027))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(2520))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(5111))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(6391))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-7174))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-773))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(-577))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-351))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(-578))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(24018))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-30520))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1061))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-21094))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-12025))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-37196))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(10934))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-9796))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-19612))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(12666))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(8648))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(10296))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-4648))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-6516))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-10407))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-9884))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-9368))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-2370))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-9620))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(-4634))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-2807))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(11435))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-908))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
