asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1462))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(1114))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3107))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(6717))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-526))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-5292))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3773))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-19639))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(17059))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-2641))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-755))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3120))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(395))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(5748))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-886))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-2315))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(9011))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(2757))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(865))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(4306))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(2047))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(586))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2532))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-9436))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-7657))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(6456))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3599))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-2804))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(8864))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(7733))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-987))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(7407))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(8687))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(3175))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(32))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-1400))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-10450))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-5324))).
playerSensor(player,objectIndex(1),intPair(rotationZ(368))).
playerSensor(player,objectIndex(1),player(velocityY(-529))).
playerSensor(player,objectIndex(1),player(velocityX(778))).
playerSensor(player,objectIndex(1),intPair(y(-2533))).
playerSensor(player,objectIndex(1),intPair(x(1874))).
