asteroidSensor(asteroidClone,objectIndex(4),intPair(y(2819))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(-3711))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(8483))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(2475))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(7248))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(5230))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(7521))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(1848))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(-5089))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(6833))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-7864))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(4704))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(10079))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(9119))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-66))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
