asteroidSensor(asteroidClone,objectIndex(5),intPair(y(6003))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(941))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(5008))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-6360))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(3184))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(8263))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(5338))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(5558))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(3859))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(1292))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(6242))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-7905))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-511))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(9512))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(241))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(10402))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(9957))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-5042))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(2337))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(6557))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(y(1699))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(x(5310))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-25))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
