asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-989))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-37514))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7862))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(28395))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-37372))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1925))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-46244))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(18565))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(45465))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(6830))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-24484))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(40785))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-15622))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(31928))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-13823))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-44544))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(1465))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-7570))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(55376))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(7676))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-24170))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(42826))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-10176))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-7526))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-179))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-10268))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-54948))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(703))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(21523))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-1133))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(1499))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3362))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(3892))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-7804))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(786))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(1815))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-15210))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(12567))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(14737))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(372))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(2211))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-12667))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-7295))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-1863))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(9733))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-7036))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-16027))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(31413))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-33154))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-15819))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-30318))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(13730))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-14951))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(5364))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-22069))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-23844))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(17519))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9710))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(3838))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(735))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-7546))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-5069))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(4889))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-2835))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(618))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-5103))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-16370))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(1639))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(3421))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(9499))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(3053))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-8968))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-4998))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(9274))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(667))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-9287))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(1172))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-9185))).
playerSensor(player,objectIndex(1),intPair(rotationZ(851))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
