asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-39916))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(8397))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-26504))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-17443))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8212))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(30791))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-14808))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2398))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-26339))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(43516))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-16883))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(24153))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-50432))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(2809))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-32914))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-10927))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-9023))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-870))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-10992))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(2198))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-2726))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(870))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3178))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(2247))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-14473))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(46440))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1290))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-41122))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-59861))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(259))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-161))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(11))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-18935))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(14712))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(892))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(3613))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-1347))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(7867))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-8586))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(59938))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-48565))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(15259))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-17772))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6097))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-26027))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(17168))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-9131))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-4277))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(4067))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-461))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-9989))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-20063))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(2853))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(7829))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6507))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(8281))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-1386))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-10230))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(326))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-9100))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(33998))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-17314))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(33467))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-36734))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-9107))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-26160))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(20174))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9813))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(6232))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(1380))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-2487))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(8802))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(8326))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(2247))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-7089))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-4414))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-11281))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(2147))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(10506))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(6962))).
playerSensor(player,objectIndex(1),intPair(rotationZ(23))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
