asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-21072))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-5828))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(47564))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(4346))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(45560))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(36449))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-31810))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-52887))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-3670))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-21438))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-18968))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(18068))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-31883))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(1429))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-33448))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(5128))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(12646))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-494))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-2972))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-20167))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-14876))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-20689))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(37637))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-8025))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-6810))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-1266))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(26649))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-13459))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(7715))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(2006))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-17328))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(17762))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-17982))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(17259))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-17383))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-17866))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-4368))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-6170))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(257))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-14817))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(y(-1300))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(x(-1730))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(1615))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-23501))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-11577))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-40800))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-4755))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-13000))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(43822))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(10055))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(10630))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-858))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(118))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-5277))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(4567))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-7646))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(3317))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(5864))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(11295))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(5422))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(-1953))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(215))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(8397))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(1054))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(x(5597))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-30317))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(16608))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-9389))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-12462))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(11864))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(7805))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-5397))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(-911))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(y(-5227))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(x(7145))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-8088))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3544))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(y(4509))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(x(2775))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(y(1282))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(x(3595))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(y(6200))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(x(7931))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(y(5169))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(x(5196))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(y(5219))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-824))).
playerSensor(player,objectIndex(1),player(velocityY(802))).
playerSensor(player,objectIndex(1),player(velocityX(-2334))).
playerSensor(player,objectIndex(1),intPair(y(606))).
playerSensor(player,objectIndex(1),intPair(x(-4178))).
