asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(38259))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-45085))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-21235))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-17104))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-12679))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-12516))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-2481))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-12680))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(7806))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-35263))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(5774))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1993))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-45520))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(9028))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(36380))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(38828))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-20316))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-57946))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(18828))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-24353))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-27627))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(19716))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(22838))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-12831))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(3157))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(3616))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(5588))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-49871))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-3501))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-30666))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(49888))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-19824))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-38972))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-12147))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-31564))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(26369))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10052))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(11816))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-2430))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(2149))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(5078))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(5684))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(18114))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-142))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(6629))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(1038))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-71325))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-777))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(30290))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-60203))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(3909))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-6445))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-597))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2748))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(282))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(2106))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(6885))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-18684))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-16277))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-28681))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(365))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-5271))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(5962))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-6180))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-12429))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-1646))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-16173))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1003))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(6611))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-3060))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(-522))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(-10024))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(-1706))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-5683))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-8426))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-4611))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-7260))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(6398))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-1796))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(-147))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(449))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(-2216))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(908))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(11679))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-29))).
playerSensor(player,objectIndex(1),player(velocityY(-1604))).
playerSensor(player,objectIndex(1),player(velocityX(-380))).
playerSensor(player,objectIndex(1),intPair(y(-3504))).
playerSensor(player,objectIndex(1),intPair(x(-6607))).
