asteroidSensor(asteroidClone,objectIndex(4),intPair(x(5871))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(6631))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(6459))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(1170))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-6741))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(8722))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-34))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-6564))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(389))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(1835))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(5470))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(3569))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(5821))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(4235))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(5926))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-737))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(10285))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(11204))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-592))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
