asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-514))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(8378))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(5716))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(1773))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-16955))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1010))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3550))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2798))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-6317))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-1468))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(5427))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-7062))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3427))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-8853))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(10162))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(283))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-607))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(2080))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(4302))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(2944))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(14657))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-3568))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(5310))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-2462))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-2985))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2830))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-1972))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(6303))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(4066))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-970))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(6165))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(359))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(5687))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(5377))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-439))).
playerSensor(player,objectIndex(1),player(velocityY(-1764))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-635))).
playerSensor(player,objectIndex(1),intPair(x(0))).
