asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-47375))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(39432))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(44497))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10751))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-34675))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(28157))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(16096))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-53063))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(34357))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-53897))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(13970))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-12002))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-21043))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(3384))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(271))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-20209))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-18864))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-20869))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-34267))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-11440))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-23655))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(21289))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(8356))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(21477))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(5657))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(7283))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-7771))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-4139))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(27583))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(25658))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-11780))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(17938))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-3992))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-1735))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(8451))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-6535))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(11185))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-7418))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-30486))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-2343))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-4787))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-11812))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(9573))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-2319))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(811))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-18192))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-3127))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-8498))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-10461))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(2761))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(5681))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(1577))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-6392))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(5433))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(1875))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(1799))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(3176))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-10506))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(16461))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-31009))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(48208))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(25199))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(20469))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-19255))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-5575))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-3104))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(-348))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-9003))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-3771))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(2839))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-1433))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-1127))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(3222))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-471))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-6540))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(1245))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(3914))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-8894))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(932))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-1317))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-9345))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(4170))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(4692))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(10752))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-949))).
playerSensor(player,objectIndex(1),player(velocityY(634))).
playerSensor(player,objectIndex(1),player(velocityX(271))).
playerSensor(player,objectIndex(1),intPair(y(48))).
playerSensor(player,objectIndex(1),intPair(x(10))).
