asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-26223))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-1032))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(9175))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(9349))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1801))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-15261))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-2636))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4621))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(6204))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-6264))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(13111))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(993))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-2541))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(2452))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-7302))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(15487))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-3221))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-5979))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4819))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(10565))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2570))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(12387))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(6))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-764))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-3565))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-9432))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-1066))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(22952))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-2776))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(1842))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-2645))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(6341))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(6217))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-7448))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-4706))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-7295))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(-440))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(9912))).
playerSensor(player,objectIndex(1),player(velocityY(-119))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-3944))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(12753))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-4108))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-2843))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(1266))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-4615))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(5600))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(7369))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(11178))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-1419))).
playerSensor(player,objectIndex(1),intPair(rotationZ(954))).
playerSensor(player,objectIndex(1),player(velocityX(-1960))).
playerSensor(player,objectIndex(1),intPair(y(-1187))).
playerSensor(player,objectIndex(1),intPair(x(-372))).
