asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(31555))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5860))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(3547))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-10806))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(22142))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-15910))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(779))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(1264))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(894))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-1754))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(29262))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(14684))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-12665))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-6517))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-15456))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3246))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(6468))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(1193))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(12833))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-35835))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4187))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(735))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-23765))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(20081))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-8663))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(19658))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-5879))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(548))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-26825))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-22274))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8190))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-21529))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-2080))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-1532))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(5099))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4417))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1242))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-6565))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(12763))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-13867))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(25154))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-8406))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(1041))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3773))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-6126))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(4974))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(4859))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-144))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1172))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(588))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-2732))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(7988))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(10092))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-347))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-10588))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(2320))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9124))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-11543))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-907))).
playerSensor(player,objectIndex(1),player(velocityY(32))).
playerSensor(player,objectIndex(1),player(velocityX(65))).
playerSensor(player,objectIndex(1),intPair(y(-3104))).
playerSensor(player,objectIndex(1),intPair(x(-5836))).
