asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-18020))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-53362))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-3941))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-32393))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(52430))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-61690))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(20252))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-26979))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(8487))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-1183))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2576))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-14307))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-13354))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-75899))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1191))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(32738))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-64102))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-1692))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(1384))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(7289))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(3866))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-20365))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-18786))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-13306))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-20998))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(40755))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-21513))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(40171))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-48418))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-38948))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(4592))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-7928))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(14045))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(7181))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-31096))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(21712))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(25101))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-32120))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(6814))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(22218))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(338))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(5762))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-2433))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-18124))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(547))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(5056))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-7754))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-11950))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(3634))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-22748))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-41390))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-13377))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-13909))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-3124))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(-726))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-13360))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-33720))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(28841))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10147))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(6052))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(2590))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(8191))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(4495))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(-384))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-4778))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(5037))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-8093))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-713))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(793))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(1317))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-5619))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-5277))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(4466))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2116))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(3887))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(-608))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(624))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(10414))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-7744))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-7897))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-1782))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-8590))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-2243))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8694))).
playerSensor(player,objectIndex(1),intPair(rotationZ(959))).
playerSensor(player,objectIndex(1),player(velocityY(814))).
playerSensor(player,objectIndex(1),player(velocityX(1542))).
playerSensor(player,objectIndex(1),intPair(y(-2920))).
playerSensor(player,objectIndex(1),intPair(x(-4293))).
