asteroidSensor(asteroidClone,objectIndex(5),intPair(y(2196))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(92))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(8164))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(5378))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-452))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(851))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(4823))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-661))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(13847))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-3880))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(5649))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-3983))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-4190))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2930))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(6490))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(5475))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(2406))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-16050))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(858))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(5534))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(3646))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3699))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-3565))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-6663))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-1709))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(6206))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-6261))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3311))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-2771))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-9256))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-705))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
