asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(15710))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(38622))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(3910))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-17595))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(14695))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-43729))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5516))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(42529))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(5644))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-12404))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(32650))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-141))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-30750))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6877))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(14116))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-34451))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-4135))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(25630))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-23074))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-11243))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-23006))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-600))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(3354))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1354))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-4709))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-8062))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-3311))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1765))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-8231))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(3302))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-10922))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(10041))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9422))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(7893))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(21650))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-26814))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-594))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-19261))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-41112))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(1954))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(3270))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3881))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(6942))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-17322))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(6894))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-4719))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(6528))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(7204))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-9521))).
playerSensor(player,objectIndex(1),intPair(rotationZ(104))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-11110))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(33095))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-12072))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(26099))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-11052))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-33221))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(9422))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-7008))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-8221))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-2900))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-3521))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(3458))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-3081))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-7299))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-1525))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(1088))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-11519))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
