asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-58498))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-35108))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-20653))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-18933))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(20920))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-21060))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-6336))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-4253))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(12711))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-33363))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-24899))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-12831))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-24746))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(5841))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(14745))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(19913))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-14247))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(14898))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(778))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-2188))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-22798))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-16799))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-23375))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(43575))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(6859))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(12655))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-3701))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(732))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-18645))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(7477))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-13497))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(3592))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-43909))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-5481))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-15476))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-23863))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(51697))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(41265))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-2213))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(31310))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(20642))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-12077))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(5695))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(6979))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(17512))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-5924))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(-7529))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(-85))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(y(3414))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(53587))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(49297))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(20628))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-36009))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(2803))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-37726))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-1000))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-17633))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(10562))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-10885))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(-4239))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3164))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(-1967))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(593))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(x(3406))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(y(2302))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(x(6691))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(x(8280))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(y(3198))).
asteroidSensor(asteroidClone,objectIndex(136),intPair(y(-9394))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-20537))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-5495))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-9153))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-24252))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-10104))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-10500))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(9200))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(-929))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(y(10268))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(x(3728))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(y(-3632))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(x(6745))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(y(1877))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(x(-995))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(y(100))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(x(4899))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(y(1239))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(x(-9271))).
asteroidSensor(asteroidClone,objectIndex(136),intPair(x(-1735))).
asteroidSensor(asteroidCloneClone,objectIndex(137),intPair(y(-3647))).
asteroidSensor(asteroidCloneClone,objectIndex(137),intPair(x(5651))).
asteroidSensor(asteroidCloneClone,objectIndex(138),intPair(y(-3648))).
asteroidSensor(asteroidCloneClone,objectIndex(138),intPair(x(5864))).
asteroidSensor(asteroidClone,objectIndex(139),intPair(y(-8924))).
asteroidSensor(asteroidClone,objectIndex(139),intPair(x(-7662))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-204))).
playerSensor(player,objectIndex(1),player(velocityY(62))).
playerSensor(player,objectIndex(1),player(velocityX(-181))).
playerSensor(player,objectIndex(1),intPair(y(1347))).
playerSensor(player,objectIndex(1),intPair(x(-6331))).
