asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(14423))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(5338))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-16602))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(31113))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-12))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-21552))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(37588))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(3469))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-4276))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(40589))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-393))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-18472))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(31934))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11536))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-10551))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-21902))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-7743))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-2674))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(12997))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-32670))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-10634))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-31511))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-911))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(4031))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(3537))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3960))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-3918))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-42575))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5322))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-10445))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(15279))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-29728))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6728))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(20631))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-25219))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(25219))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-11857))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(24757))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2058))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-7923))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-39023))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2143))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(8772))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-5809))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2990))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-9238))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(7403))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-3581))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-16337))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(8912))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9378))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1338))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-8706))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-4164))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(3862))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(7661))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(-1624))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(-2592))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-3134))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(5616))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(6860))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-2407))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(72))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-1924))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-7635))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(7553))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-10531))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-1849))).
playerSensor(player,objectIndex(1),intPair(rotationZ(523))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5772))).
