asteroidSensor(asteroidClone,objectIndex(8),intPair(y(1039))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(5700))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(2642))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(5201))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-588))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-4120))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-6913))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-5084))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-340))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-15395))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(748))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3807))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(5133))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-1883))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(6769))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3226))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(2503))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(532))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(8010))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(5925))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(4153))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(13260))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-4107))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(5894))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-5062))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(3003))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-5681))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-3349))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(6626))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-9548))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-805))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
