asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-21193))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-54321))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(14110))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(48715))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(3443))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(7528))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-8010))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-3797))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(8443))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(21778))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(5716))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(16622))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-31216))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-2399))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-2916))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(-401))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(8656))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-53491))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(34604))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(39711))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-23837))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(21562))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-21124))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-34702))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-12127))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-11644))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-8647))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(2817))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-4979))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-12028))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(25675))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(20843))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-11988))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(18398))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(5844))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(164))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-20445))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-18973))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-7515))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-30727))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-3021))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-19586))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-5514))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-1780))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-10717))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(2034))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-679))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-6679))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(913))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-4179))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(28050))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(26083))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(9771))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-18512))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-1288))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(1613))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-6178))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(5147))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(1802))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(3285))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(1450))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(4070))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-8706))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(4084))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(4636))).
asteroidSensor(asteroidCloneClone,objectIndex(112),intPair(x(1251))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-47641))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(44802))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10763))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(28432))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(16270))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-34985))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-6789))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-9210))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-3663))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(2663))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-1843))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(11546))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(3535))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-10384))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-1280))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-9072))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(10533))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-2414))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(1144))).
asteroidSensor(asteroidCloneClone,objectIndex(112),intPair(y(-2258))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-965))).
playerSensor(player,objectIndex(1),player(velocityY(520))).
playerSensor(player,objectIndex(1),player(velocityX(223))).
playerSensor(player,objectIndex(1),intPair(y(162))).
playerSensor(player,objectIndex(1),intPair(x(59))).
