asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-15182))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-43598))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-14016))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-65110))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-3711))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-13969))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(16080))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(21554))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-29378))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(9110))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-42315))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(8467))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-34265))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(685))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-80078))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1569))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(34976))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-67664))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-18857))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(31100))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10234))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(9308))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(4513))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(8277))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(3032))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(9384))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(4970))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(3497))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(-1070))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-4328))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-3152))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-19908))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(4080))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(5216))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-9284))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-1718))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-14469))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-35689))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(23536))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(27168))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-15655))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-1019))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-21900))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-21078))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-35261))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(7847))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(25967))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(778))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(4192))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-9841))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-14108))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(130))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(3636))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-2314))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(4313))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-9646))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-15169))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-6540))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-3465))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(2701))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2408))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(7088))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(7027))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(860))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(364))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(9258))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-6962))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-6640))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-4149))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-7802))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-4697))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8244))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(8774))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-5353))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-11382))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(1973))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-2488))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-1955))).
asteroidSensor(asteroidCloneClone,objectIndex(89),intPair(y(-2430))).
asteroidSensor(asteroidCloneClone,objectIndex(89),intPair(x(-1865))).
playerSensor(player,objectIndex(1),intPair(rotationZ(803))).
playerSensor(player,objectIndex(1),player(velocityY(2034))).
playerSensor(player,objectIndex(1),player(velocityX(189))).
playerSensor(player,objectIndex(1),intPair(y(-1669))).
playerSensor(player,objectIndex(1),intPair(x(-3038))).
