asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(18716))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(45828))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(6985))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1996))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-7721))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(637))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(56058))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(7783))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-24518))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(43366))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(21916))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-46870))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-7999))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-24761))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(41193))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-15810))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(32237))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-13970))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-45145))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-15766))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-16220))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(31720))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-33689))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-16061))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-30706))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-1371))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(1405))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3335))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(3730))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(12888))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(15100))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(2420))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-10288))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-7750))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-282))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-10376))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-55682))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-24190))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(17915))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9726))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(4196))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(961))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-4951))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(4766))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-2480))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(732))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-12937))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-7697))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(9594))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1034))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-37873))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7914))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(28753))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-37933))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(13958))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-15372))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(5474))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-22660))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(1574))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(645))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(1545))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-7783))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-4712))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(450))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-16922))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(1820))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(4080))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-1786))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(9324))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(2932))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-8687))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-4911))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6957))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(9126))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(360))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-9428))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(1045))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-9498))).
playerSensor(player,objectIndex(1),intPair(rotationZ(989))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
