asteroidSensor(asteroidClone,objectIndex(20),intPair(x(9931))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1753))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-15648))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-5682))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2644))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-1284))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(9338))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(12718))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-569))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-1026))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(6100))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(6106))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-8122))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(10668))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-26660))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4678))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(6590))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-3240))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-6682))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-3342))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-2468))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-2419))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(886))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-4416))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-4865))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-7942))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(5251))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(13845))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(1109))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-2917))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(2376))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-7600))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(15927))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-3681))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-10222))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4748))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(-194))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(9683))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-1024))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(6964))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(10725))).
playerSensor(player,objectIndex(1),player(velocityY(-784))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(23343))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-2610))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(1678))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-4147))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(13086))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-4315))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-1302))).
playerSensor(player,objectIndex(1),intPair(rotationZ(967))).
playerSensor(player,objectIndex(1),player(velocityX(-2179))).
playerSensor(player,objectIndex(1),intPair(y(-1371))).
playerSensor(player,objectIndex(1),intPair(x(-1001))).
