asteroidSensor(asteroidClone,objectIndex(67),intPair(y(3895))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-32793))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-25222))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(23636))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-13673))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-37339))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-57547))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(15170))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(52565))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(29290))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(23680))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-9823))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(9109))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(24063))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(6171))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(17847))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-23067))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-38009))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-13073))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(9388))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-2211))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-10784))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(-648))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-22240))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-19796))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-8254))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-32559))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-22107))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-5052))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-13193))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-9779))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(10220))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-8715))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(1244))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(30523))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(17590))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-4479))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(31598))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(29308))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(11280))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-20943))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(3237))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(7080))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-4556))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(2973))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(14292))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(5912))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(3015))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-56745))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(36477))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(41834))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-2827))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-6437))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-13570))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(21896))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-2316))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-2124))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-12667))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-2841))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(1325))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-4957))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-2513))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(1888))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-2263))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-7730))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(3821))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(4106))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(5263))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-7279))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(768))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-9455))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-1000))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-6994))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(3434))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(4211))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(8867))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-4669))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(846))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(y(7548))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(x(8541))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-2393))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(169))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-873))).
playerSensor(player,objectIndex(1),player(velocityY(115))).
playerSensor(player,objectIndex(1),player(velocityX(49))).
playerSensor(player,objectIndex(1),intPair(y(567))).
playerSensor(player,objectIndex(1),intPair(x(233))).
