asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5819))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(12759))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-35523))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4135))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(769))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-23489))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-8262))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(775))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-1637))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(28738))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-12254))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-6330))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-15157))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(336))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(1137))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-21067))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(3464))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-10538))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(21727))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(19843))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-8515))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(19422))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-5793))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-26260))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3297))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(6165))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(4798))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(5023))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-173))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-1243))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(1517))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-10322))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-6385))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(12647))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(31276))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(14409))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-15479))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(833))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-13654))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(24841))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(1213))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3852))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-6043))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-21792))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8077))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-1831))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1088))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(1043))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-2817))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(8171))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(5171))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4439))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(10217))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-197))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(2015))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9112))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1237))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-11674))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-996))).
playerSensor(player,objectIndex(1),player(velocityY(39))).
playerSensor(player,objectIndex(1),player(velocityX(79))).
playerSensor(player,objectIndex(1),intPair(y(-3111))).
playerSensor(player,objectIndex(1),intPair(x(-5850))).
