asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-17876))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(8320))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-9029))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(65))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-34048))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-11255))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(2518))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11308))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-62007))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-3422))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(34364))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-38297))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-18153))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-50321))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(15927))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-576))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-27149))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(44709))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-17433))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(34902))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-19003))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6417))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-27756))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-9676))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-27171))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-3931))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(61930))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(8712))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-27524))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(48018))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1422))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(25301))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-52261))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-15237))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(595))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3098))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(2336))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(3708))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(575))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(1712))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-1344))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-11166))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-21677))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(7847))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-40965))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8365))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(31837))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-42760))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2604))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-9677))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-1171))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-776))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-20562))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(15649))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(18229))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-9824))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1119))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(4226))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-15261))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(1894))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-6268))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-4159))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6275))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-12197))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1933))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-10909))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(21333))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9858))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(7277))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(2907))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(3383))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(9754))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-1121))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(8395))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(7813))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-2284))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-10641))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-42))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(9777))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(5854))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-8222))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(4608))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-723))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
