asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-73))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(1486))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(1579))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(7641))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(6858))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(5363))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-7509))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3232))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(6234))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(3204))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-13835))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(485))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(6099))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-415))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-4064))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(4551))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(11864))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-4646))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-5441))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(6478))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-7706))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-2297))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(8111))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-7139))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(3176))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-4301))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3025))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-4725))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-648))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
