asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(33259))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-37738))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4508))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6105))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(1621))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-2466))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(32461))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-18539))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(448))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-17276))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-7661))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(13474))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(523))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-25449))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(21532))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-9565))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(21098))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(8312))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(13282))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-15168))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(27069))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9290))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-15175))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-7656))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-7))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3288))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-6634))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(6047))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(3858))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(38))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1686))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-2186))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-1260))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4052))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-12443))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(24675))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(16364))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-6405))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1840))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(2038))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-30269))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2935))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-25210))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8880))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-24348))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-784))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-2218))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(6871))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(4658))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4288))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(9333))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-12212))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(4182))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9196))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1269))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-10742))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-8182))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-6858))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-323))).
playerSensor(player,objectIndex(1),player(velocityY(9))).
playerSensor(player,objectIndex(1),player(velocityX(19))).
playerSensor(player,objectIndex(1),intPair(y(-3082))).
playerSensor(player,objectIndex(1),intPair(x(-5790))).
