asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-21103))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-2365))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(44619))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10756))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(28267))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(16165))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-4864))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-11899))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-7867))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(34456))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(39544))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-23728))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(21398))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(25389))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(20619))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-1753))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-47482))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-53234))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-12052))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(7381))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-3728))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(228))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-20303))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-18908))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-7457))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-30583))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-20971))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-34441))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-10563))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(2784))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(5746))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(8533))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(2769))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-1597))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(924))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(8391))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(21598))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(5680))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(16525))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-31092))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-11521))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-8557))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-11863))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(18122))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-3914))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-1192))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(1592))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-6306))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(5319))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(1846))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(11329))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-10457))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(4136))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-34799))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-54066))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(14026))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(48411))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(3408))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-3085))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-19388))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-5550))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-3029))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(-369))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-6637))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-9085))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(3347))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-554))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-6596))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(1893))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-1302))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-9236))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(4669))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-4155))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(27770))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(25828))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(9652))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-18320))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(3220))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(1327))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(3976))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-8818))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(10665))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-2236))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(1167))).
asteroidSensor(asteroidCloneClone,objectIndex(112),intPair(y(-2265))).
asteroidSensor(asteroidCloneClone,objectIndex(112),intPair(x(1072))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-959))).
playerSensor(player,objectIndex(1),player(velocityY(585))).
playerSensor(player,objectIndex(1),player(velocityX(251))).
playerSensor(player,objectIndex(1),intPair(y(96))).
playerSensor(player,objectIndex(1),intPair(x(31))).
