asteroidSensor(asteroidClone,objectIndex(5),intPair(y(1219))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(6158))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-1310))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(8658))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3354))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-470))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-810))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(1653))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(3620))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(2026))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-1794))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-5864))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-1153))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4408))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(8525))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-18141))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1210))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(15718))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-3158))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(4866))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-1407))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2698))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-8111))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3580))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-926))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(6058))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-8324))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3859))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-1780))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(7358))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-191))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(6591))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-278))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(6274))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(10662))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(4072))).
playerSensor(player,objectIndex(1),intPair(rotationZ(106))).
playerSensor(player,objectIndex(1),player(velocityY(-1370))).
playerSensor(player,objectIndex(1),player(velocityX(2014))).
playerSensor(player,objectIndex(1),intPair(y(-1692))).
playerSensor(player,objectIndex(1),intPair(x(638))).
