asteroidSensor(asteroidClone,objectIndex(2),intPair(y(5443))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(-4069))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(3021))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(7859))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(8862))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(1987))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(-5820))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(3192))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(7113))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-8094))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(4936))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(10356))).
playerSensor(player,objectIndex(1),intPair(rotationZ(832))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
