asteroidSensor(asteroidClone,objectIndex(53),intPair(y(21280))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(36868))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10457))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-26932))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(11752))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-42358))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(2947))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(32448))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-19099))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(14466))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(6168))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-6403))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(13305))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-1807))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-35505))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(10701))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-50914))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-24462))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-934))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(10))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-3153))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(15912))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(-298))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(13960))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(4162))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(12431))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-25822))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-14477))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-23391))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-8892))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(1162))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(15048))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(4611))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-6575))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(6809))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-12745))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-3084))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-17299))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-40720))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(28195))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(6306))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-4963))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-3432))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-10195))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-4049))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(1379))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-3825))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-43284))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(10483))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(35542))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(1900))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(11136))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-7818))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(973))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-6342))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-4772))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(3306))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-199))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-6475))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-3177))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(2033))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-14304))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-16156))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-4988))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-5789))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-10965))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-7095))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(4567))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-3712))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(6431))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-8862))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-605))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(1612))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(7242))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(8808))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(2901))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(674))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-11727))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-963))).
playerSensor(player,objectIndex(1),player(velocityY(-933))).
playerSensor(player,objectIndex(1),player(velocityX(1820))).
playerSensor(player,objectIndex(1),intPair(y(4468))).
playerSensor(player,objectIndex(1),intPair(x(-6358))).
