asteroidSensor(asteroidClone,objectIndex(53),intPair(x(16217))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(21480))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-21148))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-12090))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-20374))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-18940))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-7486))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-30655))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(7454))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-7938))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(-385))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-34892))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-54194))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(14068))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(48563))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(3426))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-21048))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-34572))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(9712))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-18416))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-1767))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-53362))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(34530))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(39627))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-23783))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(196))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-4167))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(27910))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(25955))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-10640))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(2800))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(5795))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(8595))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(2716))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-1720))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(3252))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-47561))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(44711))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10760))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(28350))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-2382))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-4921))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-11964))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(25532))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(20731))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-11582))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-8602))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-11925))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(18260))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-3855))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-1240))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(1603))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-6242))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(5233))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(1824))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(1389))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(4023))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-8762))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(918))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(4110))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(4652))).
asteroidSensor(asteroidCloneClone,objectIndex(112),intPair(x(1162))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(8417))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(21688))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(5698))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(16573))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-31154))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-3053))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-19487))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-5532))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-2972))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-6713))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-9148))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-3695))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(11437))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(3441))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-617))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-6637))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(1963))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-10420))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-1291))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-9154))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(10599))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-2325))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(1156))).
asteroidSensor(asteroidCloneClone,objectIndex(112),intPair(y(-2261))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-962))).
playerSensor(player,objectIndex(1),player(velocityY(552))).
playerSensor(player,objectIndex(1),player(velocityX(236))).
playerSensor(player,objectIndex(1),intPair(y(130))).
playerSensor(player,objectIndex(1),intPair(x(46))).
