asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4266))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(12943))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-36303))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-24179))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5920))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-8624))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(1073))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-1929))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(30049))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-14187))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(25625))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(1454))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(3671))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-11209))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(22765))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(683))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(20437))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-8884))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(20012))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-6008))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(866))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-27672))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3170))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(6921))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(5238))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(4613))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-99))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-93))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-2606))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4386))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-6835))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(12938))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(31974))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(15097))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-16557))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(698))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-13282))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-6797))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-15903))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(783))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3654))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-6251))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-22996))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8360))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-22222))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-2454))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-1965))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(707))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1298))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(7713))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(4991))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(9905))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-571))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-10987))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(2778))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9141))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1248))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-11346))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-654))).
playerSensor(player,objectIndex(1),player(velocityY(24))).
playerSensor(player,objectIndex(1),player(velocityX(48))).
playerSensor(player,objectIndex(1),intPair(y(-3096))).
playerSensor(player,objectIndex(1),intPair(x(-5819))).
