asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-16592))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-4602))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-20444))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-19264))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-18431))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-32527))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(20275))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(5417))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(15816))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-30179))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-7029))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-29523))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-5818))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-52199))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(13412))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(46181))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(3146))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-11505))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(6303))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-6817))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-2118))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-4019))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-10947))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(23296))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(18976))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-19846))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(8779))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-2742))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-4204))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-51350))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(33371))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(38314))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-22926))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(20197))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-33436))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(699))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-3982))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(25716))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(23961))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(5030))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(7627))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(8006))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(132))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-16913))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-3553))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-17928))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-5521))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-8174))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(362))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-46310))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(43276))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10704))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(27057))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(15401))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-3858))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(-136))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-10624))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-7901))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-10947))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(3544))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(204))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-483))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(1433))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-7245))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(858))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(2744))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(421))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(3286))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-1464))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-10439))).
asteroidSensor(asteroidCloneClone,objectIndex(109),intPair(x(3175))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(16097))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-4771))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-1554))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-9435))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(2540))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(6578))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(2169))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(9739))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(1971))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-5987))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-9645))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(1008))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-10995))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(4512))).
asteroidSensor(asteroidCloneClone,objectIndex(108),intPair(y(-1375))).
asteroidSensor(asteroidCloneClone,objectIndex(108),intPair(x(3382))).
asteroidSensor(asteroidCloneClone,objectIndex(109),intPair(y(-1411))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-814))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
