asteroidSensor(asteroidClone,objectIndex(8),intPair(y(3399))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(5266))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(5608))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(324))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(6354))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(1069))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-6573))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(8519))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(6061))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(4069))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(551))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(6066))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-7156))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-637))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(9943))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(10850))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(10537))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-5166))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(2058))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(5886))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(y(1589))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(x(6028))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-333))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
