asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(8569))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(1394))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-17766))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1147))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3416))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(6018))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2111))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-6007))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-1253))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4730))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-7779))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3532))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-1524))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-746))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(1788))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-1058))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(3835))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(2316))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(15383))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-3288))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(5006))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-1099))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-1906))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2740))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-1256))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(6135))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-8491))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(9042))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3925))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(6981))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-17))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(6306))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-100))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(5990))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(11156))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(4296))).
playerSensor(player,objectIndex(1),intPair(rotationZ(7))).
playerSensor(player,objectIndex(1),player(velocityY(-1223))).
playerSensor(player,objectIndex(1),player(velocityX(1382))).
playerSensor(player,objectIndex(1),intPair(y(-1355))).
playerSensor(player,objectIndex(1),intPair(x(175))).
