asteroidSensor(asteroidClone,objectIndex(18),intPair(y(3528))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(15338))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(37728))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-11931))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-4335))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(40851))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(5379))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-16736))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-420))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-18579))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-22051))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(14460))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-42731))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5348))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(24875))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-21758))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-10645))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(3033))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-9466))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-3656))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-10535))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(20769))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-25434))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-39305))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2118))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(13148))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-32911))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-869))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(3940))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-3781))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(31321))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-30))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-29867))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6748))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-7786))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-2760))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2019))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-7965))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(3501))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3949))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(7341))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-4077))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(3807))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-3349))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(32091))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11609))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(25338))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-10690))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-31743))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(8860))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-5971))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-16471))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(9065))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9384))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1340))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-8641))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(7558))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(-1772))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(-2790))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(5739))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(6999))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-2498))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(-74))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-2002))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-7590))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(7506))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-10394))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-1805))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(1125))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-11934))).
playerSensor(player,objectIndex(1),intPair(rotationZ(482))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
