asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(65484))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-28262))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(15632))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-22558))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-10732))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-38704))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-4264))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-16246))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-30563))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(31731))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-15907))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-5484))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(43503))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(40130))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-3501))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-18393))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-19206))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-11331))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-19190))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(41422))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(33200))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-29586))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-49102))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(16341))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-29100))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(503))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(4647))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(11230))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(15468))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-15178))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-16064))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-3608))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(13887))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-7576))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-11258))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(9818))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(6864))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(8264))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-22))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(7695))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(21957))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-38084))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-45236))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-68372))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(18727))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-13579))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-18878))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(33633))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(2651))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-3276))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-4159))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-15403))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-6623))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-4321))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-627))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(23506))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(9265))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-2491))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(284))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-6340))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-62))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(1253))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(2784))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(3276))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-12236))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-153))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(y(5553))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(x(6044))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-10644))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(5795))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-1696))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(1333))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(y(-400))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(x(-4775))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(2833))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(2605))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-3700))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(1713))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(5112))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(7102))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(y(-5927))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(x(8046))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-9548))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3800))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(4032))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(8679))).
asteroidSensor(asteroidCloneClone,objectIndex(125),intPair(y(2995))).
asteroidSensor(asteroidCloneClone,objectIndex(125),intPair(x(90))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(1807))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(417))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(11637))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(2392))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-119))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(-2511))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(-688))).
