asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-46183))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-71755))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-19818))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(5257))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-69038))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(23048))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-32133))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(9826))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(9944))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-37904))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-3810))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(25631))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(29543))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-17204))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(11628))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-38869))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(2005))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(5933))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-10841))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-2332))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-15742))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-37952))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(9032))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(30273))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(1282))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(4060))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-4153))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(8357))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(2547))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(3221))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-11848))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-15029))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-3978))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-7597))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-1384))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-6868))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(33694))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10335))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(18419))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(7253))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-11819))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-18867))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(66))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(7930))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-6063))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-5198))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-9779))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(1523))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-4221))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-3222))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-4411))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-135))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-2003))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(37545))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(10833))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(3540))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(10754))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-23664))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-23711))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-21956))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-348))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(673))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2743))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(11056))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(10634))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-6897))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-7516))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-7727))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(6882))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-4615))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(1644))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(y(-263))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(x(-4702))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-10888))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-1382))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(804))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(-79))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(1165))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(2436))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-1672))).
asteroidSensor(asteroidCloneClone,objectIndex(96),intPair(y(2763))).
asteroidSensor(asteroidCloneClone,objectIndex(96),intPair(x(-2045))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-7600))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(9073))).
playerSensor(player,objectIndex(1),intPair(rotationZ(271))).
playerSensor(player,objectIndex(1),player(velocityY(1411))).
playerSensor(player,objectIndex(1),player(velocityX(-1861))).
playerSensor(player,objectIndex(1),intPair(y(394))).
playerSensor(player,objectIndex(1),intPair(x(-4888))).
