asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1205))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(1234))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-1289))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(8650))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(3638))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(2050))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-5876))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-804))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(1665))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-18110))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3359))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(6147))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(15690))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-3169))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-1821))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(4878))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-522))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-1161))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4434))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-1449))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2702))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-8083))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3576))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-953))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(6064))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-8338))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(8568))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3865))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-1759))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(7326))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-177))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(6568))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-263))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(6250))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(10703))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(4091))).
playerSensor(player,objectIndex(1),intPair(rotationZ(102))).
playerSensor(player,objectIndex(1),player(velocityY(-1397))).
playerSensor(player,objectIndex(1),player(velocityX(2054))).
playerSensor(player,objectIndex(1),intPair(y(-1665))).
playerSensor(player,objectIndex(1),intPair(x(598))).
