asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(14313))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(35270))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(2479))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-14375))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(36236))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4649))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1246))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-8954))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-3307))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(22797))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-18137))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-9001))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-19425))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2717))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-7233))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(5552))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(13812))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-39985))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4886))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(18346))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-21642))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(57))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-16703))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9695))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-27676))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(7313))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-3118))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8436))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-2338))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(4767))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(29329))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10333))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(23245))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-10629))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-34335))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2567))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(10488))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-28675))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(4137))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4136))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-9796))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-6201))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-5607))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(694))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(419))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(2521))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(27666))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(274))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-27437))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6394))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-7027))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2292))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-5462))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-1611))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-14128))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(6379))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9280))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1301))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(9382))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(827))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(3570))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(4541))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-894))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-632))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-8391))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(8338))).
playerSensor(player,objectIndex(1),intPair(rotationZ(813))).
playerSensor(player,objectIndex(1),player(velocityY(2))).
playerSensor(player,objectIndex(1),player(velocityX(4))).
playerSensor(player,objectIndex(1),intPair(y(-3074))).
playerSensor(player,objectIndex(1),intPair(x(-5775))).
