asteroidSensor(asteroidClone,objectIndex(20),intPair(x(21477))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-6278))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(12577))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(31108))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-23323))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5795))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-5741))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(12715))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-35335))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4103))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-13526))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(24652))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-8175))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(209))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(1061))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-21503))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(703))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-1567))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(28423))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(14244))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-15221))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(866))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-12007))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-6218))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-14978))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(1317))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3900))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-5993))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8009))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-20790))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(1712))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(3414))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-10377))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(790))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(19700))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-8426))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(19280))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-25921))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3328))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(5984))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(4693))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(5122))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-191))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-1681))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-1069))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1038))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(1316))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-2867))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(8281))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(5215))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4451))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(10291))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-107))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-10162))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(1832))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9105))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1234))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-11753))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-992))).
playerSensor(player,objectIndex(1),player(velocityY(44))).
playerSensor(player,objectIndex(1),player(velocityX(89))).
playerSensor(player,objectIndex(1),intPair(y(-3116))).
playerSensor(player,objectIndex(1),intPair(x(-5860))).
