asteroidSensor(asteroidClone,objectIndex(9),intPair(y(2664))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(2532))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(574))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(7995))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(5110))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-329))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(1057))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(5721))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-15332))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(737))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(5237))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-581))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(5963))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(4202))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3817))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(13204))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-4128))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-4173))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-6937))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(5917))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-5189))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-1899))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(6823))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-5145))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(3010))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-5626))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3218))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-3404))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(6639))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-9576))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-847))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
