asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-71131))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(19634))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(44514))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(35627))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-31179))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-5741))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(46537))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(42889))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(17631))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-19719))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-14548))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-20873))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-31248))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-51930))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-17054))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(17223))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-17457))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-20231))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(36624))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(3917))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-3570))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-7671))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-6180))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-12158))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(68778))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-29797))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-23263))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-11363))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-40270))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(5006))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(12288))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(16806))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-16826))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-17410))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-1105))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(25854))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(15919))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-8931))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-5546))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(176))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-14164))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-408))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(7230))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-4461))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(4071))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-47249))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-4631))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-12578))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-20596))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(1195))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-32718))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-3106))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-4176))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-5662))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-18066))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(11347))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(7567))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(9602))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(10285))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-1271))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(160))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(y(5045))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(x(5407))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-12747))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(-343))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(y(-1073))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(x(-2500))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(2215))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-6648))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(2911))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(5674))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(10235))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(y(-5404))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(x(7373))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-8457))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3609))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(2226))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(6245))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(-1002))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(266))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(9216))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(1392))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(y(3527))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(x(2613))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(y(2120))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(x(3058))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(y(6937))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(x(8702))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-660))).
playerSensor(player,objectIndex(1),player(velocityY(728))).
playerSensor(player,objectIndex(1),player(velocityX(-2403))).
playerSensor(player,objectIndex(1),intPair(y(210))).
playerSensor(player,objectIndex(1),intPair(x(-3004))).
