asteroidSensor(asteroidClone,objectIndex(12),intPair(y(3027))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(10189))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(25382))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4971))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-2595))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(1714))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-4876))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(12963))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(8600))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-6386))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(1980))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(14823))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-5394))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(14441))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-4288))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(11205))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-28938))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-1739))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(826))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(17673))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1500))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-17663))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-9156))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(18218))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-5204))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-3572))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-2389))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-8860))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-3972))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-4135))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-1541))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(4844))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(5527))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-14345))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4375))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-213))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1096))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-3378))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-11636))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5690))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-11316))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(1089))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(8485))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-805))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(3430))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(4854))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(8358))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-687))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(587))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(-11083))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(10643))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-4595))).
playerSensor(player,objectIndex(1),intPair(rotationZ(995))).
playerSensor(player,objectIndex(1),player(velocityY(-746))).
playerSensor(player,objectIndex(1),player(velocityX(-2062))).
playerSensor(player,objectIndex(1),intPair(y(-3156))).
playerSensor(player,objectIndex(1),intPair(x(-5526))).
