asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-24101))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2213))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(9545))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(10064))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-3587))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(2636))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2037))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-13384))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4348))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-5852))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(13353))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-2958))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(505))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-4234))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-2999))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(189))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(8383))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(21053))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(429))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-717))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(6525))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(4332))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(293))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(2822))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(11135))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-3102))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(10782))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(2804))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-2634))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-7420))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-3509))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(7511))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(6757))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-5592))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(5166))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-4898))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(3113))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-5582))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-4175))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-3937))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-4152))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(-1635))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(11028))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-1269))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(7296))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(9334))).
playerSensor(player,objectIndex(1),intPair(rotationZ(827))).
playerSensor(player,objectIndex(1),player(velocityY(545))).
playerSensor(player,objectIndex(1),player(velocityX(-259))).
playerSensor(player,objectIndex(1),intPair(y(-1569))).
playerSensor(player,objectIndex(1),intPair(x(1809))).
