asteroidSensor(asteroidClone,objectIndex(5),intPair(x(1485))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(2292))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(7491))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(4096))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(6638))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(-3177))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(600))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(6103))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-7263))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(9352))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(6484))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(7694))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(4751))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-1854))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(5491))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-4722))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-1047))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(11344))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-999))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
