asteroidSensor(asteroidClone,objectIndex(9),intPair(x(2270))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3713))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(3322))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(6586))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(7398))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(312))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-301))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(6160))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(4166))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(6863))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(102))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4971))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(1781))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(3574))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-12805))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(6692))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(7474))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-4234))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(10942))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-5001))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-6313))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-7902))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-9436))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-2571))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-253))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
