asteroidSensor(asteroidClone,objectIndex(53),intPair(x(18407))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-58758))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(37636))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-23350))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(15826))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(54946))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(4174))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(-1151))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-3092))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-7339))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-23665))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(6452))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(18604))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-33768))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-38794))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-59542))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(31303))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(12213))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-22447))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-1711))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-14548))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(24059))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(497))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(43147))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-26079))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(24919))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(9520))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(25477))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-20305))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-8710))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-33691))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-13657))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(10539))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-10944))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-4664))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(33792))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-1400))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-2336))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-13872))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(3497))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(7845))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-3271))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(2058))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-3553))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(1629))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-3242))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-8380))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-6396))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(31816))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-14690))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(31526))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(25435))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-24269))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-40053))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-4766))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-14152))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-10480))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(11188))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-9906))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-11757))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-2332))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-6882))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(899))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(15990))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(7382))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(4926))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(4615))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(3982))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(6001))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(679))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-8881))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-827))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-5709))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(3032))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(3948))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(7836))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-6064))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(661))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(y(7181))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(x(8081))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-3913))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(1206))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(7152))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(6699))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-300))).
playerSensor(player,objectIndex(1),player(velocityY(-1585))).
playerSensor(player,objectIndex(1),player(velocityX(19))).
playerSensor(player,objectIndex(1),intPair(y(267))).
playerSensor(player,objectIndex(1),intPair(x(263))).
