asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-20942))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-41716))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(18692))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-4969))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-13729))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-21894))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(47368))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-34708))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-2741))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-8638))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(37867))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-32782))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-54540))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-17801))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-18653))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-4700))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-7049))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-20524))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-7897))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-643))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-14689))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-7450))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-18889))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-5978))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(49338))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(45435))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(18822))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-1545))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(28022))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(17796))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-10181))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(1644))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(5424))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3432))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-31214))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-23913))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-11947))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-33099))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(1834))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-12988))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(12758))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(8216))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(10837))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(11227))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(8554))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-7014))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(-1891))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(x(6752))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(560))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(3999))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(x(6598))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-22412))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(5338))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(13264))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(18041))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-18346))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-9369))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(4017))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(6192))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(13126))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(y(-4921))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(x(3056))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(y(-165))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(x(4523))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(y(4927))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(x(6387))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(y(-87))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(x(-11325))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-15442))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-21480))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(39386))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(5086))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-3841))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-4813))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(397))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-15945))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(-3596))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(126))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(6981))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(470))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(y(6206))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(y(4325))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(x(5636))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(y(4688))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(x(2))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(y(-832))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(x(1594))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(y(1059))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-991))).
playerSensor(player,objectIndex(1),player(velocityY(378))).
playerSensor(player,objectIndex(1),player(velocityX(-1099))).
playerSensor(player,objectIndex(1),intPair(y(1031))).
playerSensor(player,objectIndex(1),intPair(x(-5412))).
