asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-5697))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(4496))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(540))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(3988))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-4656))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(4203))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(2514))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-10246))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(9003))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(8652))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-8880))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(7462))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-118))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-18))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(3211))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(x(3066))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-8480))).
playerSensor(player,objectIndex(1),intPair(rotationZ(811))).
playerSensor(player,objectIndex(1),intPair(y(0))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(4909))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(6795))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(8165))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(8143))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(y(2040))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-5885))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(7821))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
