asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10797))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-48413))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(45687))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(14514))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(29230))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(16773))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(21925))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-21627))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(50184))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(3616))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-19440))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(8697))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(22650))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(5890))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(17089))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-31818))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-35964))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-12488))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(8238))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-8702))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-2712))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(2977))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-2563))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-5535))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-12656))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(27054))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-1911))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-11461))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-1756))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-54733))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(35318))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(40521))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-24366))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(22353))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-20548))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-5337))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-2369))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(-554))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(6315))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(9253))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(2716))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-4293))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(29404))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(27313))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(10347))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(1718))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-5559))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(4318))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(1589))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-8161))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(858))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(4473))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(-145))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-21130))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-19287))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-7797))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-31426))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-21866))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(12594))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(4442))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-1283))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-7080))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-8279))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(3836))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(x(9001))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-35883))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-55552))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-12235))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-9079))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-12592))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(19733))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-3232))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-7524))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-9810))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-3349))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(2152))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-3031))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(3598))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(2047))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(4526))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-10030))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-1173))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(9897))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-3275))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(1030))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(y(7916))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-999))).
playerSensor(player,objectIndex(1),player(velocityY(292))).
playerSensor(player,objectIndex(1),player(velocityX(125))).
playerSensor(player,objectIndex(1),intPair(y(389))).
playerSensor(player,objectIndex(1),intPair(x(157))).
