asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(10329))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(25718))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5019))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-2811))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(1814))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5198))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(13461))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1458))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-17995))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-9412))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(18594))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-5378))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-4066))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-2614))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-9218))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(5431))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-4388))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-12214))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(11294))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-29313))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(3090))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-1596))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(686))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(18302))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(8930))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-6903))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(1915))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(15108))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-5572))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(14724))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-4075))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-3881))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-1388))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(4637))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-15022))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4314))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(149))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1422))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-3207))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5826))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-11870))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(1300))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(8288))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-769))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(3131))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(4507))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(7969))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-586))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(579))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(-10900))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(10097))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-4494))).
playerSensor(player,objectIndex(1),intPair(rotationZ(990))).
playerSensor(player,objectIndex(1),player(velocityY(-588))).
playerSensor(player,objectIndex(1),player(velocityX(-1626))).
playerSensor(player,objectIndex(1),intPair(y(-3314))).
playerSensor(player,objectIndex(1),intPair(x(-5963))).
