asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-32560))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-14823))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-23127))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(14192))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(51999))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(47854))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(19953))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-34922))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(19214))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-19791))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(30082))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(50080))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(39995))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-34239))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-57019))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-18510))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(20088))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-19833))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-5198))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-8367))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-22860))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(19579))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-11368))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-11955))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(42010))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(6197))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-4099))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-23874))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(5653))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-9556))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-9527))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-1964))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(-3361))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(1102))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(6710))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(5068))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(6685))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(y(-2336))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-24530))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-12500))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-43089))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-5290))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-20249))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-6202))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-13776))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(14099))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(8832))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(12011))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(12121))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-4117))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(15873))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-6494))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3264))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(-1022))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(1866))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(-6059))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(x(5915))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(y(3017))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(x(4598))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(y(3057))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(x(6297))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(y(3890))).
asteroidSensor(asteroidCloneClone,objectIndex(138),intPair(y(-4328))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(2441))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-36598))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-2395))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-22105))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-16292))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-22667))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(607))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-17636))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-867))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-16533))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(9812))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-9439))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(-6))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(4858))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(-406))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(y(8751))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(x(3477))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(x(7573))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(y(1970))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(x(-622))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(y(-247))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(x(3664))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(y(1172))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(x(-10039))).
asteroidSensor(asteroidClone,objectIndex(136),intPair(y(-10635))).
asteroidSensor(asteroidClone,objectIndex(136),intPair(x(-1593))).
asteroidSensor(asteroidCloneClone,objectIndex(137),intPair(y(-4171))).
asteroidSensor(asteroidCloneClone,objectIndex(137),intPair(x(6372))).
asteroidSensor(asteroidCloneClone,objectIndex(138),intPair(x(6440))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-740))).
playerSensor(player,objectIndex(1),player(velocityY(122))).
playerSensor(player,objectIndex(1),player(velocityX(-355))).
playerSensor(player,objectIndex(1),intPair(y(1287))).
playerSensor(player,objectIndex(1),intPair(x(-6156))).
