asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-52716))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-3859))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-32073))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(51959))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-22467))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2608))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-40942))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-13248))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-13651))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-3005))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-13136))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-33320))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(24682))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-75052))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1114))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(32285))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-63380))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(28383))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10130))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(3734))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(13632))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(6921))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-30454))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(21342))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(1526))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(6880))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-7739))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-20780))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(40398))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-21292))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(39817))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-47801))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-13229))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(-539))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-14033))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-1829))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(4698))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(-245))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-4869))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(5208))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-389))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(2933))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-17850))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-60997))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(19989))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-26492))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(8361))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-31483))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(6605))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(21458))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(249))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(5923))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(79))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(757))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-7370))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-11297))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(4824))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2057))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-7903))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-38266))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(4466))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-7654))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-1074))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(5601))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(2500))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(7949))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-20054))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-18321))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-13144))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-2287))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-17763))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(631))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(5344))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-5432))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-5644))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(3250))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(-906))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(676))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(10648))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-8151))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-1302))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-8750))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-1746))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8785))).
playerSensor(player,objectIndex(1),intPair(rotationZ(925))).
playerSensor(player,objectIndex(1),player(velocityY(1095))).
playerSensor(player,objectIndex(1),player(velocityX(2075))).
playerSensor(player,objectIndex(1),intPair(y(-3202))).
playerSensor(player,objectIndex(1),intPair(x(-4827))).
