asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(15874))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-21889))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(17574))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(43091))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-27781))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(5817))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-6577))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(50919))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(6971))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-9443))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-6064))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-12862))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-14770))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(29407))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-29657))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-14231))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(495))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-9561))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(14924))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-48722))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(6356))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-13984))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-40616))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(12235))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-12195))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4649))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-18201))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-6532))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-21581))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9610))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(1500))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-125))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-33709))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1463))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-22672))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(38117))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-14390))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-50148))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(1137))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(18953))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-42153))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-741))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(1713))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(3577))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-11570))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(10472))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(900))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-9449))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-7659))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(-135))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-4662))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-12762))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(453))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(39296))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-695))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-35167))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7520))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(26055))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(29906))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(748))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(423))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(2113))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3542))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(4950))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(12363))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-5997))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-5842))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(5692))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-5155))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(840))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-10904))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(-884))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-2368))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(10643))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(10646))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(3841))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-440))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
