asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(13517))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(34153))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(2003))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-2840))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(34139))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(17245))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-19918))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-558))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4318))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-13302))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(26005))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(413))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(22293))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-10038))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(21853))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-16491))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(6609))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-1821))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1955))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-3642))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(4427))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4220))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-7302))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-38737))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4676))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-8236))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(13847))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(274))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-15850))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(28073))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9754))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3034))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-6900))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-32077))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2771))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-1948))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(6284))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9233))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1283))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-10321))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(10211))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(2008))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(3424))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-26333))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6234))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-8254))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-18231))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-6681))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(9279))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-26750))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9242))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-25827))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8934))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-1739))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-13063))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(5158))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-6302))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(5203))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(2278))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(2131))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(2584))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-166))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(3701))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-10))).
playerSensor(player,objectIndex(1),intPair(rotationZ(312))).
playerSensor(player,objectIndex(1),player(velocityY(5))).
playerSensor(player,objectIndex(1),player(velocityX(10))).
playerSensor(player,objectIndex(1),intPair(y(-3077))).
playerSensor(player,objectIndex(1),intPair(x(-5781))).
