asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1595))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(64552))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(9126))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-28866))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(50095))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-42345))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8566))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-1568))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-19087))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-35541))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-11686))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-10537))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(26813))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-54668))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2992))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-18158))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(36092))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-18615))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(35544))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-40354))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11724))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-64831))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-190))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-30031))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(2940))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-4338))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(233))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(1713))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-10425))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-28502))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(22859))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9916))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(19626))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-10735))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-3476))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(3236))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1418))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(5032))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-5187))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(33214))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-44915))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2876))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-28215))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(46278))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-15803))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-52632))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(16806))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-20624))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6838))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(8653))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(3776))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-1121))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-1812))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-22703))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(16881))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1940))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(2150))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(158))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-16298))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-12715))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-23799))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(4080))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(12287))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-824))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(7860))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(7139))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(1431))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-3823))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-5971))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(7275))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-3464))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-11183))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-528))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-13401))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1651))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(8818))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(4396))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-7066))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(3526))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-8531))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(-273))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(-11946))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-950))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
