asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-52285))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(51645))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-2925))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-3805))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-31860))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(8277))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-17737))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-60535))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(19813))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-26168))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-1002))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2629))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(5300))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-20636))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(40160))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-21144))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(39581))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-47389))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(-415))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-12986))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-33054))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(28078))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10118))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(2440))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(7788))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-19846))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-18011))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(5322))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-7503))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(5536))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-22281))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-40644))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-13162))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-13479))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(13357))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(6747))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-30025))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(21096))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(24403))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-31058))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(6466))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(20951))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(190))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(6030))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-13036))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-2190))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-17522))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(687))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-5889))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(5062))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2017))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(2466))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(10804))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-8009))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8846))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-13146))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-74488))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1063))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(31983))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-62899))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-37811))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(4381))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-7470))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-13851))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-1920))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(1620))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(6607))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(3647))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(4832))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(-153))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-4930))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-172))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-395))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(383))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-7115))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-10862))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-5308))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(2826))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(-1104))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(712))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-8321))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-983))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-8856))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-1414))).
playerSensor(player,objectIndex(1),intPair(rotationZ(782))).
playerSensor(player,objectIndex(1),player(velocityY(1335))).
playerSensor(player,objectIndex(1),player(velocityX(2530))).
playerSensor(player,objectIndex(1),intPair(y(-3442))).
playerSensor(player,objectIndex(1),intPair(x(-5281))).
