asteroidSensor(asteroidClone,objectIndex(60),intPair(y(21125))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(44314))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10744))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(27992))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(15992))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(47904))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(3348))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(25404))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(8303))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(21297))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(5621))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(16364))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-30884))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(336))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-4116))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(27303))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-5611))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-47215))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-20067))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-18799))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-7360))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-30342))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(9454))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-2383))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(2728))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-2309))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-4672))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-11682))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(24913))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(20245))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(17661))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-4108))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-1708))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-10307))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-8878))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-3836))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-6457))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-20953))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-34489))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-53642))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(13887))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-3217))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(-316))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-11317))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-8408))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-11655))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(2945))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-1187))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-1031))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(1556))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-6520))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(1657))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(3112))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(1121))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(3819))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-1339))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-9509))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(10884))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-52806))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(34209))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(39264))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-23546))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-20715))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-34006))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-11928))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(7136))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-7628))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(709))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-18000))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-3191))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-19056))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(5583))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(8327))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-6383))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(5605))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(1919))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(10968))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(3035))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-346))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-9006))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(943))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-10579))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(4221))).
asteroidSensor(asteroidCloneClone,objectIndex(108),intPair(y(-2041))).
asteroidSensor(asteroidCloneClone,objectIndex(108),intPair(x(2521))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(4725))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-941))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
