asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(31479))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-8877))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(61249))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(8604))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-27175))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-1068))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11200))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-18582))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(47478))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1377))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-40606))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8312))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(131))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(24908))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-51635))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-15090))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6307))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-27164))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(15328))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(34593))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-17683))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(34057))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-37762))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-17910))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-61273))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(2681))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-434))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-506))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-20006))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(3831))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(221))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-1198))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-42199))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2534))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-26872))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(44301))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-17245))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(2409))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-3184))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(689))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3125))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(2498))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(1598))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-1735))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1042))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(4016))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-14991))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(7989))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(2015))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-6548))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-4246))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-10501))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(83))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-8522))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(8165))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-33660))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-11143))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-9453))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-49720))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(15699))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-9482))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-26825))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(20937))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9842))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(6920))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(17866))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-9587))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-4050))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-10764))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-21125))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(3201))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(9095))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(8534))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6354))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(7995))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-1977))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-11883))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(2006))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(10027))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(6233))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-605))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
