asteroidSensor(asteroidClone,objectIndex(20),intPair(x(20979))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(560))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-1427))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(27794))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-22992))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5747))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(19414))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-6062))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(12437))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(30773))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(13913))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-14703))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(931))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-8248))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(18997))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(908))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(12626))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-34961))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4040))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(3315))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-10055))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(832))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-13271))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(24276))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-8001))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-11513))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-5994))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-14620))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-5637))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-45))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(1523))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3995))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-5893))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-25244))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3389))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(5621))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-20926))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7874))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-20235))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(4482))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(5319))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-227))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-1382))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-723))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(2101))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(937))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(1862))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-2968))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(8501))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(5301))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4477))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(10441))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(72))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-9843))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(1465))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9091))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1229))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-11910))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-885))).
playerSensor(player,objectIndex(1),player(velocityY(56))).
playerSensor(player,objectIndex(1),player(velocityX(113))).
playerSensor(player,objectIndex(1),intPair(y(-3128))).
playerSensor(player,objectIndex(1),intPair(x(-5884))).
