asteroidSensor(asteroidClone,objectIndex(79),intPair(y(18790))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(38017))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-32884))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-54714))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-17851))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(5164))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-3859))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-18448))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-41812))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-4991))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-13806))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-21981))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(47558))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-22515))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(5360))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(13329))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(18123))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-8011))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(5514))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-18984))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-5993))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(49525))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(45605))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(18901))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-1575))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(28167))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(17921))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-10264))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(4091))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(6227))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(-3768))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-18736))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-4735))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-7141))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-20688))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-8702))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(8642))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-7184))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(-1994))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(1606))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(13319))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(y(-4889))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(x(4621))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-31309))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-23956))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-11985))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-15502))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-21564))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(39570))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-4764))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(412))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-16063))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-659))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-14818))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-9551))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(117))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(6832))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(408))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(y(6384))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(y(4793))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(x(6458))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(y(56))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-33227))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(1877))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-34841))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-2717))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-21024))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-13043))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(12852))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(8259))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(10920))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(11290))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(x(6710))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-7383))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3420))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(449))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(3850))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(x(3086))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(y(-317))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(y(4236))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(x(5683))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(y(4632))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(x(6470))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(x(-41))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(y(-791))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(x(1739))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(y(1067))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(x(-11235))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-999))).
playerSensor(player,objectIndex(1),player(velocityY(349))).
playerSensor(player,objectIndex(1),player(velocityX(-1016))).
playerSensor(player,objectIndex(1),intPair(y(1060))).
playerSensor(player,objectIndex(1),intPair(x(-5496))).
