asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(41255))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-77085))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-23140))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-42016))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10172))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-21302))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-34279))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(29482))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-1501))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-21824))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(40667))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-49282))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(14622))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(7546))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(2715))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-8313))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-1335))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2532))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(-987))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-13675))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-20801))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-19436))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-33011))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(7107))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-4650))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-12863))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1298))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(33373))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-65113))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-18257))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-62660))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-31995))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(22230))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(25688))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-14689))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(4797))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-8589))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-13534))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-2637))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-5880))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-4762))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-7522))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-13559))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-14270))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-3290))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-13529))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(1186))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(7862))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(4049))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(6683))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(8530))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-18631))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(428))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(4653))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-1168))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(1792))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2199))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(4614))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(4778))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(-191))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-7540))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-2454))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-5814))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(20622))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-27659))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(8664))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-39904))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(4769))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(23281))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(463))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(5537))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(4212))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(-579))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(2101))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-8291))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(3965))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(550))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(10086))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-8366))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-2940))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8566))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(9954))).
playerSensor(player,objectIndex(1),intPair(rotationZ(993))).
playerSensor(player,objectIndex(1),player(velocityY(537))).
playerSensor(player,objectIndex(1),player(velocityX(1017))).
playerSensor(player,objectIndex(1),intPair(y(-2643))).
playerSensor(player,objectIndex(1),intPair(x(-3769))).
