asteroidSensor(asteroidClone,objectIndex(12),intPair(y(6524))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(16109))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-49720))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-805))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(52597))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(7236))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(30162))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-22747))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(40625))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(974))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-14559))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(17947))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(43985))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(6199))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-6951))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-30974))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-14829))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-28736))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-9719))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-42095))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(12798))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(11261))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-23354))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(39122))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-14854))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(30667))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-15243))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(19920))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-43693))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-13224))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9648))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(2380))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-185))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(1364))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(13257))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-6580))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(900))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-36051))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7649))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(26936))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-35088))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1637))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-13233))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4918))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-19657))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(1018))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-162))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(15901))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(2914))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-12940))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-6696))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(55))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(1356))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-11568))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(736))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-2178))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-5354))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-6614))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(241))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-9828))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-51955))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(1882))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3475))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(4552))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-7011))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-22433))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-5551))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(5390))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-4281))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(154))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(862))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-9035))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-5653))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-14120))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(10301))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(10214))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(3544))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-10113))).
playerSensor(player,objectIndex(1),intPair(rotationZ(59))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
