asteroidSensor(asteroidClone,objectIndex(79),intPair(y(19623))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-32111))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(49176))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-2510))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-21717))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(29395))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(39286))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-33753))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-56193))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-18274))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-16009))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-22271))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-4349))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-24324))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-12316))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-42632))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-5183))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-14459))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-22716))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(2239))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-35968))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-9250))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-8984))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-1824))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(18984))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-10973))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-8630))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-19795))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-6127))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(51112))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(47048))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(19576))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-34314))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-13513))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(13652))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(8627))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(11620))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(11823))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(14957))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-6813))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3320))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(-495))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(2577))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(-5238))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(y(-442))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(41135))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(5827))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-4013))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-23387))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(5548))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(13883))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(537))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-17072))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-793))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-15918))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(9392))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(37))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(5566))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(-114))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(y(7902))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(x(3337))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(y(-1613))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(x(7178))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(y(1284))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(x(-414))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(x(2974))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(y(1134))).
asteroidSensor(asteroidCloneClone,objectIndex(138),intPair(y(-4708))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(18823))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-19309))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-19440))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-5032))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-7928))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-22081))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(-2871))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(1283))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(6281))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-11093))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(4718))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(6521))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(x(5451))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(y(3653))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(x(5265))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(y(3480))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(x(6077))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(y(4156))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(x(-10468))).
asteroidSensor(asteroidClone,objectIndex(136),intPair(y(-11328))).
asteroidSensor(asteroidClone,objectIndex(136),intPair(x(-1513))).
asteroidSensor(asteroidCloneClone,objectIndex(137),intPair(y(-4464))).
asteroidSensor(asteroidCloneClone,objectIndex(137),intPair(x(6775))).
asteroidSensor(asteroidCloneClone,objectIndex(138),intPair(x(6763))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-904))).
playerSensor(player,objectIndex(1),player(velocityY(178))).
playerSensor(player,objectIndex(1),player(velocityX(-518))).
playerSensor(player,objectIndex(1),intPair(y(1231))).
playerSensor(player,objectIndex(1),intPair(x(-5994))).
