asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-40422))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4959))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(28247))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(35661))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(2646))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6451))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-9206))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(14476))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(226))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-27823))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-19843))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-3471))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(36970))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4765))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-14751))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(23128))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-18713))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-9263))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2606))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-7349))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-6099))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(13915))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(29768))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10536))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(23578))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-10836))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-7147))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1487))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9853))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-28323))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(7559))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-3572))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2410))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-1493))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(5295))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1307))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(18732))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-22245))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-18))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-17001))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-35126))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2495))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(10911))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-29349))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(4036))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4106))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8262))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-2548))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-14501))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(6806))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9297))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-9612))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-5816))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-5363))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(4614))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(9092))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(413))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(139))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-180))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(3915))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(4932))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-1150))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(2108))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-850))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-8263))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(8205))).
playerSensor(player,objectIndex(1),intPair(rotationZ(969))).
playerSensor(player,objectIndex(1),player(velocityY(1))).
playerSensor(player,objectIndex(1),player(velocityX(3))).
playerSensor(player,objectIndex(1),intPair(y(-3074))).
playerSensor(player,objectIndex(1),intPair(x(-5774))).
