asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-44946))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5721))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7034))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-11811))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(16165))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(39711))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(4375))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(27027))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-12981))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-8555))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(14983))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(34270))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-276))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-31827))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(26551))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-24679))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-11971))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-24170))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(10108))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-8272))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(11231))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-5164))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(44574))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(5968))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-18642))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(34319))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-12637))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-8399))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-3982))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1455))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-11493))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-35024))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(2988))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3799))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(6457))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-4720))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-18361))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9468))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-1827))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-6944))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(22724))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-28494))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-806))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-20092))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-43315))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(1755))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(15295))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-36329))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(3630))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-12696))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-271))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(2639))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-2844))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(3033))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(6086))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-6389))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(7490))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(8983))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-3792))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(6835))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-8457))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-1184))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(1042))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-11015))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-11297))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(-858))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-1109))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-8393))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(-986))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(-7282))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-380))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
