asteroidSensor(asteroidClone,objectIndex(7),intPair(y(5330))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(1101))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-6969))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(5702))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-6626))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(8583))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(6187))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(366))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(10051))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-5197))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(1734))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(6441))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(3452))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(5675))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(4121))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(6021))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-669))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(344))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(10962))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(10682))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-441))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
