asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-20856))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-11480))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-40559))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-4698))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-12808))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-52452))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-17204))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-19964))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(45085))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(36075))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-31554))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-14727))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-20481))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(37177))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(4151))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(12483))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(17053))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(16295))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-30080))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-23393))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(17869))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-31563))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(1323))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-33116))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-3033))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-3624))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-21181))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(5073))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-7864))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-6524))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-1193))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(26288))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(10473))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-1045))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(137))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-5399))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(220))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(-653))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(y(-1197))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(x(-2080))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(2101))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(4341))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(5796))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(17517))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-17744))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-5788))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(47097))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(43398))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-17130))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-17659))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-4280))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-5939))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-18558))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-9181))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-12324))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(11629))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(7697))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(9849))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-14521))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-455))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-13135))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(7495))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-4971))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-7192))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(3133))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(5777))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(10813))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(y(-5308))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(x(7249))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-8256))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3573))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(1893))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(-1521))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(238))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(8769))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(1208))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(y(4063))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(x(2701))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(y(1663))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(x(3351))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(y(6535))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(x(8282))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-780))).
playerSensor(player,objectIndex(1),player(velocityY(978))).
playerSensor(player,objectIndex(1),player(velocityX(-2845))).
playerSensor(player,objectIndex(1),intPair(y(430))).
playerSensor(player,objectIndex(1),intPair(x(-3667))).
