asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-41778))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-14133))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-3227))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-13462))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-76634))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-39540))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(4702))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(7407))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1257))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(33131))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-64728))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-18167))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-62291))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-34066))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(29238))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10163))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(14402))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(3979))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(6443))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(2668))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-21706))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(40478))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-48953))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-22990))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(20481))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-27400))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(8597))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-31653))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(22033))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(25464))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-14544))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-1574))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(8401))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-20635))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-19188))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-32672))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(6996))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-4699))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(4888))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-8400))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-13447))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-2559))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-8086))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-12515))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-5781))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-4958))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(4438))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(-350))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-2198))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-21186))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(41064))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-13490))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-8166))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-1277))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2549))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(-888))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-13555))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(1261))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(7644))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(22876))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(415))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(5623))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(4320))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(-505))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-18438))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(473))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(4807))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-995))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(1411))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(1802))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(4156))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2167))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(4240))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(578))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(10211))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-7607))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-7676))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-8452))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-2674))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8615))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(10132))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-5883))).
playerSensor(player,objectIndex(1),intPair(rotationZ(997))).
playerSensor(player,objectIndex(1),player(velocityY(629))).
playerSensor(player,objectIndex(1),player(velocityX(1192))).
playerSensor(player,objectIndex(1),intPair(y(-2735))).
playerSensor(player,objectIndex(1),intPair(x(-3943))).
