asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(15862))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-17944))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(38985))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(4065))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-12596))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(14791))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-44135))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5584))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-4860))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(43210))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(5752))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(25937))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-23609))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-11485))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-23394))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(14509))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-35077))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-4330))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(33190))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-186))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-31109))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6929))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(33503))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-12261))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(26409))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-11199))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-33822))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(9651))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-7430))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(3176))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3854))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(6780))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-8050))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-2543))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-3296))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(3316))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(6849))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(8256))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-9166))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-11344))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(22008))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-27374))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-665))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-19538))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-8174))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-3534))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1661))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-8339))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-41846))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(1888))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(3411))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-11513))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-490))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(3116))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-17668))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(10438))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9437))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1360))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(6625))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-5275))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-3318))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-7180))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(7081))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-1412))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(1073))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-11351))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-222))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
