asteroidSensor(asteroidClone,objectIndex(2),intPair(y(6189))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(-5323))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(5129))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-2929))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(3726))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(9042))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(10190))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(2473))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(-8379))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(5701))).
playerSensor(player,objectIndex(1),intPair(rotationZ(68))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
