asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-43836))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(36819))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-20096))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-37152))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-12152))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-11466))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-1997))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-156))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-30315))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(52337))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1782))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-12173))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-67880))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-466))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(28446))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2877))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-2932))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(47973))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-18940))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(37377))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-19414))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(1041))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-11234))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-29940))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(24507))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(4714))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-1710))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1741))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8783))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(34701))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-47242))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-3169))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-29366))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-42576))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(7292))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-32488))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(3395))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-5327))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-25015))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(18212))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(21134))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-11719))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-2985))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(5902))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-17419))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-14388))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-26092))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(4834))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-5642))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(6659))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-4740))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-11768))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-1053))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(-3984))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-57267))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-16414))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-55127))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(17756))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-22375))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9980))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(10138))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(2726))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(3414))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(2623))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(1782))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(15023))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-504))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(7282))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(6410))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(931))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-14703))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1347))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(7781))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(2822))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-5817))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(2358))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-5962))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(-390))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(-11044))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-4124))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-5772))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-3852))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-8753))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(7854))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-576))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
