asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4539))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(13326))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-37925))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-12604))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(13544))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(33427))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(24925))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-7769))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4102))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(27257))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9377))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-17455))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(1693))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-2536))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(32776))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(503))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-25615))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6129))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-15296))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-15421))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-7768))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-6457))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1968))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(2114))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-25499))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8948))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-24625))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(3760))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(56))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-1350))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(16529))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-18798))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(415))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(21674))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-9653))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(21239))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-110))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3241))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-6684))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-30608))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2904))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(8493))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(6152))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-978))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1736))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-2459))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-2167))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(6761))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(4615))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4275))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(9258))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-12371))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(4365))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9203))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1271))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-10663))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-8017))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-6753))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-251))).
playerSensor(player,objectIndex(1),player(velocityY(8))).
playerSensor(player,objectIndex(1),player(velocityX(17))).
playerSensor(player,objectIndex(1),intPair(y(-3081))).
playerSensor(player,objectIndex(1),intPair(x(-5788))).
