asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-21164))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(15675))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-601))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-34422))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7412))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(25312))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-28546))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-13727))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-48623))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(5495))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-6262))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(49503))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(6747))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(38174))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(29264))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-14371))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(28770))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(1275))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(18137))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-40853))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-12557))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4422))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-16973))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(5286))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-47879))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(6214))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-13499))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(17260))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(42337))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-32545))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1317))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-22096))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(37270))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13999))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-26975))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-9210))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-5599))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(709))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-9337))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-39368))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(11761))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-11320))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(521))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(918))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(2308))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3600))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-6127))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-20863))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(14100))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9578))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(757))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-1210))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(2008))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(4137))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-10414))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(9807))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(11608))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-5505))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-6088))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(5947))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-5891))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-361))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(931))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-9799))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-8471))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(-296))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(405))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-10343))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-3826))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-11615))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(77))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(-2252))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-2528))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(10932))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(11010))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(4091))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-803))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
