asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3553))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(3204))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(1682))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(3451))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-13148))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(6494))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-4178))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(11249))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-6023))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(8701))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(44))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4874))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(6469))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(2040))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(7479))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(370))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-339))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(7268))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(5894))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(4294))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-4883))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-7771))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(6735))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-8860))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-2480))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-8053))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-419))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
