asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(22478))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-2979))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(2040))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-447))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(8643))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1860))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-14792))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(12349))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-3856))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(6352))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(10439))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-25693))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4553))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(5736))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-1904))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-3697))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-3074))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-6339))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-4856))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2481))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-727))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(8977))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(2545))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-6939))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(14954))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-5756))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-2861))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(6633))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-6630))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-4514))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-6509))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(10191))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-1117))).
playerSensor(player,objectIndex(1),player(velocityY(198))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(12220))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(852))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-2085))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(11986))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(705))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-3423))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-8472))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4906))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-3357))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(1728))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(-739))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(6024))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(7860))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(11730))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-1563))).
playerSensor(player,objectIndex(1),intPair(rotationZ(930))).
playerSensor(player,objectIndex(1),player(velocityX(-2378))).
playerSensor(player,objectIndex(1),intPair(y(-1222))).
playerSensor(player,objectIndex(1),intPair(x(329))).
