asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2959))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-2361))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-4527))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(10037))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(25019))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-1894))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(12423))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1545))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-3860))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-17304))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4919))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(8242))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-2147))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-8472))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-13611))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-28533))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-5826))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(2050))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-8879))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-5202))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(14134))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-3038))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(5630))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-4180))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-3563))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-11010))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5543))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(860))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(8698))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(595))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(11110))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(978))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(16992))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(1607))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(17810))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-5016))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(14514))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-4410))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-1706))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(5067))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4441))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-606))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-743))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-10715))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-844))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(3754))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(5230))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(8779))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-797))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(-11281))).
playerSensor(player,objectIndex(1),intPair(rotationZ(998))).
playerSensor(player,objectIndex(1),player(velocityY(-965))).
playerSensor(player,objectIndex(1),player(velocityX(-2668))).
playerSensor(player,objectIndex(1),intPair(y(-2937))).
playerSensor(player,objectIndex(1),intPair(x(-4921))).
