asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10792))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-48280))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(45535))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(14445))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-21552))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(3586))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(-92))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-21012))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-19233))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(26816))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(27101))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(29092))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(16687))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-54518))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(35195))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(40382))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(21739))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-21738))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-35746))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-12425))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-20382))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-5368))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(2949))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-7748))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-31306))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-2534))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-5439))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-12548))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(10248))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-19280))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-2765))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(9150))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-7397))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-9707))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-3403))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(1700))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-5666))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(4447))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-24275))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(22217))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(8654))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(22500))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(5860))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(49931))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-2463))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(-527))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-12133))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-9004))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-12488))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(2241))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-2826))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-1675))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-7011))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(2598))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(3544))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(1944))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-1192))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-8416))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(1050))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(17009))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-31714))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-35728))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-55340))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(8115))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-8583))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-4274))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(29171))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(19503))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-3329))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-1889))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-11333))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(6234))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(4461))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(1626))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(12413))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(4286))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-1179))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-8255))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(867))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-10091))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(3879))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(4501))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(10007))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-3127))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-999))).
playerSensor(player,objectIndex(1),player(velocityY(323))).
playerSensor(player,objectIndex(1),player(velocityX(138))).
playerSensor(player,objectIndex(1),intPair(y(359))).
playerSensor(player,objectIndex(1),intPair(x(144))).
