asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-31497))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(11809))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(16369))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(3457))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-4068))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(11144))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1216))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-19927))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-6607))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(21973))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(2394))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-7076))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(1534))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-10904))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(20792))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-6392))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(16774))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-11307))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-4679))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-2397))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-4970))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-18975))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3956))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6618))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-15105))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(5699))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(27673))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-762))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-131))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5301))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(10857))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-9920))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(16377))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-6946))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-3921))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-500))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(3433))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(4876))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(2265))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3324))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-2212))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-15583))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(2530))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(7140))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-560))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(1385))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(2484))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(533))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(-9832))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(6913))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-3904))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(396))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-10791))).
playerSensor(player,objectIndex(1),intPair(rotationZ(625))).
playerSensor(player,objectIndex(1),player(velocityY(508))).
playerSensor(player,objectIndex(1),player(velocityX(1019))).
playerSensor(player,objectIndex(1),intPair(y(-3581))).
playerSensor(player,objectIndex(1),intPair(x(-6790))).
