asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2740))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-41655))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8465))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(32525))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-43837))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-27682))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-62))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(45493))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-17796))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(35497))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-18245))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-51476))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(16367))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(7965))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(8618))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-9321))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-10107))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-1370))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11516))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-63419))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6627))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-28893))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(2729))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-3880))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(3341))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-848))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-10279))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(63241))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(8919))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-28195))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(49056))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1508))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(26057))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-53464))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-15520))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-19814))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-1294))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-21633))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(16265))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(18927))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1269))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(4629))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-15780))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-11941))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-22738))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(7561))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(34954))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-39325))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-18620))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-34794))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-11471))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(414))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3045))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(2025))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-10051))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-27837))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(22096))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9887))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-3704))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(3472))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1258))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(1931))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-592))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(3732))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(11021))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-973))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(8128))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(7476))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(1663))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-5727))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-3991))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6123))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-2874))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-10912))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-285))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-12799))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1792))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(9297))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(5125))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-7644))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(4067))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-9720))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-983))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
