asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-43000))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-35991))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(10828))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-51597))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(14411))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(4252))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-27396))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(12672))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-26133))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(14019))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(37325))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10475))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(21692))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(12012))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-14861))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-24044))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-9078))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(1529))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-5630))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-11462))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-3582))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-24824))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-1019))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-277))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-6728))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(11696))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-7003))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(4233))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-579))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(28564))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(32867))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-19373))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(14876))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(6299))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-3086))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(1861))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-14659))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-16318))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-5134))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(-350))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(6071))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-4805))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-3177))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-10675))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-7535))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(894))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-6648))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-4995))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-6888))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(1857))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(3614))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-4136))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-6313))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-11407))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(6936))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-13020))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-3193))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-17524))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-41120))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-43921))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(10692))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(36302))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(1989))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(2787))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-2165))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-3212))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(16612))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(15685))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(4909))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(7121))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-8570))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-673))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-4434))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(1462))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(6978))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(8193))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(2659))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(728))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-912))).
playerSensor(player,objectIndex(1),player(velocityY(-1718))).
playerSensor(player,objectIndex(1),player(velocityX(2670))).
playerSensor(player,objectIndex(1),intPair(y(4029))).
playerSensor(player,objectIndex(1),intPair(x(-5632))).
