asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-31476))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(51080))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(8125))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-13169))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-2782))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10097))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-73471))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-971))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(31438))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-62032))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-32575))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(27529))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(3489))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-51509))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-3707))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(4230))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-7141))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-872))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2668))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(1790))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(6115))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(20039))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-17533))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-59703))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(19496))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-25585))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-36992))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-13523))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-2084))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(83))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(6222))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-10079))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-21945))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-40106))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-13006))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-12996))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(-191))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-12716))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(13))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-5040))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(5528))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-7078))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(-288))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-6655))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(5492))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(12862))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(6434))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-29255))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(20652))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(23900))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-30294))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(6215))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(5075))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(216))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-1252))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-5084))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-6329))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-1946))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(1626))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8955))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-20375))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(39732))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-20878))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(39156))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-46649))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(4759))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(2333))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(7498))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-19473))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-17454))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-12841))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-2015))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-17088))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(789))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(5882))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(2062))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(-1462))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(775))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(11085))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-8199))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-8627))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-407))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-9048))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-817))).
playerSensor(player,objectIndex(1),intPair(rotationZ(479))).
playerSensor(player,objectIndex(1),player(velocityY(597))).
playerSensor(player,objectIndex(1),player(velocityX(1775))).
playerSensor(player,objectIndex(1),intPair(y(-3867))).
playerSensor(player,objectIndex(1),intPair(x(-6152))).
