asteroidSensor(asteroidClone,objectIndex(9),intPair(y(496))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(7300))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-3467))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(9416))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(4668))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-2850))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3974))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(3722))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(1771))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(5425))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-1611))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-21355))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1725))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-341))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(1778))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-10816))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3327))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-3869))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(10434))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(2242))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-1459))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-2225))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(1859))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-343))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(2662))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2359))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-6962))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(4301))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(8587))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(6630))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-4689))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(9111))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-340))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(-2440))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(18455))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-4696))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(8923))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-1727))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-1832))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-9390))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(7495))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(781))).
playerSensor(player,objectIndex(1),intPair(rotationZ(547))).
playerSensor(player,objectIndex(1),player(velocityY(-178))).
playerSensor(player,objectIndex(1),player(velocityX(261))).
playerSensor(player,objectIndex(1),intPair(y(-2884))).
playerSensor(player,objectIndex(1),intPair(x(2390))).
