asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-58311))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-25550))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(24127))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(9266))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(24605))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(53477))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(4001))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-6783))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(42337))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(-841))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-22665))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(32439))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(31018))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(17903))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-57516))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(36921))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-19991))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-8429))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-32993))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-2929))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(11637))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-21519))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-2020))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-22704))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(3337))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(7373))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(1008))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-14062))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(30147))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(24352))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-23527))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-38792))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-4942))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-13561))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-10047))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-13945))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(22724))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(10591))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-9171))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-11156))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-2646))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(14942))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(6475))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-2638))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-7979))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(5546))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-6941))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(3280))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(6278))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(18137))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-33167))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-37896))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(15421))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-13297))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(9829))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-10253))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-4550))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(30072))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-1965))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-2205))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-13128))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-5694))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-2803))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(1953))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-4172))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(2458))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(1112))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(4244))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(4301))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(3385))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(734))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-9235))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-934))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-6502))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(4110))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(8472))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-5204))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(775))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(y(7408))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(x(8365))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-2975))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(566))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(8386))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(7447))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-635))).
playerSensor(player,objectIndex(1),player(velocityY(80))).
playerSensor(player,objectIndex(1),player(velocityX(34))).
playerSensor(player,objectIndex(1),intPair(y(601))).
playerSensor(player,objectIndex(1),intPair(x(248))).
