asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(8974))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(2847))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(986))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-5351))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-2210))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3133))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(6659))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-658))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-797))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3254))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-9298))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3753))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-7726))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(6671))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(8707))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-814))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(8893))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(1170))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-19483))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1436))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(16919))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-2695))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(4364))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(1784))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(378))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2549))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(257))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(5780))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3626))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-2697))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(7614))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-913))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(7289))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(3269))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(181))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-1357))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-10556))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-5388))).
playerSensor(player,objectIndex(1),intPair(rotationZ(355))).
playerSensor(player,objectIndex(1),player(velocityY(-584))).
playerSensor(player,objectIndex(1),player(velocityX(859))).
playerSensor(player,objectIndex(1),intPair(y(-2478))).
playerSensor(player,objectIndex(1),intPair(x(1793))).
