asteroidSensor(asteroidClone,objectIndex(9),intPair(x(1873))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3436))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(3118))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(1611))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(3361))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(7538))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(6350))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(7119))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(4388))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-4796))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-8440))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(1))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4803))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(6383))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-13398))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(412))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-367))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(5701))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-4136))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(11473))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-5811))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-7676))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(6641))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-2413))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(8486))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-7720))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-472))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
