asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-16012))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(14261))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(5155))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(30200))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(63))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-20647))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-41888))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5206))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-10050))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(15023))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-274))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-18003))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(31244))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11217))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-10141))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-21245))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-7553))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-2295))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(8385))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-5095))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2805))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-8237))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(3696))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4006))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-4523))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(36974))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(3206))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-4020))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(39435))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-29121))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6640))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(20026))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-24271))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(24696))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-11532))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(24237))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2233))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-7740))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-37780))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2255))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(12332))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-31612))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-10385))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-30495))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-1097))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(4434))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(7677))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-3252))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-15752))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(8241))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9352))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1328))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-8995))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-4547))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(4102))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(8117))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(-974))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(-1721))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-2192))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(5074))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(6245))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-2006))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(721))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-1582))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-7836))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(7761))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-11131))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-2042))).
playerSensor(player,objectIndex(1),intPair(rotationZ(831))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(1))).
playerSensor(player,objectIndex(1),intPair(y(-3073))).
playerSensor(player,objectIndex(1),intPair(x(-5772))).
