asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(14313))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(39802))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(37169))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(3290))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-4101))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-312))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-18152))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(31463))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11319))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-31948))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-42107))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5243))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-10176))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(15105))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-10271))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-21454))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-7613))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-2416))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(12544))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-10464))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-30818))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3991))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(5213))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-16200))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(30490))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(39))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2177))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-7798))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-38176))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2220))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-1038))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(4306))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(3646))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9361))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1331))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-8903))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-4331))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(7972))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(-1181))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(6440))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-29314))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6668))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(20218))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-24573))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(24862))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-11635))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(24403))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-20935))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(8508))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-5322))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2864))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-8556))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(7590))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-3357))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-15938))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(8454))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-4425))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(4025))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(-1998))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-2492))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(5246))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-2134))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(515))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-1691))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-7772))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(7695))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-10940))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-1981))).
playerSensor(player,objectIndex(1),intPair(rotationZ(711))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(1))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5772))).
