asteroidSensor(asteroidClone,objectIndex(12),intPair(y(3153))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(11382))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-29687))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(1913))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5520))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(13960))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-18326))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5068))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(15008))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-1453))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(545))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(18932))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1417))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-9668))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(18971))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-5552))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(15394))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-5749))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-4179))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-3626))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-1236))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-15700))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4252))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(512))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-3037))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-12791))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(2832))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-3026))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(10468))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(26053))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(9260))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-7420))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(1849))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-4560))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-2838))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-9576))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(4431))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(5336))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-4488))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1748))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5962))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-12425))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(1511))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(8091))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-733))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(4161))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(7580))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-485))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(571))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(-10717))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(9551))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-4393))).
playerSensor(player,objectIndex(1),intPair(rotationZ(963))).
playerSensor(player,objectIndex(1),player(velocityY(-463))).
playerSensor(player,objectIndex(1),player(velocityX(-1282))).
playerSensor(player,objectIndex(1),intPair(y(-3439))).
playerSensor(player,objectIndex(1),intPair(x(-6307))).
