asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(9040))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(2686))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(768))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(2256))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3087))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(6764))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3789))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-2399))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-722))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3012))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(8990))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(17171))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-2598))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(505))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(5722))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-944))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-420))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-5244))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(4259))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-9546))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3577))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-2889))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(7501))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(8522))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-10365))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(1069))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-19764))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1483))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(752))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2518))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-7601))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(6284))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(7828))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-1047))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(3101))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-86))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-1435))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-5273))).
playerSensor(player,objectIndex(1),intPair(rotationZ(383))).
playerSensor(player,objectIndex(1),player(velocityY(-489))).
playerSensor(player,objectIndex(1),player(velocityX(719))).
playerSensor(player,objectIndex(1),intPair(y(-2573))).
playerSensor(player,objectIndex(1),intPair(x(1933))).
