asteroidSensor(asteroidClone,objectIndex(8),intPair(x(6330))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-25))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-384))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(1566))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(7575))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(11612))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4759))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(1768))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(6260))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(5580))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(4446))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(6583))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3363))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(3305))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-13554))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(7026))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-4743))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-7616))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-2372))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(3065))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(438))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-4111))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-5679))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-8178))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(8352))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-7513))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-525))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
