asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(13576))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(34558))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(2098))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-2933))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(22042))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-38986))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4718))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-8379))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(13940))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(17465))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-20263))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-16820))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(230))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-16020))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(28325))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9870))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2971))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-6966))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-32528))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2730))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2022))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-4006))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(5402))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4384))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-13516))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(26337))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(385))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(22483))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-10156))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(9521))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-27135))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9333))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-26197))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-1881))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(6138))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(4369))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4203))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9243))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1286))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-10216))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-7082))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(1961))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(1789))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(2782))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(3647))).
playerSensor(player,objectIndex(1),intPair(rotationZ(476))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(34376))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-26553))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6266))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-8404))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-18470))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-6750))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-695))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(6750))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-2080))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8835))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-1859))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-13276))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-6163))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(5116))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(10046))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(1772))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-311))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(3465))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-134))).
playerSensor(player,objectIndex(1),player(velocityY(4))).
playerSensor(player,objectIndex(1),player(velocityX(8))).
playerSensor(player,objectIndex(1),intPair(y(-3076))).
playerSensor(player,objectIndex(1),intPair(x(-5779))).
