asteroidSensor(asteroidClone,objectIndex(20),intPair(x(14250))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(1971))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5708))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-5653))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-3152))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(10550))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(26248))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-9817))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(19191))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-5853))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(15173))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-4546))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(11434))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-29906))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(3190))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(9453))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-7722))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(1811))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(15560))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-4239))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-3478))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-1147))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4216))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(724))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(1634))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-1370))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(464))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(19299))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1393))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-18519))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5096))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-4848))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-2968))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-9785))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(4310))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(5281))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-16095))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1939))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-2937))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-13128))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6041))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-12748))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(7976))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-712))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(2657))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(3958))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(7353))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-426))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(566))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(-10610))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(9233))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-4334))).
playerSensor(player,objectIndex(1),intPair(rotationZ(923))).
playerSensor(player,objectIndex(1),player(velocityY(-403))).
playerSensor(player,objectIndex(1),player(velocityX(-1116))).
playerSensor(player,objectIndex(1),intPair(y(-3499))).
playerSensor(player,objectIndex(1),intPair(x(-6473))).
