asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-48006))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-20853))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(40517))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-21366))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(39935))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(32436))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-63621))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-7745))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-13271))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-75335))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1140))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-1110))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2598))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(3778))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-22561))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-41091))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-13291))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-13737))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-3044))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-38493))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(4508))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-14124))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-1783))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(1478))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(7016))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-20158))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-18476))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(5869))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-17907))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-61228))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(20077))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-26654))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(8403))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(13769))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(7008))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-30668))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(21466))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(24822))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(5751))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(2530))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(8030))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(4630))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(-292))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-4839))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(5151))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-7857))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-497))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(317))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(944))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-7498))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-11515))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(3167))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-52931))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-3886))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-32180))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(52116))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(-601))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-13211))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-33453))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(28536))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10136))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-31695))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(6675))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(21711))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(279))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-13198))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-2336))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-17883))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(603))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(5248))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-5494))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-5521))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(4705))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2077))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(3462))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(-807))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(659))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(10570))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-7850))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-8066))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-1462))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-8697))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-1912))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8755))).
playerSensor(player,objectIndex(1),intPair(rotationZ(930))).
playerSensor(player,objectIndex(1),player(velocityY(992))).
playerSensor(player,objectIndex(1),player(velocityX(1879))).
playerSensor(player,objectIndex(1),intPair(y(-3098))).
playerSensor(player,objectIndex(1),intPair(x(-4631))).
