asteroidSensor(asteroidClone,objectIndex(4),intPair(y(2525))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(7027))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(7929))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(1645))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(-4021))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(1427))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(6425))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-7528))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(4364))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(9673))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(6821))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(8323))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(5013))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-2779))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(5270))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-3786))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-1205))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(11883))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-652))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
