asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(9571))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6032))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(1392))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-972))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(3418))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(3181))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-22011))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1861))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-125))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(1080))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(2487))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-2111))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-2716))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(7603))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(3742))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2269))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(11250))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-1988))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(9201))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(5560))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-2056))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-8839))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(4933))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(19182))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-4386))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-11534))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4078))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3186))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-4424))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(9541))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(1756))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-2235))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-4359))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(8663))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(7289))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-2442))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-1808))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(5509))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-6924))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6534))).
playerSensor(player,objectIndex(1),intPair(rotationZ(625))).
playerSensor(player,objectIndex(1),player(velocityY(580))).
playerSensor(player,objectIndex(1),player(velocityX(-239))).
playerSensor(player,objectIndex(1),intPair(y(-2678))).
playerSensor(player,objectIndex(1),intPair(x(2327))).
