asteroidSensor(asteroidClone,objectIndex(18),intPair(x(2122))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(11853))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(2583))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(10388))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-25474))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2444))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(794))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-1897))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(8352))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(5543))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-1602))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(12182))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-3753))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(11821))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-3014))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-6487))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-2950))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(6408))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-3365))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(-862))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-601))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(8896))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(22282))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-3063))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1884))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-14599))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4525))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-6790))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(14734))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-3596))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(993))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-316))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-5548))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(6754))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-8076))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4942))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-3568))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(1918))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-4956))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-6293))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-4435))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-6186))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(10306))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-1137))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(6198))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(8062))).
playerSensor(player,objectIndex(1),intPair(rotationZ(918))).
playerSensor(player,objectIndex(1),player(velocityY(228))).
playerSensor(player,objectIndex(1),player(velocityX(-2732))).
playerSensor(player,objectIndex(1),intPair(y(-1252))).
playerSensor(player,objectIndex(1),intPair(x(682))).
