asteroidSensor(asteroidClone,objectIndex(44),intPair(x(10642))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-50596))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-42058))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-35278))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(14275))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(6106))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-14139))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(4120))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(12318))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-25677))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-26715))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-16080))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-4920))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(-273))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(6750))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-12617))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-3034))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-17194))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-40534))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-42987))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(10385))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(35188))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(1858))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(3022))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-24293))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-895))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(144))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-6252))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(12972))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(6415))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-5037))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-3551))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-9971))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(4723))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-3773))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-6430))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(28022))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(32252))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-18972))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-1640))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-3126))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(15585))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(14751))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(4472))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-7950))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(1011))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-6199))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-4667))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(1341))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(36654))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10449))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(21087))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(11630))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(13749))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-3220))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(2113))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(10874))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-14299))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-23087))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-8804))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(990))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-5864))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-10732))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-7137))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(6109))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-8999))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-573))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-3870))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(1499))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(3162))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-21))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-3680))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-6551))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(7365))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(9095))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(3014))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(648))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-11876))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-984))).
playerSensor(player,objectIndex(1),player(velocityY(-599))).
playerSensor(player,objectIndex(1),player(velocityX(1407))).
playerSensor(player,objectIndex(1),intPair(y(4590))).
playerSensor(player,objectIndex(1),intPair(x(-6600))).
