asteroidSensor(asteroidClone,objectIndex(53),intPair(y(29670))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(17051))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(3711))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-36378))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-56231))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(14738))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(50994))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-36660))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-12687))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(8629))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-9084))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(10664))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-19951))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-2920))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-55418))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(35713))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(40968))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-24657))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(22790))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(-316))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-21508))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-19460))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-7952))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-31812))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-22275))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-4356))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(30151))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(27992))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-12561))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-9317))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-12925))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(20469))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-10142))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-3176))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(1871))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-3687))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(3860))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(1472))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(3092))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(8837))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(23131))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(5985))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(17347))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-32150))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-2653))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-5842))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-13002))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(27815))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(22523))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-2542))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-21079))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-5240))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-2067))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(-639))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-1984))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-11871))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(3066))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(6576))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(9582))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-7929))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-2014))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(1776))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-5218))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(13172))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(4942))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-1617))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-7301))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(3771))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(2377))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(4777))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-7861))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(827))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-9834))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-1114))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-7842))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(3699))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(4384))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(9546))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-3750))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(967))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(y(7791))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(x(8844))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-976))).
playerSensor(player,objectIndex(1),player(velocityY(213))).
playerSensor(player,objectIndex(1),player(velocityX(91))).
playerSensor(player,objectIndex(1),intPair(y(469))).
playerSensor(player,objectIndex(1),intPair(x(191))).
