asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(27533))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-822))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-72))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5281))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(10720))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-9704))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-6320))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(16655))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-6533))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(3519))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(4916))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-14874))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(3431))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-3978))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(11086))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(16161))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1233))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-19789))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(16259))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-6740))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-3828))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-563))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(2114))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3188))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-2283))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(7222))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-575))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(-9908))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(11772))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-31341))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(21711))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(2353))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-6942))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(1561))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-10798))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(20635))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-11158))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-4636))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-2503))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-4929))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-18693))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3982))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-15342))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6561))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(2443))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(1510))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(2629))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(5862))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-39))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(536))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(7140))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-3946))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(400))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-10937))).
playerSensor(player,objectIndex(1),intPair(rotationZ(646))).
playerSensor(player,objectIndex(1),player(velocityY(382))).
playerSensor(player,objectIndex(1),player(velocityX(767))).
playerSensor(player,objectIndex(1),intPair(y(-3634))).
playerSensor(player,objectIndex(1),intPair(x(-6896))).
