asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-41451))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-20718))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-23794))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-11840))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-3792))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-4907))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-13518))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-21656))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(46845))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-34343))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-2808))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-8460))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(37457))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-32500))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-54061))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-17664))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(18423))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-18425))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-4604))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-6795))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-20074))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(10611))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(11054))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(5176))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-18626))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-5934))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(48825))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(44968))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(18604))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-7582))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-1464))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(27625))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(17452))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-9952))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(8311))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-6546))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(-1607))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(1749))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-8870))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(y(253))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-22130))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(5277))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(13085))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(17814))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-18067))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(3815))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(6097))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(12596))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(y(-5010))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(-3120))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(x(6984))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-15278))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-21251))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(38880))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(4872))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-4947))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(357))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-15618))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-600))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-14333))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(152))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(7391))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(639))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(y(5715))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(x(4254))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(y(5295))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(y(-484))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-30954))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-32747))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(1717))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-12836))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(12499))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(8097))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(x(6865))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-7635))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3464))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(865))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(4411))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(x(2975))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(y(4569))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(x(5509))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(y(4842))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(x(6159))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(x(123))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(y(-945))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(x(1194))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(y(1038))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(x(-11574))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-941))).
playerSensor(player,objectIndex(1),player(velocityY(470))).
playerSensor(player,objectIndex(1),player(velocityX(-1367))).
playerSensor(player,objectIndex(1),intPair(y(939))).
playerSensor(player,objectIndex(1),intPair(x(-5145))).
