asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(12148))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-32933))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(24385))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(2776))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-8311))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-7059))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(12124))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-11902))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-1422))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(17868))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-7287))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-5353))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(28958))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-214))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-668))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5486))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-12680))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-5076))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-21573))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3721))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1155))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(18279))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1057))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-21197))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(17463))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-8839))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-4780))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(83))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(2641))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(4511))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-17231))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(3339))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(6385))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(4208))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(389))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(503))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(9691))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(3699))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-4894))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(11680))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(1284))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-11885))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(22235))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(3656))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-17797))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7138))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-422))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(238))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(-9130))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(4820))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-3516))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(356))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-9444))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(5771))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-244))).
playerSensor(player,objectIndex(1),player(velocityY(204))).
playerSensor(player,objectIndex(1),player(velocityX(410))).
playerSensor(player,objectIndex(1),intPair(y(-3276))).
playerSensor(player,objectIndex(1),intPair(x(-6181))).
