asteroidSensor(asteroidClone,objectIndex(19),intPair(y(38072))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(14070))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-41077))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5070))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4940))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-15314))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-20469))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(29120))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(153))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-28403))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6535))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-7329))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1848))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2439))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-7524))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(11546))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-30360))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-2863))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-9583))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(14720))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(36248))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(2897))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(19310))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-23150))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-132))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-17449))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(23624))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-19577))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-9655))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-10091))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-29293))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(7928))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-4252))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(3884))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4061))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8000))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9322))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1316))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-1079))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-3716))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(30427))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10841))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(24077))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-11147))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-36312))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2388))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2586))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-7054))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-1316))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(4911))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-15060))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(7447))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-9337))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-5239))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-4998))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(4385))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(8656))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(-206))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(-691))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(4433))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(5519))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-1532))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(1488))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-1177))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-8072))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(8007))).
playerSensor(player,objectIndex(1),intPair(rotationZ(994))).
playerSensor(player,objectIndex(1),player(velocityY(1))).
playerSensor(player,objectIndex(1),player(velocityX(2))).
playerSensor(player,objectIndex(1),intPair(y(-3073))).
playerSensor(player,objectIndex(1),intPair(x(-5773))).
