asteroidSensor(asteroidClone,objectIndex(60),intPair(y(20470))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(38594))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-23108))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-30386))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(43581))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10716))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(27332))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(15574))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(5477))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(15977))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-2637))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-46577))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-4211))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-11163))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(23772))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(19349))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-18260))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-5757))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-204))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-33746))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-52623))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(13552))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(46688))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(3206))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-2174))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(302))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-17233))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-3447))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-8050))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-11155))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(-7032))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-16775))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-4675))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-20594))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-20102))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-32962))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-11629))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(6548))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-7056))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-3670))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(-189))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-10828))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-644))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(1469))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-6125))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(592))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-19500))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-18539))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-7126))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-29764))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(16557))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-4576))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-1600))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-9691))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(2596))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(3368))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(1093))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(2852))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(627))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(3443))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-1427))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-10166))).
asteroidSensor(asteroidCloneClone,objectIndex(109),intPair(x(3013))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-51778))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(33618))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(8093))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(20575))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-4021))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(26183))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(24385))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(8977))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(5193))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(7833))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-5775))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-8381))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-4096))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(6292))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(2096))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(10101))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(2284))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(153))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-9457))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(989))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-10872))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(4426))).
asteroidSensor(asteroidCloneClone,objectIndex(108),intPair(y(-1571))).
asteroidSensor(asteroidCloneClone,objectIndex(108),intPair(x(3129))).
asteroidSensor(asteroidCloneClone,objectIndex(109),intPair(y(-1135))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-841))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
