asteroidSensor(asteroidClone,objectIndex(8),intPair(x(5304))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(2226))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(5564))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-242))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(8282))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3617))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(5776))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(1963))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-16549))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(942))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(14294))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-3708))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-1576))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(6387))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-537))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(708))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(4536))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(3259))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(5462))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-3144))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-6703))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3375))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-9033))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(10723))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-624))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-3142))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-6472))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-3525))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2875))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-2330))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(4136))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(-365))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(5142))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-693))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(5757))).
playerSensor(player,objectIndex(1),player(velocityY(-1424))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-175))).
playerSensor(player,objectIndex(1),intPair(x(0))).
