asteroidSensor(asteroidClone,objectIndex(5),intPair(y(1467))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(2437))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-17610))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1121))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(15243))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-3342))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-1361))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-719))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(1844))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3442))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(5960))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-1294))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4864))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-1394))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(6167))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(54))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-954))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(8532))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(3925))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2243))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-6067))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(5065))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-2113))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2757))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-7641))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3512))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-8561))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(9257))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3952))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-1418))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(6824))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(6187))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-26))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(5872))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-23))).
playerSensor(player,objectIndex(1),player(velocityY(-1164))).
playerSensor(player,objectIndex(1),player(velocityX(754))).
playerSensor(player,objectIndex(1),intPair(y(-1235))).
playerSensor(player,objectIndex(1),intPair(x(45))).
