asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(12134))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(12435))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(30047))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(250))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-5413))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-22274))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5643))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(13197))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(18383))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-10443))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-19674))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-34150))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(3904))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-5595))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-13583))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(1073))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-12716))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-5509))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-13844))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-5677))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-23775))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(4025))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-9357))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(19899))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(922))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(23459))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-7624))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(18796))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-7864))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3522))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(4835))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7579))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-19033))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(2944))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(718))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(8977))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-1123))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(26430))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(3099))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-596))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(578))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(1970))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(4201))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(5745))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-305))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-733))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(28))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3045))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-3187))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(5489))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4532))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(10764))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(461))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-9151))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(672))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9060))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-492))).
playerSensor(player,objectIndex(1),player(velocityY(94))).
playerSensor(player,objectIndex(1),player(velocityX(189))).
playerSensor(player,objectIndex(1),intPair(y(-3166))).
playerSensor(player,objectIndex(1),intPair(x(-5960))).
