asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(24628))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-2061))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1593))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(11006))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(1141))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(16257))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(1491))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-5222))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(2126))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-8581))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-4813))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(14180))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-3739))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-28096))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2885))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-2110))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(9874))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-4151))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(11841))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-16918))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4863))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(7856))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(17370))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-4995))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(13804))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-2462))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-1885))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-8054))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-4707))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-1884))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(5308))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(5741))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-4064))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-12820))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4513))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-1029))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-363))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-3762))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-10336))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5385))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-10068))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(614))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(8928))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-886))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(4104))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(5635))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(9233))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-914))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(604))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(-11495))).
playerSensor(player,objectIndex(1),intPair(rotationZ(999))).
playerSensor(player,objectIndex(1),player(velocityY(-1273))).
playerSensor(player,objectIndex(1),player(velocityX(-3521))).
playerSensor(player,objectIndex(1),intPair(y(-2629))).
playerSensor(player,objectIndex(1),intPair(x(-4068))).
