asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4082))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(12685))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-35211))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(804))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(656))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-1520))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(28213))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-23213))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5779))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(19605))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-6206))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(12530))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(30997))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(14134))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-15048))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(888))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-8367))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(19186))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(1010))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(3381))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-10270))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(21311))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-13441))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(24527))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-8117))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-11842))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-6144))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-14859))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-5706))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(124))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(1385))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3931))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-5960))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-25695))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3348))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(5863))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-21311))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7964))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-20605))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(4623))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(5187))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-203))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-1581))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-954))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(1841))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1004))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(1498))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-2901))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(8354))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(5244))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4460))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(10341))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-47))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-10056))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(1709))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9100))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1233))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-11805))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-969))).
playerSensor(player,objectIndex(1),player(velocityY(48))).
playerSensor(player,objectIndex(1),player(velocityX(96))).
playerSensor(player,objectIndex(1),intPair(y(-3120))).
playerSensor(player,objectIndex(1),intPair(x(-5867))).
