asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1877))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(9593))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(3383))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6189))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(3051))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-22104))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-100))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(1000))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-11617))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4091))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-2156))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(19265))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-4350))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3169))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-4488))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(9613))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(1700))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-2324))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-4321))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(8612))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-1978))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(5493))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-1195))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(1338))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(7638))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(3867))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2258))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(2570))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(11344))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-2031))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(9271))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(5437))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-2082))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-8776))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(7265))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-2467))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-6833))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(4851))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6491))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-1095))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-3213))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(-2760))).
playerSensor(player,objectIndex(1),intPair(rotationZ(631))).
playerSensor(player,objectIndex(1),player(velocityY(547))).
playerSensor(player,objectIndex(1),player(velocityX(-226))).
playerSensor(player,objectIndex(1),intPair(y(-2644))).
playerSensor(player,objectIndex(1),intPair(x(2313))).
