asteroidSensor(asteroidClone,objectIndex(18),intPair(y(8666))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-9368))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2762))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(8952))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-28302))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(49222))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1522))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-63645))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-83))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-29075))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-53657))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-15565))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-51661))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(16437))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(2763))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-3954))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(3434))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-41765))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8481))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(32636))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-44010))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-19944))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6661))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-10111))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-27943))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1367))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-27767))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(45619))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-17853))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(35592))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-18305))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(22219))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9892))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(8075))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(3411))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-892))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-3667))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(1966))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-472))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(7422))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(35049))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-39490))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-18695))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-34914))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-11505))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-1377))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-21804))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(16363))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(19039))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-10352))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(3787))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(11223))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-949))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(8085))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6099))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(7515))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1769))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(63451))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-10176))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-1401))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11549))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(26178))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(385))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3036))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(1975))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1293))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(4693))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-15863))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-12065))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-22908))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(1626))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-5641))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-3964))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-2968))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-10956))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-324))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-12895))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(9221))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(5009))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-7551))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(3980))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-9530))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-998))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
