asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(34643))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(21360))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-29021))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(8276))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-43270))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-13921))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-14993))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-33794))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(23265))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-21672))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-3624))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-13878))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-79457))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1512))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-15455))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-1119))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(789))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(9008))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(2967))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(9207))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(192))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-67134))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-18732))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-64601))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10221))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(15778))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(4417))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(7946))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(3645))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(-968))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-4394))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(4317))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(3669))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-9364))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(9430))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(9018))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-41815))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(5123))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-9082))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-1638))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-20737))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-34794))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(7693))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(25409))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(712))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(5088))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(3847))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-2076))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(3790))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(6575))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(6560))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(641))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(403))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-7919))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-4332))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(2031))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2443))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(-1510))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-14304))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-35397))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(30764))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(26861))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-9581))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-13989))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-3045))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-19643))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-14690))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-6403))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-3734))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(2963))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2364))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-7078))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-6827))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-3797))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8311))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(9019))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-5449))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-11589))).
playerSensor(player,objectIndex(1),intPair(rotationZ(857))).
playerSensor(player,objectIndex(1),player(velocityY(1357))).
playerSensor(player,objectIndex(1),player(velocityX(547))).
playerSensor(player,objectIndex(1),intPair(y(-2076))).
playerSensor(player,objectIndex(1),intPair(x(-3113))).
