asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-3474))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-19752))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(38709))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-20242))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(18740))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(30138))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-59962))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-17047))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-57715))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-561))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(2196))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1976))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(38141))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-44880))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-21141))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-38823))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-12635))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2759))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(344))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-12073))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-31430))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(5687))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-27413))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(6805))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-45382))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(9008))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(36243))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-49656))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-12430))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-2441))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-12639))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-71043))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-752))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(26217))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10046))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(11679))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(4942))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(3113))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(3466))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(2076))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(6683))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(5655))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(412))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-5301))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-1597))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-16052))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(1146))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-30560))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(49731))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-24191))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(7763))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-35036))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(3867))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-6353))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(19592))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(22699))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-12739))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-2475))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-18581))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-16122))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-28469))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(5615))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(17860))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-171))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(6019))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-6062))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-12375))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1031))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(6707))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(1190))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-4523))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-3297))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(-512))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(-10108))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(-1893))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-5555))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-8208))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-4549))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-7382))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(6518))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-1777))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(-380))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(237))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(-2315))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(925))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(11757))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-97))).
playerSensor(player,objectIndex(1),player(velocityY(-1771))).
playerSensor(player,objectIndex(1),player(velocityX(-420))).
playerSensor(player,objectIndex(1),intPair(y(-3337))).
playerSensor(player,objectIndex(1),intPair(x(-6567))).
