asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10384))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(19574))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(10674))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-39703))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(2741))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-12840))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-12892))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(3791))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(11431))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-24535))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-25011))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-15484))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-4386))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(3380))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(26667))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(30716))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-17969))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(12774))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(5625))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-40652))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(8821))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-355))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(9618))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(32401))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(1532))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(3611))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-20694))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-8120))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-8212))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-33495))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(10179))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-48093))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(34975))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-328))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2909))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(13017))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(12417))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(5947))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-4250))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-5285))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-22968))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-585))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(1199))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-5062))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(10355))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-6450))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-8909))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-7472))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-10070))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-325))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(603))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(6287))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-11610))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-2636))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-16371))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-39070))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(12096))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-3554))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-8987))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(1301))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-5077))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-3848))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-2459))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(1036))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(2030))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(1372))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(3900))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(-80))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(7274))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-5619))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-4485))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(3577))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(y(1131))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(x(-6300))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-2541))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-7146))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(8333))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(11348))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-273))).
playerSensor(player,objectIndex(1),player(velocityY(3395))).
playerSensor(player,objectIndex(1),player(velocityX(-1516))).
playerSensor(player,objectIndex(1),intPair(y(2674))).
playerSensor(player,objectIndex(1),intPair(x(-6317))).
