asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(14482))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(37812))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(3564))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-4370))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(41008))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-29949))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6760))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(20852))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-25564))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(25410))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-11975))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(24945))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-21881))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1995))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-7989))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-39474))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2102))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-9602))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-42824))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5364))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-10589))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(15373))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(5404))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-16817))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(31446))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-40))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-437))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-18643))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(32185))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11652))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-10701))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-22141))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-7812))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-2812))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(13239))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-33056))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-10724))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-31881))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(8913))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-6068))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(3058))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-844))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(3885))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(3479))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3943))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(7303))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-3701))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-16550))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(9156))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9388))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1341))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-8601))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-3698))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-4025))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(3774))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(7495))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-3477))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(5813))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(7083))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-2553))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(-163))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-2049))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-7562))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(7478))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-10313))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-1779))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(1122))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-11895))).
playerSensor(player,objectIndex(1),intPair(rotationZ(469))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
