asteroidSensor(asteroidClone,objectIndex(19),intPair(y(58260))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-25656))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8083))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(29910))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-39743))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2224))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-35417))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-16734))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(19205))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(47001))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(7486))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-8212))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-16846))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-31959))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-10651))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-8472))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-47086))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(14697))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3246))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(8132))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-25645))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(45110))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1179))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-39032))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(3207))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-8628))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-25308))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(19197))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(187))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(674))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(1100))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(42512))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-16419))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(33237))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-16841))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(32712))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(5827))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-24571))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(1928))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-2140))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(1101))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9775))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(5351))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(1691))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(4369))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-1334))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-3449))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(701))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(2406))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-616))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-10726))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-58054))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(422))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(23185))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-48892))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-14446))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-17565))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(13923))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(16274))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-8548))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-4568))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(3097))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-13809))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-8998))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-18705))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(6208))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-1537))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(9145))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(8757))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(2543))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-7780))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-4629))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6701))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(8646))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-630))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-9883))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(637))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-10510))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(2327))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(11120))).
playerSensor(player,objectIndex(1),intPair(rotationZ(851))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
