asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8590))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-29027))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(50344))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1616))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-42511))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-28343))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(46466))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-54716))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(64867))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(9176))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11732))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-64887))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-195))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(26843))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(226))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2990))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1967))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-18245))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(36234))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-18704))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(35686))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-40395))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-30076))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(2948))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-4357))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-3467))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(3226))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-23842))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-19106))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-35570))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-11695))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-10554))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-1576))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(1701))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-10440))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-28529))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(22890))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9918))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(2159))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(188))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1424))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(5048))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(4094))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(12338))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(7264))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-15814))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-52678))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(16824))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-20657))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6846))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(16906))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(19654))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-10753))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-16319))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-12746))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-3816))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-5965))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-3488))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-11194))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(4367))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(33379))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-45173))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2909))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(8680))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(3793))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-1132))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-1833))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-22746))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-818))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(7849))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(7125))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(1422))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-5166))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-538))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-13426))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1645))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(8798))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-7042))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(3504))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-8483))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(-275))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(-11930))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-925))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
