asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(35719))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-31308))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-48837))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-69970))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-3370))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-30155))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(49134))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-19476))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-44098))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-20787))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-424))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-654))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(29564))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-59048))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-16832))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2799))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(580))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-12393))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(53874))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1910))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-44857))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8931))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-56837))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(18406))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-23575))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(7604))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-34171))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(5357))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-26600))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(19124))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(22168))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(2946))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(2895))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-27662))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(38257))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-19961))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(37692))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(3707))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-6005))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-2648))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(2376))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(4423))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(5350))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(16898))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-284))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(6886))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(5911))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-1412))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-15594))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1138))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(7071))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(1744))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(-10425))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-38256))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-12471))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-12103))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-2290))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-12481))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-11788))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-30925))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(25637))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10024))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(11156))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1962))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(6498))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-18187))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-15534))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(588))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-5417))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(6236))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-5613))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-12169))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-4962))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(1557))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-4201))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(-470))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(-2602))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-5069))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-7382))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-4312))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-7847))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(6971))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-1702))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(-1267))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(-569))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(-2692))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-205))).
playerSensor(player,objectIndex(1),player(velocityY(178))).
playerSensor(player,objectIndex(1),player(velocityX(-1239))).
playerSensor(player,objectIndex(1),intPair(y(-2932))).
playerSensor(player,objectIndex(1),intPair(x(-6160))).
