asteroidSensor(asteroidClone,objectIndex(7),intPair(y(6017))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(2230))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(-2952))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-1607))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(7375))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(379))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(4025))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(7527))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(5550))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-996))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(6534))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(1443))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-7192))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(9267))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(6394))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(4681))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-4972))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-1005))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(11201))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
