asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(9979))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(24880))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-1954))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(8104))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(11073))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(1036))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(16729))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(1565))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-17166))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4899))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(17653))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-4943))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(14395))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-2053))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-8323))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-3816))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-1769))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(5154))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5487))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-28377))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2932))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-2272))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-4393))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(12215))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1562))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-5610))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(2078))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-8773))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-5128))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(14016))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-2832))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-4516))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(5670))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-4138))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-13328))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4467))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-757))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-608))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-3634))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-10770))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-10484))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(772))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(8780))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-859))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(3879))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(5374))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(8941))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-839))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(598))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(-11358))).
playerSensor(player,objectIndex(1),intPair(rotationZ(999))).
playerSensor(player,objectIndex(1),player(velocityY(-1065))).
playerSensor(player,objectIndex(1),player(velocityX(-2946))).
playerSensor(player,objectIndex(1),intPair(y(-2837))).
playerSensor(player,objectIndex(1),intPair(x(-4643))).
