asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8658))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(65758))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(9317))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-41300))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-18491))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(36639))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-18955))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(36087))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-10933))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-1751))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(7031))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-29483))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(51050))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1675))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-42980))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11915))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-66130))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-307))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(27508))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-55775))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(1427))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-10770))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-29115))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(23561))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9944))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(17448))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(20268))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-11154))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-3267))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(3018))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(2568))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(2351))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(850))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1556))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(5402))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-4690))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(33847))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-45906))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-3001))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-28705))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(47000))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-19517))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-36227))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-11885))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-16063))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-53695))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(17211))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-21370))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-31077))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(3134))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-4759))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(67))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2943))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(9285))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(4175))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-1372))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-2289))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-23688))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-16776))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-13427))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-24776))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(4401))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(13453))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-688))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(7614))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(6829))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(1218))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-3668))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-5831))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(7013))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-4008))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-11432))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-751))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-13956))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1521))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(8376))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(3726))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-6534))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(3029))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-7436))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(-323))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(-11562))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-816))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
