asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-9098))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(14406))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(35493))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(2575))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(13))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-16873))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-7299))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(13871))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-40234))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4928))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(22986))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-18466))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-9151))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-19664))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-1544))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(5405))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-2458))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(18566))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-21987))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-7096))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1384))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2654))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2359))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-5826))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-9691))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-5981))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(76))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(27998))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(246))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-27658))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6427))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-34787))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2526))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(10730))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-29060))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(4080))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4119))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8337))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-5468))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(4680))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(2285))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-3401))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(36656))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4716))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-14590))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(29580))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10449))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(23435))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-10748))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9785))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-28045))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(7453))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-3377))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-14341))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(6623))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9290))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1304))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(9216))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(590))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(377))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(3768))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(4764))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-1040))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-757))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-8318))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(8262))).
playerSensor(player,objectIndex(1),intPair(rotationZ(914))).
playerSensor(player,objectIndex(1),player(velocityY(1))).
playerSensor(player,objectIndex(1),player(velocityX(3))).
playerSensor(player,objectIndex(1),intPair(y(-3074))).
playerSensor(player,objectIndex(1),intPair(x(-5775))).
