asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-46134))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-22873))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(16342))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(32603))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(7868))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(22425))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-38686))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-16599))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-5599))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(44857))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(41361))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-31524))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-3325))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-16591))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(42801))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(34283))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-30327))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-50363))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-16607))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-15913))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-16665))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-3861))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-4829))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(7178))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(8861))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(2622))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-18985))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-14012))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-19482))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(34967))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(3216))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-1947))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(228))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-5986))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(44))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(2640))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-13096))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(2557))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-11014))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-39403))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-4428))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-11887))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-19817))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(16917))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-30028))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(812))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-7090))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-5150))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-840))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(24554))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(14794))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(9720))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-267))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(y(5326))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(x(5760))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-11582))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(6435))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(3259))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-5015))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(2248))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(5362))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(8500))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(1946))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-69603))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(19131))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(66954))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-28947))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-3407))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-19950))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(4807))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(11702))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(16065))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-8180))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-11659))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(10500))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(770))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(1005))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-2929))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(585))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(y(-700))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(x(-3760))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(y(-5694))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(x(7745))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-9061))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3715))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(3226))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(7593))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(553))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(350))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(10557))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-471))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(-1414))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(-1785))).
