asteroidSensor(asteroidClone,objectIndex(18),intPair(y(977))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-1836))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(29629))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(741))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-6691))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(12845))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(31751))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(710))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-23958))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5888))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(14877))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-16212))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(20247))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-8766))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(19823))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-5939))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(696))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(1353))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-27220))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3210))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(6679))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(966))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(12884))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-36053))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4224))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(3605))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-10994))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(22433))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-14017))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(25374))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-8508))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-12953))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-6648))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-15665))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(921))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3717))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-6185))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-22611))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8269))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-21853))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(5097))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(4744))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-123))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-2255))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-1734))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1231))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(270))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-2673))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(7860))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(5048))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4402))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(10005))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-451))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-10774))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(2534))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9132))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1245))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-11451))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-768))).
playerSensor(player,objectIndex(1),player(velocityY(28))).
playerSensor(player,objectIndex(1),player(velocityX(56))).
playerSensor(player,objectIndex(1),intPair(y(-3100))).
playerSensor(player,objectIndex(1),intPair(x(-5827))).
