asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-16071))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(30157))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-17605))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(1413))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-38538))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(34365))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10360))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(19024))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(3672))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(11109))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-19824))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-72814))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-20067))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-70054))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(23435))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-32846))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(10327))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-38846))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(26174))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(3825))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-3676))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(2969))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-12368))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-472))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(1583))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(12084))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(12229))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(5450))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(11494))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-4629))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(9404))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(8074))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-12381))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(2983))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(-10))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(7586))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-5830))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-8245))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-7593))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-4670))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(10011))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-47183))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(6118))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-11244))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-2491))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-24120))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-24392))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-39803))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(9339))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(31388))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-15267))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-4192))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-22486))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-7871))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-845))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(148))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2830))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(11568))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-4824))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-7572))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-6663))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(6392))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-4424))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-9364))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(1407))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-3550))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-4868))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(2657))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(y(467))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(x(-5539))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-10460))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-234))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-1946))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(926))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(278))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(1618))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(1879))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-2127))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-7362))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(8686))).
playerSensor(player,objectIndex(1),intPair(rotationZ(51))).
playerSensor(player,objectIndex(1),player(velocityY(2685))).
playerSensor(player,objectIndex(1),player(velocityX(-1657))).
playerSensor(player,objectIndex(1),intPair(y(1445))).
playerSensor(player,objectIndex(1),intPair(x(-5686))).
