asteroidSensor(asteroidClone,objectIndex(4),intPair(y(1858))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(6674))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(5502))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(8754))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(10338))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(5910))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(1186))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-6767))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(3595))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(5855))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(6522))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(4261))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-126))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(5904))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-6470))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-753))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(400))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(11260))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-611))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
