asteroidSensor(asteroidClone,objectIndex(62),intPair(y(32483))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-22829))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(7844))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(22360))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-38603))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-46011))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-11810))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-19731))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(16837))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-69433))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(19076))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(66751))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-28852))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-29900))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(769))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-31392))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-3349))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(34783))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(3138))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-811))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(42611))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(34134))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-30225))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-50189))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-16557))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-3389))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-19848))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(4785))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(11637))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(15983))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-7026))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-5036))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(24409))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(14669))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-12978))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-10975))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-39306))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-4405))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-15812))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-16582))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-3826))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-4737))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-16428))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(9657))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-2022))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(236))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-6035))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(29))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(y(5358))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(x(5799))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-11453))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(6347))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(x(-3900))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(2595))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(8307))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(16244))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-16503))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-5583))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(44670))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(41191))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-18903))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-13952))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-19399))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-8097))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-11604))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(10406))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(7134))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(8779))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(660))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(1040))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(2645))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(2728))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-251))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-2759))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(688))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(y(-659))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(3169))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-4834))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(2174))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(5328))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(y(-5726))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(x(7787))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-9128))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3726))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(3337))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(7743))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(726))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(359))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(10706))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(2008))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-450))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(-1530))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(-1669))).
