asteroidSensor(asteroidClone,objectIndex(8),intPair(y(3792))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(2029))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(1304))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(8989))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-805))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(6196))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(5738))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(6102))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(4453))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(5742))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(11670))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(6995))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-6962))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(6982))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-5783))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-869))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(10734))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(476))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-883))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
