asteroidSensor(asteroidClone,objectIndex(53),intPair(y(19299))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-11427))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-2564))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(31895))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(5537))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(11795))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(3732))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(11270))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(1472))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-20259))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-16221))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-38804))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(34670))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10372))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(3718))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-3615))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(2855))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-12604))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-600))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-90))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-4654))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(10095))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-47638))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(6202))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-24328))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-24702))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-40228))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(9479))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-4846))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(9880))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(8448))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-12637))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2869))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(12550))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-9175))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-33171))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-15376))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-4289))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-22727))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-529))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(1391))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-7996))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-7892))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-6556))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-8577))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-7532))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(1354))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-4873))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(x(-5920))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(10500))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-39275))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(26420))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(30437))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-17787))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(12501))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(11992))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(3182))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(-45))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(7430))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-5725))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(6170))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-4337))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-3699))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-5077))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(3117))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(y(799))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-10265))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-280))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-2202))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(981))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(441))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(1824))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(1625))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-2334))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-7254))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(8510))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-81))).
playerSensor(player,objectIndex(1),player(velocityY(2885))).
playerSensor(player,objectIndex(1),player(velocityX(-1534))).
playerSensor(player,objectIndex(1),intPair(y(2020))).
playerSensor(player,objectIndex(1),intPair(x(-6007))).
