asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(41443))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(5114))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-21414))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-12924))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(16887))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-31166))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1143))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-13898))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-5888))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(47825))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(6482))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-20305))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(24431))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-8934))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-5048))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(963))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-9071))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(11198))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-10283))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-5648))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(36845))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-490))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-33538))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7283))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(28014))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-27230))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-13129))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-26020))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-12195))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-37889))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(2540))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3667))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(5685))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-1766))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(2357))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(4800))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-9044))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(6250))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-6765))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-641))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(969))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(-488))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-110))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(-369))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(15439))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-46881))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(6046))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(36266))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13536))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(28502))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-46816))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(1438))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(17169))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-39313))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4152))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-15517))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(251))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(1504))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-20011))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(13124))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9541))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-122))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(9018))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(10715))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-4922))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-6379))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-10213))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-9433))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-9679))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-2835))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-10257))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(-3874))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-2718))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(11275))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-999))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
