asteroidSensor(asteroidClone,objectIndex(6),intPair(x(1841))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(5042))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(-3394))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(2641))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(7222))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(8148))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(1726))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(-4442))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(6586))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-7661))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(4498))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(9833))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(6990))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(8637))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-410))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
