asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2838))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(33021))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-44613))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-154))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(46058))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-18056))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(35925))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-18512))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11666))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-64435))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-4210))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(8833))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-9531))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-42152))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8537))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-10417))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-1512))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-20397))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6779))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-29712))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(2881))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(3654))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-1045))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-10607))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(35379))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-40066))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-18956))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-35332))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-11626))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(26601))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-54331))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-15724))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-52308))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(16683))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(22646))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9908))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(8460))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-3540))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(3302))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1749))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(2089))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-51))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(3983))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(11933))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-866))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(7935))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(7233))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(7355))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(64185))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(9068))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-28678))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(49804))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1571))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-28065))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(284))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3006))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(1800))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-10320))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-28316))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-1667))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-22403))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(16708))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(19430))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1376))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(4919))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-16153))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-12498))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-23502))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(1496))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-5339))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-3870))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6014))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-3299))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-11107))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-460))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-13233))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1690))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(8952))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(4600))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-7227))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(3678))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-8864))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-964))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
