asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-3751))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-14011))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-42543))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-14543))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-35823))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(9465))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-80361))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1594))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(35127))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-67904))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-18913))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(5258))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-9375))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-1754))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(9445))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(4557))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(8427))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(3062))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(807))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(4266))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-15268))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(23659))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(27308))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-15746))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-974))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(638))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(4917))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(3430))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(-1117))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-4297))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-2422))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(4551))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-6556))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(31252))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10240))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(16218))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(8554))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-34479))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(4134))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-9959))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-14162))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-3200))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-20028))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(101))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(3540))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(7322))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(7239))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(959))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(347))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-4309))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-7749))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-11287))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-65341))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(21641))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-29540))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(9152))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-22004))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-21233))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-35473))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(7916))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(26220))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-9773))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-15386))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-6602))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-3342))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(2581))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2428))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(9180))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-6909))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-4863))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8213))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(8663))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-5310))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(1947))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-2590))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-2030))).
asteroidSensor(asteroidCloneClone,objectIndex(89),intPair(y(-2436))).
asteroidSensor(asteroidCloneClone,objectIndex(89),intPair(x(-1992))).
playerSensor(player,objectIndex(1),intPair(rotationZ(794))).
playerSensor(player,objectIndex(1),player(velocityY(2173))).
playerSensor(player,objectIndex(1),player(velocityX(6))).
playerSensor(player,objectIndex(1),intPair(y(-1450))).
playerSensor(player,objectIndex(1),intPair(x(-3034))).
