asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-4243))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(9659))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(19517))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-4680))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-26))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(758))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(5067))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(4241))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2227))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(11626))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-2162))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(9484))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(5447))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-22385))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1924))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-11866))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4127))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3121))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(1532))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-2593))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-4207))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(8457))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-2486))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6363))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-1528))).
playerSensor(player,objectIndex(1),intPair(rotationZ(665))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(1177))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(7742))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(3278))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6661))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(2818))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(2663))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(9827))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-2289))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-2160))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-8585))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(7193))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-2542))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-6561))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(4607))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-3315))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-1611))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(-2602))).
playerSensor(player,objectIndex(1),player(velocityY(458))).
playerSensor(player,objectIndex(1),player(velocityX(-189))).
playerSensor(player,objectIndex(1),intPair(y(-2555))).
playerSensor(player,objectIndex(1),intPair(x(2276))).
