asteroidSensor(asteroidClone,objectIndex(19),intPair(y(17411))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-1799))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(884))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-5132))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-2505))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(10131))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(25243))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1517))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-17525))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4951))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(14704))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-5320))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(14323))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-4241))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-1604))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5634))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(11168))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-28782))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(3001))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(8462))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-6170))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(2007))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-3367))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-2296))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-8711))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-3929))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-14062))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4400))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-364))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-11085))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(1001))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(10871))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(1673))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-4742))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(12755))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-9050))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(18061))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(4930))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(5566))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-4247))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-961))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-3449))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-11395))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(8567))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-820))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(3555))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(4999))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(8520))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-729))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(590))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(-11159))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-4637))).
playerSensor(player,objectIndex(1),intPair(rotationZ(996))).
playerSensor(player,objectIndex(1),player(velocityY(-823))).
playerSensor(player,objectIndex(1),player(velocityX(-2277))).
playerSensor(player,objectIndex(1),intPair(y(-3079))).
playerSensor(player,objectIndex(1),intPair(x(-5312))).
