asteroidSensor(asteroidClone,objectIndex(79),intPair(y(19843))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-20010))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-6163))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(14029))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(51532))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(47429))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(19755))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-34602))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-23618))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(5598))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(13863))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-2455))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-21901))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-16143))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-22459))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-13638))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-9013))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-32324))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(8724))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(11805))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(11964))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-4239))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-16209))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(9591))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(y(-1955))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(49604))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(39622))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-33983))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-56584))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-18386))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(2335))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-36267))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(570))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-17339))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-828))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(15391))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-6662))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(y(3280))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-9395))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-9241))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-1890))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(29721))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(19266))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-11160))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3294))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(-745))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(2240))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(-5627))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(y(3352))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(x(4949))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(y(1152))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-24422))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-12403))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-42848))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-5233))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-14631))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-22911))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(41549))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(6002))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-4054))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(17))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(5231))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(-252))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(y(8304))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(x(3403))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(x(5671))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(x(6181))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(y(4030))).
asteroidSensor(asteroidCloneClone,objectIndex(138),intPair(y(-4528))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(19008))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-19537))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-19626))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-5111))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-8136))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-22450))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(-3103))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(1197))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(6484))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-11501))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(4884))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(6598))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(x(7365))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(y(1609))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(x(-513))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(y(-350))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(x(3301))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(x(-10265))).
asteroidSensor(asteroidClone,objectIndex(136),intPair(y(-11000))).
asteroidSensor(asteroidClone,objectIndex(136),intPair(x(-1551))).
asteroidSensor(asteroidCloneClone,objectIndex(137),intPair(y(-4326))).
asteroidSensor(asteroidCloneClone,objectIndex(137),intPair(x(6584))).
asteroidSensor(asteroidCloneClone,objectIndex(138),intPair(x(6610))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-794))).
playerSensor(player,objectIndex(1),player(velocityY(149))).
playerSensor(player,objectIndex(1),player(velocityX(-433))).
playerSensor(player,objectIndex(1),intPair(y(1260))).
playerSensor(player,objectIndex(1),intPair(x(-6078))).
