asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(10108))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-24289))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2244))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4372))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(479))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-878))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(6774))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-5980))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(13541))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-3045))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-7292))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-3432))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(2950))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-3516))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(2566))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(9860))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2016))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-13550))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(11278))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-3191))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(10924))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(7407))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(6709))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-3049))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-5496))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-4464))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(7146))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(81))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(8453))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(21221))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(4497))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(35))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(2789))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(2557))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(393))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-4414))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-2686))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-5931))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(5136))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-4717))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-4005))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-4430))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(-1530))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(10929))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-1251))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(9160))).
playerSensor(player,objectIndex(1),intPair(rotationZ(857))).
playerSensor(player,objectIndex(1),player(velocityY(484))).
playerSensor(player,objectIndex(1),player(velocityX(-230))).
playerSensor(player,objectIndex(1),intPair(y(-1508))).
playerSensor(player,objectIndex(1),intPair(x(1780))).
