asteroidSensor(asteroidClone,objectIndex(46),intPair(x(5393))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-9668))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-1870))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-14783))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-36248))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(31741))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10259))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-16038))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(27031))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-30058))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(9287))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-43271))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-828))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(486))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(9882))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(4697))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(902))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(4745))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(3233))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(35610))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-68675))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-19094))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-66080))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(21923))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(16658))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(8832))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-35164))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(24054))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(27755))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-36152))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(8140))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(3214))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(-1265))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-4200))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(3952))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-10337))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-2769))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(5313))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(4864))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-10183))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-16082))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-6740))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-15544))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-3878))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-14144))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-81264))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1676))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(8908))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(3158))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(9722))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-22336))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-21728))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-14336))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-3356))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-20414))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(11))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-6801))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-2951))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(2200))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2491))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(8069))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(7918))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(1276))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(291))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(8930))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-6284))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-4821))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-7578))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-5393))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8116))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(8306))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-5171))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-10986))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(1862))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-2916))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-2268))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-3078))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(-1300))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(y(-2389))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(x(-2266))).
playerSensor(player,objectIndex(1),intPair(rotationZ(734))).
playerSensor(player,objectIndex(1),player(velocityY(1857))).
playerSensor(player,objectIndex(1),player(velocityX(-902))).
playerSensor(player,objectIndex(1),intPair(y(-785))).
playerSensor(player,objectIndex(1),intPair(x(-3272))).
