asteroidSensor(asteroidClone,objectIndex(12),intPair(x(1033))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(7836))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(19740))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-4147))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(544))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(4573))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2200))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(2319))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3077))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-4850))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-2277))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(10017))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-2229))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(9718))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-22635))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1966))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(3185))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7081))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(40))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-12086))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4159))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(3038))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(11878))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-2407))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(9673))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(4737))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(1382))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-2832))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-8416))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-4105))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(8319))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(7130))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-2608))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-2938))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(5406))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-6319))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(4390))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6250))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-1913))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-3406))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-1980))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(-2462))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(11799))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-1410))).
playerSensor(player,objectIndex(1),intPair(rotationZ(704))).
playerSensor(player,objectIndex(1),player(velocityY(1383))).
playerSensor(player,objectIndex(1),player(velocityX(-657))).
playerSensor(player,objectIndex(1),intPair(y(-2407))).
playerSensor(player,objectIndex(1),intPair(x(2208))).
