asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(13849))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-40141))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4912))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10406))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(27874))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(257))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-27575))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6415))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(23364))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-10703))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-28916))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(18484))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-21857))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(29))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-16809))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(29486))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2541))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(10639))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(5460))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-3366))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(36499))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4691))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-14509))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(22915))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-18343))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-9095))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-19574))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-34618))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2334))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-5689))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-1569))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8374))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-2413))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1303))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-9044))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(14371))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(35410))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(2539))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-7070))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1332))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2677))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-7274))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9751))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-27907))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(7401))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-3280))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(4101))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4125))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-14261))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(6532))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9286))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-9731))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-6064))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-5520))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(4712))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(9278))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(679))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(496))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(205))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(3694))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(4681))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-986))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(2373))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-710))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-8345))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(8290))).
playerSensor(player,objectIndex(1),intPair(rotationZ(879))).
playerSensor(player,objectIndex(1),player(velocityY(2))).
playerSensor(player,objectIndex(1),player(velocityX(4))).
playerSensor(player,objectIndex(1),intPair(y(-3074))).
playerSensor(player,objectIndex(1),intPair(x(-5775))).
