asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-22992))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-3258))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-70070))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(19285))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(67511))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-29207))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-50842))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-16743))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(16291))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(17135))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-30380))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(929))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-31889))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-19209))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-17042))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-11120))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-39668))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-4490))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-12098))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-20055))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-14176))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-19711))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(35474))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(3430))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-3957))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-5083))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(9088))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(16611))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-16861))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-5642))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(45370))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(41828))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-3457))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-20232))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(4868))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(11881))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-7268))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-5465))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-921))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(24951))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(15138))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(9893))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-1740))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(207))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-5851))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(84))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-310))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(y(5240))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(x(5652))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-11938))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(6678))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(9030))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(32934))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(7934))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(22602))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-38914))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-46475))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(43324))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(34694))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-30609))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-16192))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-16893))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-8410))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-11812))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(10759))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(7297))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(1070))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(911))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(2561))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(2399))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-13423))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-3397))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(301))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(y(-814))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(x(-3375))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(2453))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(3507))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-5514))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(2451))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(5457))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(y(-5605))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(x(7632))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-8877))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3682))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(2921))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(7181))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(78))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(324))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(10147))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(1777))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-510))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(-1137))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(-2062))).
