asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(15174))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-12278))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(16468))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-29615))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-45758))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5857))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7138))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(23440))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-24946))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(6183))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-19339))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(35350))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-366))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-32545))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-8623))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-4429))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3744))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(27646))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-13365))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(27164))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-25748))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1249))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-8771))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-44783))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(1622))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(2163))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(2800))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(12025))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-947))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-20647))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(35136))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13014))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-12457))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(10565))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-9115))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(3849))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-13879))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-52))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9498))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-1112))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-2392))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(2749))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(8130))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(9709))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-7747))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(40437))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(4685))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-5468))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(45937))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(16081))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-37580))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-11787))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-36225))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(6133))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-5109))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-19053))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(5547))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-7502))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-4266))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-6707))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(6590))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-956))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(1011))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-10678))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-10515))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(-703))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-690))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-8933))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-1719))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-8729))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(-871))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(-5698))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-596))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
