asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(30846))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-26381))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(43579))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-16912))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-59974))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(46523))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1297))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-39971))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8220))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(248))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(24213))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-50528))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-14830))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3174))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(2784))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(14761))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-32974))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-10944))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-9057))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-885))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11009))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(2215))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-2763))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(855))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(17223))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-9168))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-4259))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(4048))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-406))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(2228))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-41208))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2409))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-48657))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(15294))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-17836))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6114))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-26118))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(2281))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-183))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-29))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-19021))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(1397))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-2427))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(904))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(3645))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-14514))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(8781))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(8299))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-7045))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-4400))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-9054))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(7891))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-8609))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(60043))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(8413))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-26558))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(34046))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-17343))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(33514))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-36816))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-17481))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-9137))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-26213))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(20235))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9815))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(6287))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-10051))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-20148))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(2881))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(7930))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-1335))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6494))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(8258))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-1433))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-10251))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(307))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-11329))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(2136))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(10468))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(6903))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-48))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
