asteroidSensor(asteroidClone,objectIndex(19),intPair(y(40694))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(37644))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(3493))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-4300))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(31196))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-19))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-21634))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-42637))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5332))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-10481))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(15303))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-10589))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-21962))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-7760))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-2708))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-895))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(3995))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(8973))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-404))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-18515))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(31997))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11565))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(13058))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-32767))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-10656))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-31604))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(3523))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3955))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(-1683))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(14438))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(5354))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-16656))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(25267))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-11886))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(24804))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(8807))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-5873))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(3007))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-9329))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9381))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1338))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-8680))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-3863))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(5666))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(6915))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-7617))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-29784))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6736))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(20686))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-25305))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2042))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-7940))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-39136))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2133))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(7378))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-3611))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-16391))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-4130))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(3840))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(7620))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(-2672))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-3220))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-2443))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(13))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-1955))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(7535))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-10476))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-1832))).
playerSensor(player,objectIndex(1),intPair(rotationZ(508))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5772))).
