asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-41509))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-21056))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(40850))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-18065))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-61875))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10152))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-27108))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(8521))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-39130))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(4626))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-33826))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(28963))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(1346))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-1211))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(32859))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-64294))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(14155))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(7251))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-8188))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-8002))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-1212))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2568))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(-776))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-13420))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(7398))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(3901))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(6172))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(2614))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-13350))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-2472))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(4980))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-13412))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-13978))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-3155))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-13387))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-76125))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-31267))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(21811))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(25213))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-14380))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-1656))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(22420))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(362))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(5719))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(4441))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(-422))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-18221))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(524))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-800))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(983))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(-529))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-21573))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(40265))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-48582))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-22822))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(20323))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(8256))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-20448))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-18910))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-32290))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(6870))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-4754))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(4991))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(1466))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-7856))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-12124))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-5669))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-5179))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(4371))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2132))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(3820))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(4056))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(610))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(10351))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-7702))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-7829))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-1910))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-8547))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-2376))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-8669))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(10332))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-5961))).
playerSensor(player,objectIndex(1),intPair(rotationZ(974))).
playerSensor(player,objectIndex(1),player(velocityY(752))).
playerSensor(player,objectIndex(1),player(velocityX(1424))).
playerSensor(player,objectIndex(1),intPair(y(-2858))).
playerSensor(player,objectIndex(1),intPair(x(-4176))).
