asteroidSensor(asteroidClone,objectIndex(62),intPair(y(33054))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(19341))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-46599))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-70240))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(34843))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(7958))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(22666))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-38997))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-30711))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-51016))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(3508))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(67714))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-29301))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-23035))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-11159))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-39764))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-4512))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-14235))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-19794))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(35658))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-3475))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-20335))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-1665))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-12175))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-20142))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(43515))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(4890))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(11946))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(16374))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-16293))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-16976))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-3992))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(200))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-5803))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(99))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(1180))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(x(5613))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-12068))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(y(-5573))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(17214))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-30508))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(972))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-32022))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-3234))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-19291))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-5176))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-17206))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-7332))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-5580))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-950))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(25096))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(6766))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-3568))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(198))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(y(-855))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(x(-3235))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(2415))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-5695))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(2524))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(5492))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(9223))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(7032))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(-94))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(y(2920))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-16793))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(16709))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-16956))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-5658))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(45557))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(41997))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(15263))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-8493))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-11867))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(10853))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(7340))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(9170))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(9956))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(877))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-13541))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-326))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(y(5209))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(3597))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(x(7590))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-8810))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3670))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(2810))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(315))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(9998))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(1715))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(y(2590))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(x(2458))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(x(2545))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-518))).
playerSensor(player,objectIndex(1),player(velocityY(143))).
playerSensor(player,objectIndex(1),player(velocityX(-1399))).
playerSensor(player,objectIndex(1),intPair(y(8))).
playerSensor(player,objectIndex(1),intPair(x(-2170))).
