asteroidSensor(asteroidClone,objectIndex(18),intPair(y(2765))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-9385))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(14592))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(35940))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4848))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-15019))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10681))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(28663))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(191))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-28100))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6491))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(30082))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(23816))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-10984))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-29831))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(19007))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-22676))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-73))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-17214))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-7234))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1659))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2527))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-7432))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9966))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-28785))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(7735))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-3896))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(3964))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4085))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8137))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-2698))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9309))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1311))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(4505))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(13989))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-40734))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(5012))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-3587))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(37495))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(23364))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-19124))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-9449))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-20141))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-35691))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2444))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(11214))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2494))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-6554))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-1409))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(5112))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-14767))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(7111))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-9481))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-5541))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-5190))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(8884))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(118))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(-256))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-608))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(4162))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(5211))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-1332))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(1813))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-1006))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-8172))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(8111))).
playerSensor(player,objectIndex(1),intPair(rotationZ(999))).
playerSensor(player,objectIndex(1),player(velocityY(1))).
playerSensor(player,objectIndex(1),player(velocityX(2))).
playerSensor(player,objectIndex(1),intPair(y(-3073))).
playerSensor(player,objectIndex(1),intPair(x(-5774))).
