asteroidSensor(asteroidClone,objectIndex(44),intPair(x(10272))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-48594))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-40174))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-33852))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-16535))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-39363))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-4493))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(35311))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10397))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(19877))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(10865))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-13100))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-15603))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(3599))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(26938))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(31023))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-18170))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(13075))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(5721))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-3488))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(2615))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-5300))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(10879))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-8564))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(12426))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(3857))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(11609))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-24764))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-25352))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-23233))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-647))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(988))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(y(-5502))).
asteroidSensor(asteroidClone,objectIndex(83),intPair(x(-4298))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-5514))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(6379))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-11811))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-2715))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(9232))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-13174))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-21173))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-8257))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-86))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(-119))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(7102))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(y(-8780))).
asteroidSensor(asteroidClone,objectIndex(87),intPair(x(1243))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-5302))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-4012))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(-9856))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-375))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(1093))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-41119))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(9772))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(32958))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(1597))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(3493))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-591))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-2952))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(13531))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(12884))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(-6332))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-9273))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-7405))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(y(5702))).
asteroidSensor(asteroidClone,objectIndex(86),intPair(x(-4155))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(4084))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(y(1496))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(91),intPair(x(-6719))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-2741))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(1097))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(783))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(2256))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-2769))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-7027))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(8140))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(10897))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(3723))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-523))).
playerSensor(player,objectIndex(1),player(velocityY(3380))).
playerSensor(player,objectIndex(1),player(velocityX(-1383))).
playerSensor(player,objectIndex(1),intPair(y(3464))).
playerSensor(player,objectIndex(1),intPair(x(-6646))).
