asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-26445))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(43673))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-16955))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(24304))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-17388))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(33585))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-36939))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-17537))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-50673))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-14864))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(2747))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-33064))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-10970))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-9109))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-909))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11034))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(2240))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-2818))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(833))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3167))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-19149))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(14835))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-324))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(46647))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1308))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-40054))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8232))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(30928))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-41338))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2425))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(34117))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-60144))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(233))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-9182))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-26293))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(20326))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9819))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(6369))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(17307))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-9222))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-4232))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(4020))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-10144))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-20276))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(2922))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(8082))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-1317))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(278))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(7927))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-8644))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(60200))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(8438))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-26638))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-48796))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(15347))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-17934))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6139))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-26254))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(2333))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-216))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-92))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(1423))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-2336))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(922))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(3694))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-14576))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(8749))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(8258))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(2200))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-6981))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-4380))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-6476))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(8224))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-1504))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-10284))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-11401))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(2119))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(10410))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(6816))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-8984))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-158))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
