asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(6904))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-20138))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1546))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(2886))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-2650))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(9129))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3025))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-103))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-5101))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(4119))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(1250))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2477))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(835))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(5645))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3512))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-3145))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-444))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(934))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(2470))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(478))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(17506))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-2469))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-623))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(2690))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-9878))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3837))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-7434))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(5766))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(9367))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-1118))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(8114))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-1224))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(7784))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(8029))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(2877))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-1538))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-10111))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-5121))).
playerSensor(player,objectIndex(1),intPair(rotationZ(431))).
playerSensor(player,objectIndex(1),player(velocityY(-385))).
playerSensor(player,objectIndex(1),player(velocityX(567))).
playerSensor(player,objectIndex(1),intPair(y(-2677))).
playerSensor(player,objectIndex(1),intPair(x(2085))).
