asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8618))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(65234))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(9234))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2947))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-28492))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(46686))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-55293))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(33572))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-45475))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-11832))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-65565))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-256))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(27206))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-21046))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(6947))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(-1263))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-29214))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(50635))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1640))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-42704))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-18346))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(36401))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-18807))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(35851))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-40889))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-15950))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-53233))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(17035))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-10620))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-28848))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(23256))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9932))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(-2082))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-23260))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(3113))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-19330))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-35929))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-11798))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-10761))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-1671))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-30622))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(3050))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-4576))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(139))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2964))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(1551))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(9010))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(4002))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(17201))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(19989))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-10972))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-3358))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(2295))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(2264))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(549))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1496))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(5241))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-16568))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-13118))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-24351))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(4262))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(12946))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-747))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(7721))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(6963))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(1311))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-4906))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-3736))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-5892))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(7127))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-3771))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-11324))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-654))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-13715))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1578))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(8568))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(4017))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-6765))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(3245))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-7912))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(-301))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(-11729))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-876))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
