asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4497))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(13267))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-37676))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6097))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-12389))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(24592))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(26))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(16309))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-18453))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(459))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1798))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(2013))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-24256))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-15125))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(27006))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9261))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3304))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-6617))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-2095))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(530))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-25394))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-30157))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2945))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(8251))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-719))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1669))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9193))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(1597))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-2443))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(32356))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-15092))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-7619))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-17216))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-25113))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8858))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-2235))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(6907))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(4672))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-12158))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(4121))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-8237))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-7625))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(13451))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(33203))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4036))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(21484))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-9535))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(21051))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-6388))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(6012))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(3891))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(32))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4292))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(9357))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-1230))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1268))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-10768))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-6892))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-342))).
playerSensor(player,objectIndex(1),player(velocityY(10))).
playerSensor(player,objectIndex(1),player(velocityX(20))).
playerSensor(player,objectIndex(1),intPair(y(-3082))).
playerSensor(player,objectIndex(1),intPair(x(-5791))).
