asteroidSensor(asteroidClone,objectIndex(19),intPair(y(17726))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-1727))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(814))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(1974))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(11213))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-28969))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(3032))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-17691))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4975))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(14465))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(1723))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-4903))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(13004))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(8627))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-6429))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-3614))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-2408))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-8890))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(4370))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-182))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(3405))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-9178))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(18249))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-5219))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-3980))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-4114))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-1528))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1124))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-3364))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-11684))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(8469))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-802))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(10598))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-2613))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(10200))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(25410))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1497))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(14847))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-5409))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(4827))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(5519))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-4297))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-14401))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5702))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-11362))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(1106))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(4825))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(8325))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-679))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(586))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(-11068))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-4587))).
playerSensor(player,objectIndex(1),intPair(rotationZ(995))).
playerSensor(player,objectIndex(1),player(velocityY(-731))).
playerSensor(player,objectIndex(1),player(velocityX(-2022))).
playerSensor(player,objectIndex(1),intPair(y(-3171))).
playerSensor(player,objectIndex(1),intPair(x(-5567))).
