asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-31147))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(53625))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-20675))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1889))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-44692))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(8907))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(35554))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-58759))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-16764))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(655))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(38114))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-19872))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(37551))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-43851))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(18301))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-23380))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(7553))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-33898))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(22000))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-12284))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(2714))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-69631))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(-624))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(29383))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-56560))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(5253))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-26343))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(18976))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(4260))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(2894))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(5992))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-38077))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-12420))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-11999))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-2243))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-12431))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-11698))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-30765))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(25454))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-10017))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(10991))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(1926))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(6402))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-18062))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-15348))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-27408))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(643))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-5454))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(6305))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-5472))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-12104))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(1687))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-4487))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(-457))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(-10525))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-4237))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(-7994))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(-2811))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-48578))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-3338))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-30027))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(48946))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-19389))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(3657))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-5895))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(-380))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-2812))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-2703))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(2433))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(5266))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(16594))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-320))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(6950))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-1354))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-15450))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(1172))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(7187))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(1919))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-5101))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(-2826))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-4916))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-7121))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(7114))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-1678))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(-1548))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(-823))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-299))).
playerSensor(player,objectIndex(1),player(velocityY(565))).
playerSensor(player,objectIndex(1),player(velocityX(-1213))).
playerSensor(player,objectIndex(1),intPair(y(-2962))).
playerSensor(player,objectIndex(1),intPair(x(-6007))).
