asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-6413))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(973))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(3238))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(1107))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-543))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(10102))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(6091))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(5073))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(8327))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(5406))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(5684))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(3911))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(6198))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-7718))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(9620))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(261))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(10514))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-5073))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(2267))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(6389))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(y(1671))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(x(5490))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-88))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
