asteroidSensor(asteroidClone,objectIndex(8),intPair(x(6554))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(86))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-312))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(3290))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(3541))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(328))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(11026))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3670))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(1754))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(7421))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-12898))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(7418))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(6088))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(4201))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-6234))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-2546))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4945))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(2208))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(6638))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-4219))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-4969))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-7866))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(6828))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-9279))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-319))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
