asteroidSensor(asteroidClone,objectIndex(8),intPair(x(7366))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(4778))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(4106))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(2433))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(3799))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-10527))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(7926))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(492))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-5617))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(4395))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(6861))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-70))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(8003))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-49))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(8835))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-4610))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(3316))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(8903))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(y(2081))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(x(2797))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-5788))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-8242))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-8772))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(7716))).
playerSensor(player,objectIndex(1),intPair(rotationZ(548))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
