asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(64015))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(14922))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-22244))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-10450))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-38005))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-4101))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-15215))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-5370))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-18275))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-37482))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-44338))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-67141))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(18322))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(38899))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(15765))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-28172))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(194))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-18463))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(4487))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-14443))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-29601))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-3678))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-17802))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-13147))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(10758))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(14871))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(x(265))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(30859))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(7522))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(21490))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(32298))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(2086))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-3145))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-15464))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-3354))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-6694))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-27577))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-3488))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-14215))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-6156))).
asteroidSensor(asteroidClone,objectIndex(99),intPair(y(2705))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(-169))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(y(-815))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-40))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-47840))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-15885))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-3491))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-414))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(22458))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(12980))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-6972))).
asteroidSensor(asteroidClone,objectIndex(107),intPair(x(1501))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(y(2947))).
asteroidSensor(asteroidClone,objectIndex(110),intPair(x(3912))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-11375))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-462))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-10774))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-18562))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(40042))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(32118))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-28845))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(42149))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-10857))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(9136))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(6550))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(7667))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(8810))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(y(-3036))).
asteroidSensor(asteroidClone,objectIndex(105),intPair(x(339))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(y(5780))).
asteroidSensor(asteroidClone,objectIndex(113),intPair(x(6328))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-9705))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(5156))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(2081))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(y(-100))).
asteroidSensor(asteroidClone,objectIndex(117),intPair(x(-5790))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(3109))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(1950))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-2384))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(1179))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(4861))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(5705))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(y(-6161))).
asteroidSensor(asteroidClone,objectIndex(122),intPair(x(8346))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-10034))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3885))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(4837))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(9764))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-6))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
