asteroidSensor(asteroidClone,objectIndex(5),intPair(y(1598))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-765))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(8466))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(4087))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(2654))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(14992))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-3439))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(5170))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-1833))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-2487))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2788))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-1642))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(6226))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-1226))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-671))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(1945))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-17330))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1073))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3488))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(5855))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2481))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-6174))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-1369))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(5105))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-7393))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3475))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-8686))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(9645))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(4001))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(6542))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(185))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(5973))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(106))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(5660))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-169))).
playerSensor(player,objectIndex(1),player(velocityY(-1391))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-1008))).
playerSensor(player,objectIndex(1),intPair(x(0))).
