asteroidSensor(asteroidClone,objectIndex(18),intPair(y(2456))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(14289))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(35214))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(281))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(4633))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-14321))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-10600))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-27382))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(6386))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-28579))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-3284))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(36132))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(27583))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-8964))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-19365))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-27583))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-8918))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(29266))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10304))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(23197))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-7009))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1212))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2733))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-7216))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9672))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(7277))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-3053))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-2308))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(13797))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-39922))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(4875))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(18291))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-21556))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(68))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-16660))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(22750))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-18055))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-34223))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2577))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(10428))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2275))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-5371))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-1628))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(5588))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(4152))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4140))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8461))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-14075))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(6318))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9278))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(y(-1300))).
asteroidSensor(asteroidClone,objectIndex(52),intPair(x(-9822))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(-6256))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-5641))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(4789))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(9424))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(y(886))).
asteroidSensor(asteroidCloneClone,objectIndex(55),intPair(x(773))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(504))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(3521))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(4485))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-858))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(2580))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(-601))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-8409))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(8357))).
playerSensor(player,objectIndex(1),intPair(rotationZ(785))).
playerSensor(player,objectIndex(1),player(velocityY(2))).
playerSensor(player,objectIndex(1),player(velocityX(4))).
playerSensor(player,objectIndex(1),intPair(y(-3074))).
playerSensor(player,objectIndex(1),intPair(x(-5776))).
