asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(18239))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-23418))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(41663))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-892))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-36741))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7749))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(30752))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-32002))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-44896))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(27625))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-36166))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1773))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-23887))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(39906))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-15296))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-29482))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-9935))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-7044))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(42))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-13507))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-43250))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(13237))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-14043))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(5129))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-7385))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-23099))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(16664))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9677))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(2395))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-14011))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(5154))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(44683))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(6497))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-7243))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(53908))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(7443))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-15216))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(31262))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-15613))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-10035))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-53367))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(846))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(20676))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-20795))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(1229))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(-620))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(1701))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3422))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(4241))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(3068))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(248))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(1092))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(11877))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(13955))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-7036))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-5324))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-3599))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(373))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(833))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-8712))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-5945))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(205))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(1759))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-12086))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-6427))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-15181))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(1249))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(2002))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-2030))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(10033))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(9877))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(3312))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(-9573))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-5186))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(y(-7207))).
asteroidSensor(asteroidClone,objectIndex(70),intPair(x(9594))).
playerSensor(player,objectIndex(1),intPair(rotationZ(380))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
