asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(9254))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-2937))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(7102))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(2234))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(743))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(2165))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(67))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(345))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-4898))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-482))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-10347))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3906))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-3507))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-3006))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-20669))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1635))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(17981))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-2286))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(3920))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(3777))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(1956))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2418))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(1303))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(5535))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-7198))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(5034))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(3419))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(9900))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-1365))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(8518))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-1475))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(8186))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(7329))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(2559))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-952))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-1685))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-9751))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-4905))).
playerSensor(player,objectIndex(1),intPair(rotationZ(487))).
playerSensor(player,objectIndex(1),player(velocityY(-275))).
playerSensor(player,objectIndex(1),player(velocityX(405))).
playerSensor(player,objectIndex(1),intPair(y(-2787))).
playerSensor(player,objectIndex(1),intPair(x(2247))).
