asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(12111))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(29991))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(226))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-22219))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(5635))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(13142))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(18336))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-10361))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-5396))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(12420))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-1100))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(26326))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(3082))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-13497))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(1083))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-12674))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-7834))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-638))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(553))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(2005))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3532))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(4775))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-19578))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(5778))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-311))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-684))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-3204))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(9014))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(611))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-34087))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(3893))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-5559))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-9304))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(19816))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(929))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(23397))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-7595))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(18748))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-5471))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-13784))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(4217))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-5661))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-23662))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7557))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-18941))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(3990))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(86))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(3009))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(701))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3136))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(5504))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4536))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(10789))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(491))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-9097))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9058))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-468))).
playerSensor(player,objectIndex(1),player(velocityY(98))).
playerSensor(player,objectIndex(1),player(velocityX(197))).
playerSensor(player,objectIndex(1),intPair(y(-3170))).
playerSensor(player,objectIndex(1),intPair(x(-5968))).
