asteroidSensor(asteroidClone,objectIndex(5),intPair(x(962))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(6062))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(5051))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(8306))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-7781))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-6396))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(3220))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(5383))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(5642))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(3894))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(1168))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(6213))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-532))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(9584))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(254))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(10477))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(10054))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-5063))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(2291))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(6445))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(y(1680))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(x(5430))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-70))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
