asteroidSensor(asteroidClone,objectIndex(5),intPair(y(4428))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(364))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(3849))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-5405))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(2219))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(7109))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(4125))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(3297))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(7038))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-11276))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(55))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(7572))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-132))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(8388))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(7345))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-4486))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(3595))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(9573))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(y(2191))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(x(2079))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-5529))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-7608))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-8486))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(7435))).
playerSensor(player,objectIndex(1),intPair(rotationZ(360))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
