asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-23344))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(x(-15015))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(-32796))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-18635))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(20333))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(y(6392))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(52466))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(48278))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(20152))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(y(-35242))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(x(-2334))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(y(-22309))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(y(-3995))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(50556))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(40369))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-34494))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(-57454))).
asteroidSensor(asteroidCloneClone,objectIndex(88),intPair(x(-16441))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(y(-22875))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(y(-23269))).
asteroidSensor(asteroidClone,objectIndex(92),intPair(x(-4144))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(y(-24131))).
asteroidSensor(asteroidCloneClone,objectIndex(93),intPair(x(5708))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(y(14355))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(x(19891))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(y(-11577))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(y(1007))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-24639))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(-12598))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-43330))).
asteroidSensor(asteroidClone,objectIndex(73),intPair(y(-5346))).
asteroidSensor(asteroidClone,objectIndex(98),intPair(x(-9717))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(y(-9813))).
asteroidSensor(asteroidClone,objectIndex(100),intPair(x(-2037))).
asteroidSensor(asteroidCloneClone,objectIndex(101),intPair(y(30443))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(x(10032))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(y(-9864))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(y(-6492))).
asteroidSensor(asteroidCloneClone,objectIndex(94),intPair(x(19420))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(y(-20044))).
asteroidSensor(asteroidCloneClone,objectIndex(95),intPair(x(-20040))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(y(-5286))).
asteroidSensor(asteroidClone,objectIndex(97),intPair(x(-8598))).
asteroidSensor(asteroidCloneClone,objectIndex(118),intPair(x(6935))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(y(-12408))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(120),intPair(x(5252))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(y(6771))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(y(-1300))).
asteroidSensor(asteroidClone,objectIndex(124),intPair(x(1491))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(y(2835))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-20487))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(-6242))).
asteroidSensor(asteroidCloneClone,objectIndex(102),intPair(x(-13915))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(y(14334))).
asteroidSensor(asteroidCloneClone,objectIndex(103),intPair(x(8940))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(y(12217))).
asteroidSensor(asteroidCloneClone,objectIndex(104),intPair(x(12278))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(121),intPair(x(16355))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(y(-6326))).
asteroidSensor(asteroidClone,objectIndex(123),intPair(x(3235))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(x(6159))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(y(2681))).
asteroidSensor(asteroidClone,objectIndex(130),intPair(x(4248))).
asteroidSensor(asteroidCloneClone,objectIndex(131),intPair(x(6413))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(y(3750))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(y(1191))).
asteroidSensor(asteroidCloneClone,objectIndex(84),intPair(x(2548))).
asteroidSensor(asteroidCloneClone,objectIndex(85),intPair(y(-36930))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(90),intPair(x(42470))).
asteroidSensor(asteroidClone,objectIndex(106),intPair(x(644))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(y(-17933))).
asteroidSensor(asteroidCloneClone,objectIndex(111),intPair(x(-906))).
asteroidSensor(asteroidCloneClone,objectIndex(115),intPair(y(-16856))).
asteroidSensor(asteroidClone,objectIndex(116),intPair(x(-3619))).
asteroidSensor(asteroidCloneClone,objectIndex(126),intPair(x(-29))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(y(4486))).
asteroidSensor(asteroidClone,objectIndex(127),intPair(x(-560))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(y(9197))).
asteroidSensor(asteroidCloneClone,objectIndex(128),intPair(x(3551))).
asteroidSensor(asteroidCloneClone,objectIndex(129),intPair(y(-2717))).
asteroidSensor(asteroidCloneClone,objectIndex(132),intPair(x(7781))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(y(2332))).
asteroidSensor(asteroidCloneClone,objectIndex(133),intPair(x(-732))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(y(-145))).
asteroidSensor(asteroidCloneClone,objectIndex(134),intPair(x(4027))).
asteroidSensor(asteroidClone,objectIndex(135),intPair(x(-9813))).
asteroidSensor(asteroidClone,objectIndex(136),intPair(y(-10270))).
asteroidSensor(asteroidClone,objectIndex(136),intPair(x(-1635))).
asteroidSensor(asteroidCloneClone,objectIndex(137),intPair(y(-4017))).
asteroidSensor(asteroidCloneClone,objectIndex(137),intPair(x(6160))).
asteroidSensor(asteroidCloneClone,objectIndex(138),intPair(y(-4128))).
asteroidSensor(asteroidCloneClone,objectIndex(138),intPair(x(6271))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-660))).
playerSensor(player,objectIndex(1),player(velocityY(100))).
playerSensor(player,objectIndex(1),player(velocityX(-291))).
playerSensor(player,objectIndex(1),intPair(y(1309))).
playerSensor(player,objectIndex(1),intPair(x(-6220))).
