asteroidSensor(asteroidClone,objectIndex(9),intPair(y(2159))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(1875))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(5240))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(4428))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(3114))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2983))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(-6400))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2854))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(-570))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(654))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-16737))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(974))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(14461))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-3643))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-1526))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(5615))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-2165))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(6348))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-821))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-367))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(8326))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-3586))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(5634))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(5392))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(-2829))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-3276))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-6868))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3399))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(-8950))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(10464))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(4104))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(5945))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-552))).
playerSensor(player,objectIndex(1),player(velocityY(-1627))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-372))).
playerSensor(player,objectIndex(1),intPair(x(0))).
