asteroidSensor(asteroidClone,objectIndex(5),intPair(y(5843))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(5215))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(882))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-6263))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(8145))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(6323))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-8249))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(9314))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(6864))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(4890))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(3086))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(5328))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(-454))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(203))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(10197))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(9691))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-4986))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(2465))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(y(1749))).
asteroidSensor(asteroidCloneClone,objectIndex(16),intPair(x(4981))).
playerSensor(player,objectIndex(1),intPair(rotationZ(153))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
