asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(x(42057))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(15601))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(48979))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-47567))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(6162))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-13320))).
asteroidSensor(asteroidCloneClone,objectIndex(15),intPair(y(17143))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(6664))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-20896))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-13540))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1262))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(-21883))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(36956))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13854))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(28533))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-28135))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(y(-9254))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(y(5376))).
asteroidSensor(asteroidClone,objectIndex(18),intPair(x(-6145))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(-32114))).
asteroidSensor(asteroidCloneClone,objectIndex(34),intPair(x(-48058))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(1326))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(17834))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(-40372))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-12443))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(436))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(y(1101))).
asteroidSensor(asteroidClone,objectIndex(48),intPair(x(2381))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-3621))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(5411))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(-1384))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(2117))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(4344))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(y(-9986))).
asteroidSensor(asteroidCloneClone,objectIndex(56),intPair(x(9560))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(x(-356))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(37759))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-566))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-34146))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(7371))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(25036))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(29026))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-14223))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-26677))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-9123))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-5427))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(788))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(y(-38906))).
asteroidSensor(asteroidCloneClone,objectIndex(41),intPair(x(11585))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-10996))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4337))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(-16518))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(y(-5977))).
asteroidSensor(asteroidCloneClone,objectIndex(50),intPair(x(-20596))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(13795))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-9567))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(482))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(y(11329))).
asteroidSensor(asteroidCloneClone,objectIndex(57),intPair(x(-5323))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(y(-6179))).
asteroidSensor(asteroidClone,objectIndex(59),intPair(x(6042))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(-6164))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(-449))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(943))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-9928))).
asteroidSensor(asteroidClone,objectIndex(62),intPair(y(-8771))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(244))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-10136))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(y(-3516))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(65),intPair(x(-11191))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(y(-62))).
asteroidSensor(asteroidCloneCloneClone,objectIndex(66),intPair(x(-2759))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(y(-2588))).
asteroidSensor(asteroidClone,objectIndex(67),intPair(x(11039))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(y(11145))).
asteroidSensor(asteroidClone,objectIndex(68),intPair(x(4183))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-864))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3072))).
playerSensor(player,objectIndex(1),intPair(x(-5771))).
