asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-362))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(3513))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6765))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(1165))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-5389))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(5712))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-9040))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(11846))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(3522))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(631))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(4331))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(526))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-7944))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-7067))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-8454))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(831))).
playerSensor(player,objectIndex(1),intPair(rotationZ(999))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
