asteroidSensor(asteroidClone,objectIndex(2),intPair(y(1720))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(4564))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-8658))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(2481))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(694))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(5386))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-10186))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(2571))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-6958))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(6691))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(256))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(7287))).
playerSensor(player,objectIndex(1),intPair(rotationZ(420))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
