asteroidSensor(asteroidClone,objectIndex(3),intPair(y(735))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-1000))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(3191))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-4909))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(5412))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-8688))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(11614))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(3841))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(611))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(4007))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(609))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-7726))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6605))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6889))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-8199))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(777))).
playerSensor(player,objectIndex(1),intPair(rotationZ(759))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
