asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3701))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-493))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-9911))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-37466))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-688))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-14736))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(1942))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-13008))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-15340))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-8820))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(3045))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(412))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(2798))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(4892))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-13727))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(2247))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-5760))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(9139))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(9172))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(4421))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(430))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(632))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-5767))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(6748))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-8640))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-1056))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7333))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-3036))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-5438))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(9963))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-4940))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(5954))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(3176))).
asteroidSensor(asteroidClone,objectIndex(35),intPair(y(-9433))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-24819))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(15744))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1162))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-4073))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(10135))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6297))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(8059))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-4024))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(749))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-4830))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-3994))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-5864))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-8987))).
asteroidSensor(asteroidClone,objectIndex(35),intPair(x(5920))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-209))).
playerSensor(player,objectIndex(1),player(velocityY(1080))).
playerSensor(player,objectIndex(1),player(velocityX(-26))).
playerSensor(player,objectIndex(1),intPair(y(-1361))).
playerSensor(player,objectIndex(1),intPair(x(-6384))).
