asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-3234))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(12890))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-11486))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-5940))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(-3219))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-3648))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-6327))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2960))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(1277))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-1525))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(1274))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-5996))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-2833))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-2123))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-9267))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(3743))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-8319))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-2086))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-9419))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-19108))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2065))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-7284))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-29269))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(1869))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-4405))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3917))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-7946))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1679))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(7790))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(3214))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-5943))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(3926))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7234))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-987))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-6210))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-7779))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(6671))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-1957))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(6960))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-1907))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(-2012))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-9657))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-5867))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(9932))).
playerSensor(player,objectIndex(1),intPair(rotationZ(872))).
playerSensor(player,objectIndex(1),player(velocityY(-1085))).
playerSensor(player,objectIndex(1),player(velocityX(-771))).
playerSensor(player,objectIndex(1),intPair(y(-1595))).
playerSensor(player,objectIndex(1),intPair(x(-5638))).
