asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(22015))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-62151))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(20506))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6589))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(14921))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2395))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7632))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9209))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-23821))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(16573))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7228))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(11811))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-3661))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-15605))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2156))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-31206))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-30016))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2018))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3101))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-1997))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(5096))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(1317))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-7717))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(13888))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(6320))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-3680))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-17825))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-15921))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(19005))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-14072))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(9067))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(3208))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(7420))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1302))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(11422))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(2292))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-11009))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(1655))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5934))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(9705))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1647))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-6024))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1945))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1977))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1812))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-6196))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-4751))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-7815))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3939))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(7746))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-8517))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(525))).
asteroidSensor(asteroidCloneClone,objectIndex(59),intPair(y(1494))).
playerSensor(player,objectIndex(1),intPair(rotationZ(883))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(15301))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(30982))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7363))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(2830))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(19774))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6311))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-1343))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-749))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-11013))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(6091))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4780))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-3888))).
asteroidSensor(asteroidCloneClone,objectIndex(59),intPair(x(793))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(178))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(11998))).
playerSensor(player,objectIndex(1),player(velocityY(-303))).
playerSensor(player,objectIndex(1),player(velocityX(3))).
playerSensor(player,objectIndex(1),intPair(y(2690))).
playerSensor(player,objectIndex(1),intPair(x(-1014))).
