asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2576))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(11412))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-9490))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-1198))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-16151))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2806))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(6101))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(-866))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-5180))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(4675))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-4449))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-506))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-5924))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(2535))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-6991))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-6899))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4496))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-5130))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-2675))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(9289))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-5519))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7183))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(73))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-7341))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-349))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-2537))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-25027))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-4044))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(1260))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-9074))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-944))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-6436))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-4330))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(-369))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-5760))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(1787))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-7560))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-8824))).
playerSensor(player,objectIndex(1),intPair(rotationZ(246))).
playerSensor(player,objectIndex(1),player(velocityY(-7))).
playerSensor(player,objectIndex(1),player(velocityX(-1794))).
playerSensor(player,objectIndex(1),intPair(y(-349))).
playerSensor(player,objectIndex(1),intPair(x(-3089))).
