asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(31677))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(8831))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(24102))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-30663))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(21277))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-22555))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(24728))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-19851))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-3810))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-1274))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-6527))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(14330))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(18904))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(5217))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-13605))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-4789))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(21755))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-1971))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(-696))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-24564))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(7002))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1912))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(1647))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(44175))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-8038))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(28382))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7820))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13116))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(34133))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9027))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-11882))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(8075))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-9898))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(3529))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2272))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-7044))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-7757))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-5714))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(9269))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-9014))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-8042))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-7325))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-8682))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(5231))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(3833))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-20013))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4188))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-41629))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-40324))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(23562))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7888))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(17877))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(12193))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-24380))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(12292))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(5165))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(2775))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(3407))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-931))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(6230))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(452))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(3316))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-8128))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(8868))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-11328))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(8146))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-2212))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5344))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(9071))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-4134))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-10963))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-1435))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(3834))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(11063))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(3222))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-2047))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(3291))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-2432))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-925))).
playerSensor(player,objectIndex(1),player(velocityY(-913))).
playerSensor(player,objectIndex(1),player(velocityX(788))).
playerSensor(player,objectIndex(1),intPair(y(4032))).
playerSensor(player,objectIndex(1),intPair(x(-5016))).
