asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-34763))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-24258))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-23144))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-218))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-12667))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(800))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6914))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(15255))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(215))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-51737))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(5094))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(8800))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(15574))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-2245))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(13436))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-11499))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(15190))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(5036))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-4267))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(7767))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(9894))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(3835))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-1860))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-14486))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-10219))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(5557))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(3573))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-732))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-970))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-3354))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-798))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6788))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(9924))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(20713))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-22052))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-13835))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(4992))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(9794))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(22187))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7506))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-6605))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-19259))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-4946))).
asteroidSensor(asteroidClone,objectIndex(35),intPair(y(-3528))).
asteroidSensor(asteroidClone,objectIndex(35),intPair(x(2689))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-2301))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(364))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(4735))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(5567))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(10201))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-4500))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(5683))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-35))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(2660))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-8135))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(5462))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(3221))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-10774))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-1321))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(4534))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-952))).
playerSensor(player,objectIndex(1),player(velocityY(2417))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(1182))).
playerSensor(player,objectIndex(1),intPair(x(0))).
