asteroidSensor(asteroidClone,objectIndex(19),intPair(y(8153))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(28755))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-18680))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3574))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-38477))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(16042))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(10046))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-3709))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-21318))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-73048))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(21325))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(6603))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(1760))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7763))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11934))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-28594))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(19854))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-20549))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(1019))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-1668))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-8341))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(18630))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(1026))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(3708))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-2447))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(22997))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-18103))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(12738))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(16122))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(4137))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(207))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-20464))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-4779))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-20337))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-1706))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(3459))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-9736))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-2259))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-32))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(29790))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8205))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-8694))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-5809))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-2966))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(556))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(1576))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(5427))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(5492))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(6104))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-11312))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-4065))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7688))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(10416))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(2975))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(-6))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-2286))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(5928))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-6280))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(4191))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-7677))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(1257))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(10671))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-4478))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-37206))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(21063))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(40184))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7834))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(26000))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1387))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(6091))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2363))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-8720))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-6864))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-3926))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-5930))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(4169))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-627))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5131))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-356))).
playerSensor(player,objectIndex(1),player(velocityY(891))).
playerSensor(player,objectIndex(1),player(velocityX(-1964))).
playerSensor(player,objectIndex(1),intPair(y(3095))).
playerSensor(player,objectIndex(1),intPair(x(-1447))).
