asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-693))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(4418))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(10844))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(4898))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(2124))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(884))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-7001))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-7354))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(1068))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(366))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-417))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-3116))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(2935))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-7524))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6074))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6297))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(598))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-11440))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2175))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(73))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-6319))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
