asteroidSensor(asteroidClone,objectIndex(6),intPair(y(6056))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(22850))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-3915))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-18258))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(21186))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-63501))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6782))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(15714))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(32122))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7421))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-2225))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7648))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9547))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-24412))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(16979))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1955))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-6679))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(874))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(14406))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(6642))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(16015))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1627))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-2950))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-1615))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2602))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(2475))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(21015))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6546))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2253))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1526))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1629))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-5603))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-5196))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4618))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-15986))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2331))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-32107))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-30907))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-16495))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(19500))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-14571))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(9521))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(10500))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7285))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(12335))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(5709))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(3629))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(7095))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1127))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-3081))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(12315))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-7221))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(2033))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-12180))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-1249))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-12168))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(6627))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-7298))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3820))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(6786))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-7335))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-2947))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(328))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(11266))).
playerSensor(player,objectIndex(1),intPair(rotationZ(951))).
playerSensor(player,objectIndex(1),player(velocityY(-174))).
playerSensor(player,objectIndex(1),player(velocityX(2))).
playerSensor(player,objectIndex(1),intPair(y(2561))).
playerSensor(player,objectIndex(1),intPair(x(-1013))).
