asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-6815))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-3759))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-2531))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-3895))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(3800))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-4100))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-12187))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(9431))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-170))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(600))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-19337))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(1531))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-6791))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-7234))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-5668))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(443))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-962))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-2450))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2061))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-3729))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(7544))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-8191))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(2288))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-3698))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(4227))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-8325))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-10243))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(5272))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-10586))).
playerSensor(player,objectIndex(1),player(velocityY(-82))).
playerSensor(player,objectIndex(1),player(velocityX(-141))).
playerSensor(player,objectIndex(1),intPair(y(-275))).
playerSensor(player,objectIndex(1),intPair(x(-743))).
