asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-11717))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2000))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-130))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(9196))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-2212))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-4056))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-3890))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(7715))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-8359))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-18662))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(2662))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-7064))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(346))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-6497))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-2790))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(3918))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-3917))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(624))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-3883))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(1855))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-3782))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-7478))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(4427))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-8483))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-5861))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-10639))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-996))).
playerSensor(player,objectIndex(1),player(velocityY(-109))).
playerSensor(player,objectIndex(1),player(velocityX(-186))).
playerSensor(player,objectIndex(1),intPair(y(-248))).
playerSensor(player,objectIndex(1),intPair(x(-697))).
