asteroidSensor(asteroidClone,objectIndex(7),intPair(y(4479))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1152))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(17244))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-13429))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-11218))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-2332))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-15352))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-54437))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(5481))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(11222))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(24467))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-115))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-14784))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5236))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(10929))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-20442))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(14250))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-12645))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(16179))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(6467))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(5163))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(3849))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-36644))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(21653))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-23321))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7030))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(16616))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7538))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-7280))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-4182))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-1211))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-2222))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1212))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(4857))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(12683))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-4969))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(3861))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-9587))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-2210))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-4315))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(10387))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-26059))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-24926))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-2281))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-344))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(4254))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3964))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6902))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(8815))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(1591))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(805))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(9274))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(2308))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-6975))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4559))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(2855))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(6320))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-10555))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(3767))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(2103))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-4412))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(3028))).
asteroidSensor(asteroidCloneClone,objectIndex(53),intPair(y(491))).
asteroidSensor(asteroidCloneClone,objectIndex(53),intPair(x(-1691))).
asteroidSensor(asteroidCloneClone,objectIndex(54),intPair(y(297))).
asteroidSensor(asteroidCloneClone,objectIndex(54),intPair(x(-2010))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-943))).
playerSensor(player,objectIndex(1),player(velocityY(797))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2802))).
playerSensor(player,objectIndex(1),intPair(x(0))).
