asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-19494))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(7563))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4589))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-391))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7695))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10511))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-26102))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(18141))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-15998))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(10821))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(24560))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(18055))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(35380))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7588))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(23131))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-18133))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(20913))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7216))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-4856))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-15468))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-67359))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7336))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(17981))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(25236))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(235))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1107))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-3907))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-6467))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(8158))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4157))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-3464))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(12772))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2837))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-8551))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3193))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(4830))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(6168))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(624))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-1424))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-5818))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3479))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(4041))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-3956))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(-1289))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(387))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-2640))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-17074))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2833))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-34681))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-33452))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7448))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(13833))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(7462))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(1462))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(14867))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-5802))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(1295))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-15527))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-2675))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-258))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(756))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(9175))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2472))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-10739))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(342))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(-2116))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(-628))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(123))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-5939))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(9979))).
playerSensor(player,objectIndex(1),intPair(rotationZ(828))).
playerSensor(player,objectIndex(1),player(velocityY(-35))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2422))).
playerSensor(player,objectIndex(1),intPair(x(-1011))).
