asteroidSensor(asteroidClone,objectIndex(4),intPair(y(745))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(3400))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(3705))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-8222))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-921))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(1641))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(5411))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(6237))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(7480))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(38))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-11111))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
