asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2493))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-15513))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-4127))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-5630))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(11093))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-9059))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2966))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(6334))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-24110))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-758))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(2808))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-7206))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-7437))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4621))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-4872))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-2794))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(-1142))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-700))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-2756))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-452))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(-358))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-5510))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-4306))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(1128))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-9317))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1511))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-5825))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(4877))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(9613))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-4915))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-4814))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-5721))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(1325))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7172))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(302))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-7159))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-7585))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-9050))).
playerSensor(player,objectIndex(1),intPair(rotationZ(27))).
playerSensor(player,objectIndex(1),player(velocityY(-11))).
playerSensor(player,objectIndex(1),player(velocityX(-2614))).
playerSensor(player,objectIndex(1),intPair(y(-346))).
playerSensor(player,objectIndex(1),intPair(x(-2270))).
