asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(47147))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-8190))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(20977))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-24050))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(26017))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-21153))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(15516))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(24083))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-677))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(13689))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(9336))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(26171))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(33854))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-21006))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4646))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(6021))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-15313))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-5328))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-8036))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(19244))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(-1369))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-27619))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-7828))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-27391))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(2613))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-6929))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-43978))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-42647))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(25423))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-14257))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(9172))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-11057))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(-1168))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(12083))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-10615))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-11109))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(11059))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-10470))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-1488))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(30156))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7863))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13996))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-32205))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(22336))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(8248))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(9455))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(2302))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(1621))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-9207))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-8364))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(2681))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(5751))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(7880))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-3877))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-10020))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(1776))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(7054))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(-6643))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(13792))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-4965))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-2198))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(37369))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9639))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-7761))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(4428))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(4771))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-353))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(8294))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(6006))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-14048))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(9666))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-3393))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5503))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(3516))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(10236))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(3475))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-1701))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(9820))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-5230))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(2645))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-735))).
playerSensor(player,objectIndex(1),player(velocityY(-610))).
playerSensor(player,objectIndex(1),player(velocityX(714))).
playerSensor(player,objectIndex(1),intPair(y(2300))).
playerSensor(player,objectIndex(1),intPair(x(-3020))).
