asteroidSensor(asteroidClone,objectIndex(2),intPair(y(3837))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(-18))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(1423))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(4000))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(5631))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(758))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-8551))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(6459))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(7685))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-11351))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-996))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
