asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-2388))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-4669))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2633))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-25653))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-1499))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(1350))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-16588))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-109))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-543))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-6124))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(2349))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-6844))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-3865))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-8907))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-557))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-6854))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(4538))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-3998))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(160))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7191))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-83))).
playerSensor(player,objectIndex(1),intPair(rotationZ(327))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(11631))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-9785))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2696))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(5943))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(-1214))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-4953))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-6530))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4410))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-5307))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-2593))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(9068))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-5933))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-5787))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(2103))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-7835))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-7174))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-8670))).
playerSensor(player,objectIndex(1),player(velocityY(-6))).
playerSensor(player,objectIndex(1),player(velocityX(-1387))).
playerSensor(player,objectIndex(1),intPair(y(-351))).
playerSensor(player,objectIndex(1),intPair(x(-3497))).
