asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(24148))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-20326))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4333))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-42369))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-41056))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(25134))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-20261))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(5470))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(45111))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-8086))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(28941))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7834))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13393))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(14704))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(19558))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-14144))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-4959))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-10263))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(8990))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(24754))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(32363))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-31149))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(21611))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-23026))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7935))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(18307))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(12697))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-4173))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-1565))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(35153))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9220))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-12630))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(8420))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(22488))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-1564))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(-908))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-25527))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-6937))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-25329))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(12732))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(6137))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(7775))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(2035))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(2928))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2251))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-6651))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-8214))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-6359))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(3296))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(3837))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-749))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(6881))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(1133))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(760))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(10156))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-9518))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-9008))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-7652))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(3116))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-7750))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(9558))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-9245))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(5475))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-12185))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(8625))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-2584))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5394))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(4437))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(8696))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-4053))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-10666))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-1452))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(3734))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(10802))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(3302))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-842))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(4476))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-2202))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-999))).
playerSensor(player,objectIndex(1),player(velocityY(-1642))).
playerSensor(player,objectIndex(1),player(velocityX(1922))).
playerSensor(player,objectIndex(1),intPair(y(3332))).
playerSensor(player,objectIndex(1),intPair(x(-4228))).
