asteroidSensor(asteroidClone,objectIndex(2),intPair(x(11563))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-9694))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-6063))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-4601))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2615))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-532))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-6889))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-16454))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2730))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(5991))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-25460))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-1406))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-3920))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(1322))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-5253))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-2618))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(9136))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-5806))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-5779))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(2006))).
playerSensor(player,objectIndex(1),intPair(rotationZ(313))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-183))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-2434))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(-1107))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-5023))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(2406))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-6644))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4437))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-8958))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-676))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-6726))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(4580))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-4100))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(-2))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7188))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-34))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-7750))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-7225))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-8717))).
playerSensor(player,objectIndex(1),player(velocityY(-6))).
playerSensor(player,objectIndex(1),player(velocityX(-1501))).
playerSensor(player,objectIndex(1),intPair(y(-351))).
playerSensor(player,objectIndex(1),intPair(x(-3382))).
