asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-23276))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-36577))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(21620))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(10892))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(4456))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1139))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-14750))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5227))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-2315))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-15321))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-54341))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(5467))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(10330))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(17185))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-13401))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-25995))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-24862))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(11171))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(24386))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7026))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(16568))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7537))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-7256))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-20400))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(14220))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-12604))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(16144))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-11182))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(6435))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(5106))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-137))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-2234))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-324))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(4282))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3975))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-4209))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-1250))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-2263))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1198))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6898))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(8778))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(1547))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(3881))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(4882))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(12594))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-4953))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(3926))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(775))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(9298))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(2321))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-7016))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4591))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(2868))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-9630))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-2178))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(6256))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-10590))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(3786))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-4231))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(2138))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-4329))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(2990))).
asteroidSensor(asteroidCloneClone,objectIndex(53),intPair(y(478))).
asteroidSensor(asteroidCloneClone,objectIndex(53),intPair(x(-1622))).
asteroidSensor(asteroidCloneClone,objectIndex(54),intPair(y(227))).
asteroidSensor(asteroidCloneClone,objectIndex(54),intPair(x(-2006))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-946))).
playerSensor(player,objectIndex(1),player(velocityY(829))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2770))).
playerSensor(player,objectIndex(1),intPair(x(0))).
