asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-12590))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-3646))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-2653))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2114))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-3568))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(7397))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-8046))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-4285))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(1967))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-3626))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(4055))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-8189))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(5193))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(9633))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-7087))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-2309))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-3757))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(3699))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-204))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(579))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-19916))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(1253))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-6557))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-7025))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-5503))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(526))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-9902))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-10432))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-941))).
playerSensor(player,objectIndex(1),player(velocityY(-65))).
playerSensor(player,objectIndex(1),player(velocityX(-111))).
playerSensor(player,objectIndex(1),intPair(y(-292))).
playerSensor(player,objectIndex(1),intPair(x(-773))).
