asteroidSensor(asteroidClone,objectIndex(9),intPair(y(6126))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-16084))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-4415))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2567))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2823))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-24930))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-1152))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(2564))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-7013))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-6955))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4509))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-5103))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-2687))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(-450))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(11379))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-9445))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-386))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-2560))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-500))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-5893))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(-813))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-5214))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-4072))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(1246))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-9099))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1004))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-6372))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(4697))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(9323))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-5456))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-4381))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-5756))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(1739))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7182))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(97))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-7518))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-7367))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-8848))).
playerSensor(player,objectIndex(1),intPair(rotationZ(223))).
playerSensor(player,objectIndex(1),player(velocityY(-8))).
playerSensor(player,objectIndex(1),player(velocityX(-1867))).
playerSensor(player,objectIndex(1),intPair(y(-349))).
playerSensor(player,objectIndex(1),intPair(x(-3017))).
