asteroidSensor(asteroidClone,objectIndex(9),intPair(y(7177))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-13195))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-1976))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-3550))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(837))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-2958))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2192))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-255))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(548))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-20784))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-6207))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-6712))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-5256))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(651))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-3227))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(9935))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-7495))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(3547))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-7830))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-4563))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(1485))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-3517))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(3797))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-7986))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-9392))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(5075))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-10202))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-3568))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-3933))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-3605))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-865))).
playerSensor(player,objectIndex(1),player(velocityY(-45))).
playerSensor(player,objectIndex(1),player(velocityX(-78))).
playerSensor(player,objectIndex(1),intPair(y(-312))).
playerSensor(player,objectIndex(1),intPair(x(-806))).
