asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-4511))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-4010))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-4815))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(739))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-1094))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(1712))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-4803))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(8522))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(1015))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-2863))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-8627))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-9499))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(4474))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(57))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-15480))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(3382))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-8349))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-6770))).
asteroidSensor(asteroidCloneClone,objectIndex(17),intPair(y(-255))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-709))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(8088))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-5001))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-9153))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-1232))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(4426))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-4179))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(5374))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-9230))).
asteroidSensor(asteroidCloneClone,objectIndex(17),intPair(x(1316))).
asteroidSensor(asteroidCloneClone,objectIndex(18),intPair(y(131))).
asteroidSensor(asteroidCloneClone,objectIndex(18),intPair(x(1607))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(-1087))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(-112))).
