asteroidSensor(asteroidClone,objectIndex(19),intPair(x(16366))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(23536))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-16299))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2476))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-24898))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(17313))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-16966))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(19906))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(11153))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2209))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(22034))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(6156))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(14831))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(6907))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-32847))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-31639))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(16602))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(33059))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-7218))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-2455))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1306))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-2826))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(6213))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(510))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(2184))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(982))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-2604))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1155))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1479))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(1821))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-13143))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-1659))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-13117))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-6872))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3722))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(451))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4109))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-18613))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-64610))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6941))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7469))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(21745))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7661))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9824))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-14981))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(9895))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-1301))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2772))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7332))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(12766))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6738))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-3002))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(3974))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(6829))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-5115))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-5562))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(13049))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-6813))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(7067))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4486))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(5997))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-6363))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-2174))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(10665))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2524))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-11714))).
playerSensor(player,objectIndex(1),intPair(rotationZ(990))).
playerSensor(player,objectIndex(1),player(velocityY(-110))).
playerSensor(player,objectIndex(1),player(velocityX(1))).
playerSensor(player,objectIndex(1),intPair(y(2497))).
playerSensor(player,objectIndex(1),intPair(x(-1012))).
