asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(26392))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-16203))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(48694))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-8269))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(31080))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7885))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-8114))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(19955))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(5289))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-33007))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(22888))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-24828))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(26688))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(14625))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-5566))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(9369))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-21830))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(16134))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(22056))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(6440))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-5609))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-9962))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-8827))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(12199))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(34987))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-21523))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4885))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-45200))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-43856))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-14454))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(2505))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(628))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(3738))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(-2634))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-9529))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-2680))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(39053))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9957))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-15493))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(9742))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(5481))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-53))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(10458))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-4007))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(3768))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-8506))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-28959))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(14417))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(9853))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(10733))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5586))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(6750))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(7260))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-3744))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(9805))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(3606))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(9262))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(9599))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(27248))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-11661))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(25295))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-3))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(-1720))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-29208))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-11402))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(6410))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-15464))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(9013))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-1321))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-4777))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(3212))).
asteroidSensor(asteroidCloneClone,objectIndex(83),intPair(x(-7583))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(13548))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-11448))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-12705))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-8904))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-1515))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(3350))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(-7815))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(10199))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(-2766))).
asteroidSensor(asteroidCloneClone,objectIndex(83),intPair(y(1746))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-606))).
playerSensor(player,objectIndex(1),player(velocityY(-1658))).
playerSensor(player,objectIndex(1),player(velocityX(336))).
playerSensor(player,objectIndex(1),intPair(y(1348))).
playerSensor(player,objectIndex(1),intPair(x(-2643))).
