asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-35581))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-17455))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3009))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-34343))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4825))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-19927))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-68709))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7530))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(18769))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(36520))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-834))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-26693))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(18547))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-18706))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(21407))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(1107))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(25801))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(3996))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(7885))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-16498))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(11276))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(13567))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(3145))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(15760))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-5305))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(1037))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-16699))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-16624))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(8694))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(-565))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(18775))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(26071))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-9206))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3400))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7505))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(14357))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7451))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-5767))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(5251))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(5843))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-5300))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3359))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(3081))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-2774))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-247))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-4021))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-2418))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7646))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(23812))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7711))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10849))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(8075))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(448))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-844))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-216))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-6912))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-3174))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(683))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(906))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(8443))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2446))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-10260))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-442))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(-1482))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(-104))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(915))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-5111))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(8899))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(2022))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-4890))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-145))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-4649))).
playerSensor(player,objectIndex(1),intPair(rotationZ(625))).
playerSensor(player,objectIndex(1),player(velocityY(-20))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2407))).
playerSensor(player,objectIndex(1),intPair(x(-1011))).
