asteroidSensor(asteroidClone,objectIndex(2),intPair(x(13880))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-12823))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-6939))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-5329))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-21090))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-2620))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(428))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-11165))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(1568))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-8196))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-32114))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-2021))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(2277))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-2733))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-7130))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-1752))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-1698))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3217))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(2368))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-846))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3529))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-7189))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(3438))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(3118))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(6784))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-10196))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-582))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(5616))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6066))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(5361))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7269))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-10664))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-5451))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-7078))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(7527))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-3165))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(8002))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-2960))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(-1054))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-7982))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-5217))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(8552))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(4287))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(10723))).
playerSensor(player,objectIndex(1),intPair(rotationZ(988))).
playerSensor(player,objectIndex(1),player(velocityY(-337))).
playerSensor(player,objectIndex(1),player(velocityX(-239))).
playerSensor(player,objectIndex(1),intPair(y(-2343))).
playerSensor(player,objectIndex(1),intPair(x(-6170))).
