asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(31063))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(13925))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(6343))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-3696))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-17856))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7367))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(20554))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1965))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-15632))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2168))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-31271))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-30080))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(15352))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(9762))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1669))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-6071))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7232))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(11848))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(5139))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(1285))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1290))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-3619))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-4783))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5942))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7633))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9233))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-23863))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(16602))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1990))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3090))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-1970))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2409))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1945))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1799))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-6154))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-785))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-11095))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(6129))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4768))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(7678))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-8433))).
asteroidSensor(asteroidCloneClone,objectIndex(59),intPair(y(1531))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-62248))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6602))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(14977))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(22075))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-15962))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(19041))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-14107))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(9099))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(2805))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(19863))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6328))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-1408))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(3238))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(7397))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(11486))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-7682))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(2273))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-11093))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-7778))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3931))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-3821))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(1613))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(421))).
asteroidSensor(asteroidCloneClone,objectIndex(59),intPair(x(687))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(189))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(11946))).
playerSensor(player,objectIndex(1),intPair(rotationZ(888))).
playerSensor(player,objectIndex(1),player(velocityY(-292))).
playerSensor(player,objectIndex(1),player(velocityX(3))).
playerSensor(player,objectIndex(1),intPair(y(2678))).
playerSensor(player,objectIndex(1),intPair(x(-1014))).
