asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-9309))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(11278))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-497))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-2629))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-7081))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-15883))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2873))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(6199))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-24641))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-1013))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(2650))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-7125))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4548))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-6179))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(4760))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(1593))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-4313))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2541))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-483))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-5800))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(-652))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-5319))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-4154))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(1205))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-9176))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1183))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-5021))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-2725))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(9426))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-5265))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-4534))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(-694))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-5743))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7178))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(170))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-7391))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-7444))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-8919))).
playerSensor(player,objectIndex(1),intPair(rotationZ(170))).
playerSensor(player,objectIndex(1),player(velocityY(-9))).
playerSensor(player,objectIndex(1),player(velocityX(-2102))).
playerSensor(player,objectIndex(1),intPair(y(-348))).
playerSensor(player,objectIndex(1),intPair(x(-2781))).
