asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-6112))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-11146))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-82))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-1924))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-4251))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-4145))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-3621))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-7395))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(8911))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-3104))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(7923))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(653))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-17843))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3116))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-7774))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-6095))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-928))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(1926))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(4061))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-4050))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-8564))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(2248))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-3884))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(4671))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-8676))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(229))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-11121))).
playerSensor(player,objectIndex(1),player(velocityY(-152))).
playerSensor(player,objectIndex(1),player(velocityX(-261))).
playerSensor(player,objectIndex(1),intPair(y(-204))).
playerSensor(player,objectIndex(1),intPair(x(-623))).
