asteroidSensor(asteroidClone,objectIndex(9),intPair(y(6065))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-4500))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2589))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2781))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(2492))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-6957))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-2656))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(11463))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-9558))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-25171))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-1267))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-6814))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4476))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(4644))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-16252))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-515))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-5970))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-4003))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(1281))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-5171))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-4253))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(-246))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-7303))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-294))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-2503))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(-946))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-5127))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-9035))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-855))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-6533))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(9238))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-5615))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-5766))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(1860))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7185))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(37))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-7624))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-8788))).
playerSensor(player,objectIndex(1),intPair(rotationZ(286))).
playerSensor(player,objectIndex(1),player(velocityY(-7))).
playerSensor(player,objectIndex(1),player(velocityX(-1691))).
playerSensor(player,objectIndex(1),intPair(y(-350))).
playerSensor(player,objectIndex(1),intPair(x(-3193))).
