asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-5707))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-4212))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2515))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-874))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-608))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-2698))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-24352))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4588))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-15681))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2924))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(6273))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(-492))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-5423))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-4940))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-2763))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(-939))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(11177))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-9173))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-466))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(2736))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-7149))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-9253))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-1362))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(9528))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-5074))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7175))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(242))).
playerSensor(player,objectIndex(1),intPair(rotationZ(146))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-4237))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(1163))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-7295))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-5986))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(4824))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-4687))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-5731))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(1447))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-7265))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-7521))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-8990))).
playerSensor(player,objectIndex(1),player(velocityY(-10))).
playerSensor(player,objectIndex(1),player(velocityX(-2367))).
playerSensor(player,objectIndex(1),intPair(y(-347))).
playerSensor(player,objectIndex(1),intPair(x(-2516))).
