asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(48939))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(9641))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(27418))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7889))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-8281))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(31226))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(9832))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(35166))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-21604))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4923))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-45393))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-44046))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-2756))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(39319))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-10008))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-15688))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(-1775))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-29459))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(5593))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(26545))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-5654))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-8126))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(20067))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(14756))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-5661))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-11756))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(25486))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(102))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-5))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(9538))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(3915))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(-2865))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-8990))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(12379))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-9451))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-14526))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-33134))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(22975))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-24951))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(26794))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-8613))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-29207))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(14531))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(10107))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(10934))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-11549))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(6474))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-15687))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(10583))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-4104))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-1520))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(3324))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(9737))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(3627))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(4082))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(3301))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-21937))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(16231))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(22226))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(6506))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-16343))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(2538))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(471))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-10082))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-8995))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(5425))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(13779))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-11580))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-12957))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5599))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(6907))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(7162))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-3723))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(9322))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-1261))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(9174))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-4706))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(-8000))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(9962))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(-2702))).
asteroidSensor(asteroidCloneClone,objectIndex(83),intPair(y(1652))).
asteroidSensor(asteroidCloneClone,objectIndex(83),intPair(x(-7785))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-591))).
playerSensor(player,objectIndex(1),player(velocityY(-1472))).
playerSensor(player,objectIndex(1),player(velocityX(298))).
playerSensor(player,objectIndex(1),intPair(y(1162))).
playerSensor(player,objectIndex(1),intPair(x(-2605))).
