asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-21210))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-17978))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-72711))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(8104))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(4060))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(12624))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(15923))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(9893))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7759))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11850))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-28446))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(19752))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-20405))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(56))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(29480))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8147))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-8466))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-3834))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(272))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-20048))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(21127))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(28546))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-18584))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3530))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-38252))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(22873))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(874))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-1555))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-8230))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(18406))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-20171))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-4654))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-2770))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-11149))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-4013))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7674))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(15911))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-2148))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(6498))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-2127))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-5670))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(397))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(1445))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-6710))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-36984))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(20885))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(39899))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7819))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(25829))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(10282))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3005))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(233))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(731))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(3472))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-3632))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-5830))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(4230))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-9851))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-7417))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(5958))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-4502))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1350))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(6274))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2369))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-8840))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(1579))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-1762))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(3262))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-2654))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(5697))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(5222))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(5718))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-6109))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(4116))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-514))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5116))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(1073))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(10785))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-279))).
playerSensor(player,objectIndex(1),player(velocityY(1023))).
playerSensor(player,objectIndex(1),player(velocityX(-999))).
playerSensor(player,objectIndex(1),intPair(y(2963))).
playerSensor(player,objectIndex(1),intPair(x(-1212))).
