asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(24341))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(22402))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(15330))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(7218))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4337))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-19031))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-33716))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-32498))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2506))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(6274))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-17518))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(20383))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-15463))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(10334))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-7849))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-2680))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(6516))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(17290))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(34158))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7526))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(6804))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(83))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(1842))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(23231))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(719))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1303))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-6334))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-65912))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7128))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(17131))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-16666))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2645))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-932))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2971))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7387))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(13271))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-4543))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-5990))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(13910))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(7584))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4330))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-6373))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3607))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-1266))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(595))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(-2064))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7677))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10150))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-25468))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(17705))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(11920))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6965))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-3880))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(4380))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(812))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-2045))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(1572))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-14272))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-2140))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-14231))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(5071))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-5223))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(9959))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2499))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-11252))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(1067))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-2868))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(1183))).
playerSensor(player,objectIndex(1),intPair(rotationZ(989))).
playerSensor(player,objectIndex(1),player(velocityY(-64))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2451))).
playerSensor(player,objectIndex(1),intPair(x(-1012))).
