asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-19047))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(22090))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(29560))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(26656))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7779))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-12260))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(16548))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3743))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-39345))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-38065))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(21752))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(23474))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-18584))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-374))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-29164))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(20246))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-21102))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7743))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(10638))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-2686))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(2860))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(13177))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(16889))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(4434))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-11944))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-4264))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-21594))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-5261))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-21451))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(10933))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1532))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(5385))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(4223))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-21736))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-74350))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(8339))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-2103))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-8770))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(19491))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-3231))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(-41))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(-932))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(2167))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(4615))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-3723))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(1167))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(2081))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-1493))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(3934))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-9293))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(6738))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-6942))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-1064))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5190))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-1384))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(41284))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7890))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(30987))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8432))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-9572))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(7008))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(1579))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2338))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-8259))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(2458))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-2897))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-6346))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-1648))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(4386))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(6532))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-7456))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-5060))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-6314))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(4477))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-8683))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(6667))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(1966))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(10230))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-4383))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-11881))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-534))).
playerSensor(player,objectIndex(1),player(velocityY(1027))).
playerSensor(player,objectIndex(1),player(velocityX(-3149))).
playerSensor(player,objectIndex(1),intPair(y(3630))).
playerSensor(player,objectIndex(1),intPair(x(-2964))).
