asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(22999))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(6078))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-32268))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-31066))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(9603))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-63742))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6817))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(15856))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7651))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9607))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-24518))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(17052))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(10642))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2010))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-6796))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-2275))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6587))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2416))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-12390))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(16143))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(32326))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7432))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(21308))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7295))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(12429))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(5819))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(795))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(3704))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(7037))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1095))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-2977))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(12475))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-7132))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(1987))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(6722))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4589))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-7124))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(14498))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(6700))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-3957))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-18335))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-16054))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2363))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-16597))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(19588))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-14660))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1557))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-2923))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-1547))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2639))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(2412))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(21236))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1445))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1596))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-5497))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-5276))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-1338))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-12374))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-7205))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3799))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(6614))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-2779))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(355))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(11136))).
playerSensor(player,objectIndex(1),intPair(rotationZ(963))).
playerSensor(player,objectIndex(1),player(velocityY(-158))).
playerSensor(player,objectIndex(1),player(velocityX(1))).
playerSensor(player,objectIndex(1),intPair(y(2544))).
playerSensor(player,objectIndex(1),intPair(x(-1013))).
