asteroidSensor(asteroidClone,objectIndex(3),intPair(y(1415))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(7))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(4518))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(478))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-7171))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(3337))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(3700))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(642))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-5667))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(5886))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-9243))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-8071))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6858))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-8602))).
playerSensor(player,objectIndex(1),intPair(rotationZ(955))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
