asteroidSensor(asteroidClone,objectIndex(2),intPair(x(2296))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(4750))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-10390))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(2090))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(2821))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(705))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-7236))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(5573))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(6865))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(208))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-8784))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(7380))).
playerSensor(player,objectIndex(1),intPair(rotationZ(349))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
