asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-25222))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(568))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(15945))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-15612))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-9023))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-479))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1334))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-3938))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(2720))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-5613))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(7106))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(1815))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(4688))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-14109))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7340))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-3181))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(10175))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3753))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(4642))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(531))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-10097))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-38044))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-328))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(3128))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(752))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-8803))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-981))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-15122))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(2553))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(10624))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6322))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(8351))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-13262))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-3870))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-5617))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(9313))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-5684))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-5154))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(944))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-4490))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-3862))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(5674))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(3056))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(9005))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-5799))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-8823))).
asteroidSensor(asteroidClone,objectIndex(35),intPair(y(-9193))).
asteroidSensor(asteroidClone,objectIndex(35),intPair(x(5789))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-7829))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-9093))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-269))).
playerSensor(player,objectIndex(1),player(velocityY(851))).
playerSensor(player,objectIndex(1),player(velocityX(-21))).
playerSensor(player,objectIndex(1),intPair(y(-1133))).
playerSensor(player,objectIndex(1),intPair(x(-6389))).
