asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-6))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(953))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-9324))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(5615))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-8176))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3535))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(3718))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-8123))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-1294))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(8588))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-35634))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-1349))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-617))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-13513))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(2345))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(5540))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-12518))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(1278))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(9292))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-23542))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(15106))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-14478))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-4503))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-1016))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(2782))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-2578))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-12206))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-4512))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-4262))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(131))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-6069))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-664))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3048))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-6254))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6218))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(7135))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7311))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-6211))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(8587))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-4660))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-5909))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-4413))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(6844))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(3556))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(9703))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-9506))).
playerSensor(player,objectIndex(1),intPair(rotationZ(303))).
playerSensor(player,objectIndex(1),player(velocityY(972))).
playerSensor(player,objectIndex(1),player(velocityX(-56))).
playerSensor(player,objectIndex(1),intPair(y(-2454))).
playerSensor(player,objectIndex(1),intPair(x(-6354))).
