asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4547))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-19417))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(12630))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(7505))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7578))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(23010))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3156))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(17928))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(35176))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2782))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-8434))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-15318))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-67118))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7301))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(17840))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(25087))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(1525))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(24339))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7174))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-4693))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-5891))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(1342))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-4167))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7692))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10451))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-25996))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(18068))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7438))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(13739))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(7352))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-312))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-2586))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-15262))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(8062))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4186))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3500))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(4213))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-3365))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-18030))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(20825))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-15909))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(10740))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(316))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1140))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-4013))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-6388))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-426))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(729))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(9306))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2476))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(-721))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-2680))).
playerSensor(player,objectIndex(1),intPair(rotationZ(853))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-17006))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2802))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-34520))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-33293))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(4755))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(6226))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(655))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-1527))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(14707))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-5911))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-10824))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(-1418))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(500))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(482))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(-2229))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(-17))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-6087))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(10172))).
playerSensor(player,objectIndex(1),player(velocityY(-39))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2426))).
playerSensor(player,objectIndex(1),intPair(x(-1011))).
