asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1773))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-25566))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-29244))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-28076))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(13746))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(28498))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(7974))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(974))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1944))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-3166))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-16882))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-59210))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6166))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7236))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(19023))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7596))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-8474))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-12984))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(8076))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-2830))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(715))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-222))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(3603))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(17070))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5799))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(641))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1686))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-4924))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-3783))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-16461))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5668))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(12760))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(5618))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(13192))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(20196))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-14775))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-22533))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(15687))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-14672))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(17928))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-4597))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1335))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2871))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3430))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7103))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(10669))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(3759))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(2282))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(2292))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(8127))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2961))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(2210))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-7489))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(9477))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-8799))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(2854))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-8457))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(337))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-8496))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(4923))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(5131))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-8943))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(4199))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(9839))).
playerSensor(player,objectIndex(1),intPair(rotationZ(302))).
playerSensor(player,objectIndex(1),player(velocityY(-1016))).
playerSensor(player,objectIndex(1),player(velocityX(11))).
playerSensor(player,objectIndex(1),intPair(y(3403))).
playerSensor(player,objectIndex(1),intPair(x(-1023))).
