asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-37930))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11729))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7798))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(25586))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-28235))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(20843))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(28248))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-18448))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3467))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7753))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(19607))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-20201))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-19753))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-36665))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(20630))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(39492))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(667))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-1394))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-8071))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(18088))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-4476))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-19635))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(1321))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-21055))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-72229))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(8035))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-10915))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3939))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7653))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(15724))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(9674))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1296))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(6535))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2378))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-9011))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(6083))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(4836))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-5688))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(22697))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-17800))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(12462))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(15639))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(3950))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(6348))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(10091))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3048))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(577))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(308))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(3136))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-1841))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(2979))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-2950))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-6491))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-3211))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(4317))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-10015))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-4538))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-1990))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(182))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(29037))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8063))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-8141))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-4011))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(364))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-1900))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-5471))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-2489))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(171))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(1258))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(5418))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-5863))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(4010))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-7044))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(5750))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-352))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5094))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(810))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(10948))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-232))).
playerSensor(player,objectIndex(1),player(velocityY(1247))).
playerSensor(player,objectIndex(1),player(velocityX(-376))).
playerSensor(player,objectIndex(1),intPair(y(2738))).
playerSensor(player,objectIndex(1),intPair(x(-1034))).
