asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-35972))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-24290))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-2163))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-15043))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(23653))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-53473))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(5343))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(9820))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(16648))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(10712))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6988))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(16130))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-144))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-13157))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1026))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-25416))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-1817))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(13959))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-12236))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(15826))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(4533))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-4072))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(4165))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(21318))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-22868))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-14445))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5149))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-10861))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(6142))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(4595))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-336))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-1813))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6861))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(8441))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(1153))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(504))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(9506))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(2434))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-7389))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-10011))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-1892))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-3478))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(10559))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(4249))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7527))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-7039))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-20020))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(244))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-4455))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-1600))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-2626))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1065))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(5111))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(11797))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-4802))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(4512))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4881))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(2986))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(5682))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-10909))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(3952))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(2459))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-3587))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(2645))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-981))).
playerSensor(player,objectIndex(1),player(velocityY(1185))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2414))).
playerSensor(player,objectIndex(1),intPair(x(0))).
