asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-239))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3275))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(797))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6243))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(1103))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-2445))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(4563))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(2463))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(4734))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-7893))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-7231))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6485))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-7622))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(11089))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(655))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-11680))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(596))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-3161))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(382))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-5355))).
playerSensor(player,objectIndex(1),intPair(rotationZ(141))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
