asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3047))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(26250))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-17537))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(21513))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(18922))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(36764))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(26067))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(7954))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-35774))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-34534))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-929))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(1031))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(5774))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(18945))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-9347))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3444))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7517))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(14469))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-5962))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(5341))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3334))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4876))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-20020))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-68998))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7571))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-26820))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(18634))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-18829))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(15951))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-5199))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(982))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-16950))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-5189))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(2875))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-2520))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(-1346))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-16605))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(11373))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(13737))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(3211))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(8206))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7501))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-3281))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-16871))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(8808))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(3961))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-10157))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(-410))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-382))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-4140))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-610))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(7))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-2371))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(2254))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7659))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(23958))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7714))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10921))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(410))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-719))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-313))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-7007))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(884))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(938))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(8286))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2440))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(1084))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-4933))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(8668))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-5021))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-397))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-4735))).
playerSensor(player,objectIndex(1),intPair(rotationZ(610))).
playerSensor(player,objectIndex(1),player(velocityY(-18))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2405))).
playerSensor(player,objectIndex(1),intPair(x(-1011))).
