asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-17021))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-25770))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-59644))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6229))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(28865))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(13447))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(20465))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-14898))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1829))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7255))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(19242))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7601))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-8582))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-13144))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(8222))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(8229))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1074))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2745))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3382))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(2140))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-16614))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5707))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(12926))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(5722))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-3241))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-29534))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-28362))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(13976))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-22723))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(15818))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-14857))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(18087))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-4808))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1425))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-2707))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(891))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-40))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2010))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7122))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(10837))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(3957))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(3489))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(17469))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5875))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(348))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(2427))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(8022))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1629))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-4738))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2816))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(2151))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-7298))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-3925))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(9764))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-8639))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(2771))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-8833))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(177))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-8868))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(5095))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(5079))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-8777))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(4161))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(9530))).
playerSensor(player,objectIndex(1),intPair(rotationZ(438))).
playerSensor(player,objectIndex(1),player(velocityY(-850))).
playerSensor(player,objectIndex(1),player(velocityX(10))).
playerSensor(player,objectIndex(1),intPair(y(3237))).
playerSensor(player,objectIndex(1),intPair(x(-1021))).
