asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-2142))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-8060))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-35))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(4876))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-7335))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-7743))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-3605))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(4412))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(2615))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3429))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(757))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6319))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6569))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(11199))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(680))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(1119))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-11789))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(700))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(521))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-4921))).
playerSensor(player,objectIndex(1),intPair(rotationZ(353))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
