asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-9262))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(15039))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-14388))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-4548))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-1419))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-560))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(5496))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-8109))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3518))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(3644))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-1071))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(2755))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(5608))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-23408))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-8069))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-1319))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7309))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-778))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3075))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-6305))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-12391))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(1176))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(8425))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6210))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(7038))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-6259))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(8529))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-4578))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-52))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(986))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-35441))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-13385))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(2387))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-2530))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-12122))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-4564))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(9221))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-4190))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(66))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-6023))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-4457))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(6937))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(3597))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(9759))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-6090))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-9561))).
playerSensor(player,objectIndex(1),intPair(rotationZ(385))).
playerSensor(player,objectIndex(1),player(velocityY(653))).
playerSensor(player,objectIndex(1),player(velocityX(-61))).
playerSensor(player,objectIndex(1),intPair(y(-2534))).
playerSensor(player,objectIndex(1),intPair(x(-6349))).
