asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-25067))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6014))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-16542))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-58150))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(27603))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-16089))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5572))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(12353))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(5365))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-14476))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1635))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(732))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(12569))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(19540))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-12591))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(7718))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(7349))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3178))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3549))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(1356))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-2980))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-22068))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(15367))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-14222))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(17539))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-3130))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(287))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-666))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1781))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(1961))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(8382))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-3433))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-28536))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-27376))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(13185))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7059))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(10257))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(3277))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(2630))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1824))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-5380))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-7536))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7190))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(18488))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7583))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-8209))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-4082))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1114))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(3882))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(16095))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5615))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(3316))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(2353))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-7955))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(8776))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-9189))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(3057))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(730))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-7589))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(4502))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(5258))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-9350))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(4293))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(10594))).
playerSensor(player,objectIndex(1),intPair(rotationZ(20))).
playerSensor(player,objectIndex(1),player(velocityY(179))).
playerSensor(player,objectIndex(1),player(velocityX(-532))).
playerSensor(player,objectIndex(1),intPair(y(3734))).
playerSensor(player,objectIndex(1),intPair(x(-954))).
