asteroidSensor(asteroidClone,objectIndex(2),intPair(x(8306))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-5296))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(4364))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-4389))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-8997))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-1334))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-4101))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-9936))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-3770))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-4666))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(20))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(716))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-16107))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(3081))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-8096))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-8401))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-769))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-1314))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(1769))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-4628))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(8363))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(1155))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-3064))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(4079))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(5187))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-9083))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-6591))).
asteroidSensor(asteroidCloneClone,objectIndex(18),intPair(y(-399))).
asteroidSensor(asteroidCloneClone,objectIndex(18),intPair(x(1893))).
playerSensor(player,objectIndex(1),player(velocityY(-311))).
playerSensor(player,objectIndex(1),player(velocityX(-532))).
playerSensor(player,objectIndex(1),intPair(y(-46))).
playerSensor(player,objectIndex(1),intPair(x(-351))).
