asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-4504))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-1537))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(2920))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6470))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(4109))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(595))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(5160))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-7542))).
playerSensor(player,objectIndex(1),intPair(rotationZ(620))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(372))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3735))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(679))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-8393))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6738))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-7985))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(11419))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(732))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
