asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3463))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(4378))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(11223))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(9))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(749))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6335))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(723))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-2075))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(4907))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-7358))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6588))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(686))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-11813))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-4825))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(2649))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-8097))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-7770))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(1122))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-3704))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(552))).
playerSensor(player,objectIndex(1),intPair(rotationZ(394))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
