asteroidSensor(asteroidClone,objectIndex(2),intPair(y(3131))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(1776))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(3523))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(5275))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(737))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-8020))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(6101))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(7354))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(73))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-10963))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-9141))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(7641))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-756))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
