asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-25423))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(4753))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(637))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(922))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(481))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-10189))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-38334))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-245))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(3170))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-8885))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-943))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-15315))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(2706))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(10868))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6335))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7344))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-3254))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(10281))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(16046))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-15748))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-9125))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3779))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-374))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1420))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-3870))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(2680))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-5536))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(7285))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(1752))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(4585))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-14300))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(8497))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-13389))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-3792))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-5546))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(9400))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-5806))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-5261))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(1041))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-4319))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-3796))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(5533))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(2996))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(8921))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-5766))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-8741))).
asteroidSensor(asteroidClone,objectIndex(35),intPair(y(-9073))).
asteroidSensor(asteroidClone,objectIndex(35),intPair(x(5724))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-7713))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-8972))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-300))).
playerSensor(player,objectIndex(1),player(velocityY(756))).
playerSensor(player,objectIndex(1),player(velocityX(-18))).
playerSensor(player,objectIndex(1),intPair(y(-1037))).
playerSensor(player,objectIndex(1),intPair(x(-6392))).
