asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7592))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(7988))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(18678))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4901))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-20066))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-69143))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-18890))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(21566))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-657))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(19030))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(26339))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-17578))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3065))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-16658))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(11422))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(13822))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(3244))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(391))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-17075))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7665))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(24031))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7716))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10958))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(8272))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-977))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(993))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(26200))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-361))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-7055))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3321))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-35871))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-34629))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(18998))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(36886))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7526))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-6059))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(5386))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(5739))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(16047))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-5146))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(954))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-5134))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(2772))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-2393))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-4200))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-26883))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-9417))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3466))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7523))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(14526))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-3335))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-16995))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(8866))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(3944))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(985))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(954))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(8208))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2437))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-10106))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(-332))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-450))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-695))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(-1278))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(63))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-2347))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(1169))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-4844))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(8552))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(2369))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-5087))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-523))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-4777))).
playerSensor(player,objectIndex(1),intPair(rotationZ(593))).
playerSensor(player,objectIndex(1),player(velocityY(-17))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2403))).
playerSensor(player,objectIndex(1),intPair(x(-1011))).
