asteroidSensor(asteroidClone,objectIndex(3),intPair(y(961))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(3673))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(3361))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-5162))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(4178))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-7841))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-664))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(621))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(5570))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(566))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-8873))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6689))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6983))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-8334))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(11736))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(806))).
playerSensor(player,objectIndex(1),intPair(rotationZ(940))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
