asteroidSensor(asteroidClone,objectIndex(3),intPair(y(168))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-1840))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(2768))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(5018))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-8226))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(706))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(4260))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3582))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(718))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-7438))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6394))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6654))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-7864))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(11309))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(1134))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-11897))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(803))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-4049))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(660))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-4487))).
playerSensor(player,objectIndex(1),intPair(rotationZ(514))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
