asteroidSensor(asteroidClone,objectIndex(3),intPair(y(1211))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-294))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(3547))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-7967))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-5440))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(5744))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-9077))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-8481))).
playerSensor(player,objectIndex(1),intPair(rotationZ(999))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(3488))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(633))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(4365))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(518))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6782))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-7086))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(11871))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(837))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
