asteroidSensor(asteroidClone,objectIndex(2),intPair(x(1272))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(4139))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(5784))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-8779))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-923))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(4204))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(767))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(6612))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(7827))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(-57))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-11518))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
