asteroidSensor(asteroidClone,objectIndex(5),intPair(x(4686))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(4613))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3224))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-7838))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6217))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-7582))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(1098))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(335))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-2545))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-307))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(2412))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(810))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-7197))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6457))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(11052))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(646))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-11644))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(562))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-3013))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-5500))).
playerSensor(player,objectIndex(1),intPair(rotationZ(60))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
