asteroidSensor(asteroidClone,objectIndex(19),intPair(y(8014))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(20758))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(12413))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(28158))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-18408))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3448))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-37833))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(15554))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(3917))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(17992))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3917))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7647))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(15668))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(9608))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-4423))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-19512))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2381))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-21009))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-72084))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-1942))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(220))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(28904))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8038))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-8044))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3061))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(679))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(182))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(3035))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-9062))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(1243))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-5645))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7752))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11693))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-28171))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(19563))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-20139))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(6302))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(605))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-1345))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-8024))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(10033))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1280))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(6614))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(2894))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-3039))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(6199))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(4721))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(4343))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-10065))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(5688))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-36570))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(20554))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(39370))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7792))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(25513))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(22644))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-17746))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-10844))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-4064))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(392))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-19628))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-1832))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-5412))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-2405))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(103))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(1202))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-1865))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-6425))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-3085))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(5328))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-5790))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(3978))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-6932))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-304))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5088))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(731))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(10997))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-4548))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-198))).
playerSensor(player,objectIndex(1),player(velocityY(1324))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2662))).
playerSensor(player,objectIndex(1),intPair(x(-1011))).
