asteroidSensor(asteroidClone,objectIndex(7),intPair(y(4180))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-2113))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-14950))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-24099))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-13075))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(988))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-25223))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6976))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(15984))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-402))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-53183))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(5301))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(9650))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(16469))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(10559))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(23409))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-10754))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(6045))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(4425))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(4617))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-4105))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(4260))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-35770))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(10449))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7523))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-6967))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-19893))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(167))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-4537))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-1717))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-2748))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1020))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(5187))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(11531))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-4751))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(4707))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-10139))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-1797))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-3227))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(21217))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-22732))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-14344))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5123))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-1888))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(13872))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-12113))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(15720))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-1672))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-84))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6849))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(8328))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(1021))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(414))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(9576))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(2472))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-7513))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4978))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(3025))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(5491))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-11016))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(4007))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(2566))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-3339))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(2531))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-998))).
playerSensor(player,objectIndex(1),player(velocityY(1334))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2265))).
playerSensor(player,objectIndex(1),intPair(x(0))).
