asteroidSensor(asteroidClone,objectIndex(2),intPair(y(5953))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(366))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(5428))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(6699))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(822))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-10145))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(7531))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(8680))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-13))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
