asteroidSensor(asteroidClone,objectIndex(5),intPair(y(2594))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(5234))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(4102))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(5906))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-11199))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-3788))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-1146))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(971))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6109))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(10600))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(1034))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(7314))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(1785))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-7154))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-6771))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-7085))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(541))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(136))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-1189))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-236))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-7284))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(8971))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-581))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(-392))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(-7))).
