asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-3452))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(1955))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(927))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(1051))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-920))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(4260))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-6886))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6203))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(10722))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-11319))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(9239))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(5066))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(2765))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-7339))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(5990))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-7219))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(569))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(251))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-1682))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-81))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-6801))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(7546))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-468))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
