asteroidSensor(asteroidClone,objectIndex(19),intPair(x(2622))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-24))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-10142))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(4041))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(9074))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(5863))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1327))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-567))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-17245))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(9955))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-11117))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-41226))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(669))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(3585))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-9701))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7379))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-3977))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-4834))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(4236))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(13311))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6460))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-14656))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-3021))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-2616))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-17109))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(1116))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(3563))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-16209))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-6331))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(2016))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(4129))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(2396))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-6545))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-27439))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(17053))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-2280))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-3191))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(579))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(10271))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-7035))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(11340))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-3135))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(8082))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-5443))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-7922))).
asteroidSensor(asteroidClone,objectIndex(35),intPair(y(-7877))).
asteroidSensor(asteroidClone,objectIndex(35),intPair(x(5069))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-7759))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(1123))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6224))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(3685))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(-4411))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(8185))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(8328))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-584))).
playerSensor(player,objectIndex(1),player(velocityY(567))).
playerSensor(player,objectIndex(1),player(velocityX(-174))).
playerSensor(player,objectIndex(1),intPair(y(-491))).
playerSensor(player,objectIndex(1),intPair(x(-6415))).
