asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-2951))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-3839))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2419))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-5806))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-1015))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-404))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-5367))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-4540))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(1011))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(5057))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-14942))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(3109))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(6542))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(95))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-7919))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4733))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-5278))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(912))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(10808))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-8674))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-23291))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-365))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-9535))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-2018))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(9903))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-4374))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7162))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(507))).
playerSensor(player,objectIndex(1),player(velocityX(-1897))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(3051))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-7398))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-4640))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-2901))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-5248))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(-1834))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-5685))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-6800))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-391))).
playerSensor(player,objectIndex(1),player(velocityY(-16))).
playerSensor(player,objectIndex(1),intPair(y(-341))).
playerSensor(player,objectIndex(1),intPair(x(-1387))).
