asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5511))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(5917))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(12094))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(5204))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-26930))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-2862))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-16326))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-57475))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-28086))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(12828))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(27033))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3624))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-24750))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7161))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(18148))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7575))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-8040))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-974))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3374))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(2852))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-15852))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-21772))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(15164))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-13935))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(17292))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-3321))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(15))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-949))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1678))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5498))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(1812))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-5670))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(12172))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(19123))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-14286))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1547))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-12342))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(7491))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(6951))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(578))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-3755))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7030))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(9995))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(2971))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(4059))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(15475))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(1751))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(8544))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1912))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(3542))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(2444))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-8252))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-3211))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(8329))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-9437))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(3186))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-6951))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(979))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-7011))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(4234))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(5339))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-9609))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(4353))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(11074))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-312))).
playerSensor(player,objectIndex(1),player(velocityY(640))).
playerSensor(player,objectIndex(1),player(velocityX(-804))).
playerSensor(player,objectIndex(1),intPair(y(3661))).
playerSensor(player,objectIndex(1),intPair(x(-780))).
