asteroidSensor(asteroidClone,objectIndex(6),intPair(y(967))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-3755))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(5217))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(1802))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(4118))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-6782))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(544))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-1124))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(2612))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-7172))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(5914))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6118))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-7099))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(10612))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(1035))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-11211))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(147))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-1238))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-220))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-7235))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(7338))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(8998))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-568))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
