asteroidSensor(asteroidClone,objectIndex(5),intPair(x(4844))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-81))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3395))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-8023))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6302))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-7716))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(675))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-5018))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-2209))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(4445))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(2582))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(766))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-7312))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6550))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(11174))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(1115))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-11765))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(677))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-3506))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(490))).
playerSensor(player,objectIndex(1),intPair(rotationZ(310))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
