asteroidSensor(asteroidClone,objectIndex(6),intPair(y(6008))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-30557))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(14202))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(6516))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-3823))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-18088))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(19306))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-15837))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2262))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-31753))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-14375))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(9343))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(12129))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-62971))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6706))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(15403))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(22522))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(10188))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1834))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-6422))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-2115))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7262))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(5468))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(1048))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-3309))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7642))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9414))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-24180))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(16819))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-16269))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(2615))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(20527))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6453))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-1896))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(11965))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-7416))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(2135))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-11720))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(6416))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4682))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-7799))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(15735))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(31674))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7399))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(20919))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1781))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3009))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-1765))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2520))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(3463))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(7223))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1196))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1703))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1701))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-5836))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-5021))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-1052))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-11714))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-7501))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3867))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(7163))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-3316))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(269))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(11554))).
playerSensor(player,objectIndex(1),intPair(rotationZ(928))).
playerSensor(player,objectIndex(1),player(velocityY(-217))).
playerSensor(player,objectIndex(1),player(velocityX(2))).
playerSensor(player,objectIndex(1),intPair(y(2603))).
playerSensor(player,objectIndex(1),intPair(x(-1013))).
