asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-4466))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-17529))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(408))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-2066))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(-1962))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(277))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-5144))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2755))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-27003))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-2146))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-3480))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(1544))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-8548))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-7755))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(4241))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-3284))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(1300))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-420))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(12101))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-10420))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2460))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-6557))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(1948))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-6527))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-5737))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4226))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-5688))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-2418))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(8591))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-6824))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-5846))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(2784))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7207))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-8426))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-6814))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-8337))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(5988))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-995))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(6130))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-1069))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(-2776))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-10991))).
playerSensor(player,objectIndex(1),intPair(rotationZ(433))).
playerSensor(player,objectIndex(1),player(velocityY(1))).
playerSensor(player,objectIndex(1),player(velocityX(-1958))).
playerSensor(player,objectIndex(1),intPair(y(-282))).
playerSensor(player,objectIndex(1),intPair(x(-4452))).
