asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-9091))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(498))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-25356))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-10159))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-38237))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-15250))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3771))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(4716))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(614))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-273))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(3156))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(865))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(2655))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(10787))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6331))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(8448))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7343))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-3229))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-4376))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-409))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1391))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-3892))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(1773))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(4620))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-14236))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-13346))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-3818))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-5570))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-5225))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(1009))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-8769))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(16012))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-15703))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(2693))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-5561))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(7225))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-8858))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-956))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(9371))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-5765))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(10245))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-3818))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(5580))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(3016))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(8949))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-5777))).
asteroidSensor(asteroidClone,objectIndex(35),intPair(y(-9113))).
asteroidSensor(asteroidClone,objectIndex(35),intPair(x(5746))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-7752))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-9012))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-291))).
playerSensor(player,objectIndex(1),player(velocityY(786))).
playerSensor(player,objectIndex(1),player(velocityX(-19))).
playerSensor(player,objectIndex(1),intPair(y(-1068))).
playerSensor(player,objectIndex(1),intPair(x(-6391))).
