asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-1134))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(644))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(607))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3939))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-8614))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6571))).
playerSensor(player,objectIndex(1),intPair(rotationZ(680))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(3908))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(3124))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-4807))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(5349))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(627))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-7680))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6851))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-8146))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(11565))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(766))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
