asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7364))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4623))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-19556))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-67552))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7596))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(23228))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7697))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10560))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(24738))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-34809))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-33579))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(18157))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(35542))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-8645))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3222))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7456))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(13908))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-455))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(1411))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-5731))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(18095))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(25355))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-17129))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2858))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-16069))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(10886))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(12885))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2881))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(599))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-1341))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(170))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-6530))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(1259))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-15695))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-3787))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(7609))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-26186))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(18199))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-18215))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(20984))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(7549))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7250))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-4986))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(4890))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(6121))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(14994))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-2746))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-15634))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(8234))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4134))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-5744))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3462))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(3904))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-123))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(777))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(9071))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2468))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-10670))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(-1185))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(296))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-3544))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(230))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(-2025))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(-553))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-2608))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(236))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-5821))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(9825))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(1097))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-4363))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(862))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-4308))).
playerSensor(player,objectIndex(1),intPair(rotationZ(806))).
playerSensor(player,objectIndex(1),player(velocityY(-33))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2419))).
playerSensor(player,objectIndex(1),intPair(x(-1011))).
