asteroidSensor(asteroidClone,objectIndex(6),intPair(y(4891))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-33990))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-23518))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-22413))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-986))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(9208))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(21251))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6866))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(14696))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-11028))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(14784))).
asteroidSensor(asteroidClone,objectIndex(35),intPair(y(-3987))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-50628))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(4935))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(8148))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(14889))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-432))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(445))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(5358))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-4391))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-5260))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(7336))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(9469))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(3571))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-1666))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-14131))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-9809))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(5184))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(2920))).
asteroidSensor(asteroidClone,objectIndex(35),intPair(x(2940))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-2749))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(6431))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(20327))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-21530))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-13446))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-12354))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(656))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-2518))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(13103))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(-139))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(5099))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(5858))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(9182))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-4307))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-381))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(10190))).
asteroidSensor(asteroidCloneClone,objectIndex(46),intPair(y(-604))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7492))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-6328))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-18774))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-514))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-3819))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-629))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6741))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(2805))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-8611))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(5833))).
asteroidSensor(asteroidCloneClone,objectIndex(46),intPair(x(1201))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(3371))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-11262))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-955))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(3801))).
asteroidSensor(asteroidCloneClone,objectIndex(49),intPair(y(-911))).
asteroidSensor(asteroidCloneClone,objectIndex(49),intPair(x(3277))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-814))).
playerSensor(player,objectIndex(1),player(velocityY(1423))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(176))).
playerSensor(player,objectIndex(1),intPair(x(0))).
