asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-17238))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(5883))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-3359))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-28807))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7609))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-8751))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-23018))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(16021))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-13394))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(8449))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(11099))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-60319))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6326))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(13844))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(20882))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(14333))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(29435))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7284))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(19582))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(8627))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1228))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-5135))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1565))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(242))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2114))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7150))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5992))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-106))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(2637))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(7860))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2590))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(2060))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-8391))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5768))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(13185))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-15088))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1917))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-29984))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-15143))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(18334))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2549))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3306))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-2516))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(1163))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(4263))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(1918))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(3312))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(18090))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1541))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-4448))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-7002))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-4148))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(10211))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(2642))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-9419))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-72))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-9445))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(5363))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4999))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-8518))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(4101))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(9050))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-10122))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-5165))).
playerSensor(player,objectIndex(1),intPair(rotationZ(697))).
playerSensor(player,objectIndex(1),player(velocityY(-644))).
playerSensor(player,objectIndex(1),player(velocityX(7))).
playerSensor(player,objectIndex(1),intPair(y(3031))).
playerSensor(player,objectIndex(1),intPair(x(-1018))).
