asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-14320))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-9216))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-1471))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-517))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-1338))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-8058))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3505))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(3588))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3095))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-6343))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(8303))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-4582))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-1113))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(2734))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(2419))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(5659))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7307))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-23307))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(14988))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(5406))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-8028))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-13288))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6204))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(6965))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(8486))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-4516))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(18))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-87))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(1012))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-35296))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-863))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-12296))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(1100))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-2494))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-12058))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-4602))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-6294))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(9168))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-4137))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-6108))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-4490))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(7007))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(3627))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(9801))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-6106))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-9602))).
playerSensor(player,objectIndex(1),intPair(rotationZ(439))).
playerSensor(player,objectIndex(1),player(velocityY(293))).
playerSensor(player,objectIndex(1),player(velocityX(-64))).
playerSensor(player,objectIndex(1),intPair(y(-2574))).
playerSensor(player,objectIndex(1),intPair(x(-6345))).
