asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-38156))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5432))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-2711))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-16047))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(26300))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(11761))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(4997))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(12369))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7124))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(17710))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-794))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(22409))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-24342))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-15547))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7565))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-7823))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-21392))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(14903))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-3567))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-335))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(2397))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-56607))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(5793))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(11662))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(18586))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(6440))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(379))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-3334))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(2576))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(3137))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(4287))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(14677))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(1481))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(8753))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(2562))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-14041))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1434))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-27507))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-26358))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-13567))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(16974))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-12021))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(7198))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3625))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3722))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-1313))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1545))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6993))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(9658))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5347))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(2025))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-6043))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(3833))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-8634))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-2925))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(7755))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-9757))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(3352))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-6198))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(1300))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-6268))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(3890))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(5442))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-9942))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-557))).
playerSensor(player,objectIndex(1),player(velocityY(914))).
playerSensor(player,objectIndex(1),player(velocityX(-1148))).
playerSensor(player,objectIndex(1),intPair(y(3386))).
playerSensor(player,objectIndex(1),intPair(x(-436))).
