asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5402))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(11632))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(4917))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-2652))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-15939))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(11463))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(18377))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(14801))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(22291))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-24183))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-15428))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-56269))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(5744))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7561))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-7738))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-21244))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-11896))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(7085))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-471))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-13946))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1390))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-27282))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-26135))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-13423))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(16851))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3723))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3759))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-3663))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(2423))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(3248))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(4376))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(14367))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(2069))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-6188))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(3946))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(2608))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(7532))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-9881))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-5980))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-37921))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(12191))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(26015))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7109))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(17540))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(6242))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(302))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-3170))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-724))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-1454))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1493))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6979))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(9527))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5288))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(2625))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(1375))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(8834))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-8782))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-2814))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(3417))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-5905))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(1425))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(3756))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(5483))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-10071))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-592))).
playerSensor(player,objectIndex(1),player(velocityY(701))).
playerSensor(player,objectIndex(1),player(velocityX(-1123))).
playerSensor(player,objectIndex(1),intPair(y(3250))).
playerSensor(player,objectIndex(1),intPair(x(-265))).
