asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-18010))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5986))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(16747))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(14110))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(6458))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-3781))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7639))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9354))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-24074))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-14286))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(9262))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-1733))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(15607))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(31471))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7388))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(20797))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-16167))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(19217))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(5359))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(1127))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-3412))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-62730))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6672))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(15261))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(22373))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(10046))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1779))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-6305))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-2065))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7252))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(12035))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(3388))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(7281))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1227))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(11805))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-7504))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(2181))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-11511))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(6320))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4710))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-8011))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-15769))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2231))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-31592))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-30398))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1851))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3036))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-1833))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2483))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(2678))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(20306))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6411))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1784))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1733))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-5942))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-4942))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-963))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-11508))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-7593))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3888))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(7335))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-3484))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(242))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(11684))).
playerSensor(player,objectIndex(1),intPair(rotationZ(916))).
playerSensor(player,objectIndex(1),player(velocityY(-239))).
playerSensor(player,objectIndex(1),player(velocityX(2))).
playerSensor(player,objectIndex(1),intPair(y(2626))).
playerSensor(player,objectIndex(1),intPair(x(-1014))).
