asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-7382))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(7238))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-2069))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-3607))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(953))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-13027))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(9851))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-241))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(556))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(1619))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-3547))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-8042))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-2873))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2170))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(3589))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-7890))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-4486))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-20543))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-6304))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-6799))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(3868))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-5324))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(616))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-9534))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(5108))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-10266))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-3717))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-3865))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-3258))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-3444))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-876))).
playerSensor(player,objectIndex(1),player(velocityY(-50))).
playerSensor(player,objectIndex(1),player(velocityX(-86))).
playerSensor(player,objectIndex(1),intPair(y(-307))).
playerSensor(player,objectIndex(1),intPair(x(-798))).
