asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-21102))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-72373))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(8056))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7805))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(25659))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(3983))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(20928))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(28337))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-18489))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3486))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-38026))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7755))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11765))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-28298))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(19650))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-20262))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-10985))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3961))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7660))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(15780))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(9740))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(6393))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(729))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-1442))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-8119))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(18183))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(10148))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3035))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(474))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(435))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(3237))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(1315))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-36761))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(20707))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(39614))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(22750))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-17853))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(12511))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(15725))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-2037))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(144))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(29170))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8088))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-8239))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-3958))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(336))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-19879))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-4529))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-19759))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1312))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(6457))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2375))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-8960))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(1398))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-1968))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-5531))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-2573))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(238))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-1817))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(3064))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-2861))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(5967))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(4952))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-6557))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-3337))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-5731))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(4291))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-9966))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(5508))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-5937))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(4042))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-7156))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(5813))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-401))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5101))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(889))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(10900))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-4527))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-237))).
playerSensor(player,objectIndex(1),player(velocityY(1175))).
playerSensor(player,objectIndex(1),player(velocityX(-739))).
playerSensor(player,objectIndex(1),intPair(y(2810))).
playerSensor(player,objectIndex(1),intPair(x(-1071))).
