asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-3486))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-942))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(2748))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-7320))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-6874))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6193))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(10710))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-11307))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(7523))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(5083))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(1938))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(4244))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(932))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(5982))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-7206))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(566))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(1049))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(239))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-1633))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-97))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-6850))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(9212))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-477))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
