asteroidSensor(asteroidClone,objectIndex(4),intPair(y(637))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-160))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(3421))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(3615))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(4433))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(500))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-8535))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(1301))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-5541))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(5807))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-9151))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-8013))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6816))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-7124))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(11920))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(848))).
playerSensor(player,objectIndex(1),intPair(rotationZ(988))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
