asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-9634))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-1162))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(1730))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-1263))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-3936))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-4769))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(732))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(8155))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-5092))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-4749))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(8473))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(45))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-9105))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-15673))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(3289))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-8557))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(4440))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-4473))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(1058))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-2925))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(4319))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-4155))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-8271))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(5316))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-9185))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-6714))).
asteroidSensor(asteroidCloneClone,objectIndex(17),intPair(y(-119))).
asteroidSensor(asteroidCloneClone,objectIndex(17),intPair(x(1189))).
asteroidSensor(asteroidCloneClone,objectIndex(18),intPair(y(-31))).
asteroidSensor(asteroidCloneClone,objectIndex(18),intPair(x(1695))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-718))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(-1381))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(-218))).
