asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-36140))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1058))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(10652))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(4307))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-2205))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-15120))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-13225))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(16252))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-25577))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-24449))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(6224))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(21401))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-22981))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-14530))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5171))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(10840))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(23857))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6999))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-10950))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(4737))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-281))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(4086))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-53714))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(5377))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(9962))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(16797))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7530))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-7100))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-20125))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(308))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-1930))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-194))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(4464))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-4045))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-2525))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1101))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(4349))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-1758))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(14032))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-12338))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(15915))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-4386))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-1503))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6871))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(8534))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(1262))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(5047))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(12018))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-4844))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(579))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(9448))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(2402))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-7285))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4801))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(2953))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-9905))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-1972))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(5842))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-10821))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(3906))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-3687))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(2370))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-3793))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(2741))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-968))).
playerSensor(player,objectIndex(1),player(velocityY(1073))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2526))).
playerSensor(player,objectIndex(1),intPair(x(0))).
