asteroidSensor(asteroidClone,objectIndex(2),intPair(y(1384))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(2649))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(4394))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-6705))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(6533))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-7556))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(2344))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(684))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(5216))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(300))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-10001))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-8543))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(7203))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-9152))).
playerSensor(player,objectIndex(1),intPair(rotationZ(490))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
