asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-21795))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(2756))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-605))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-11840))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(14233))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-13299))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-7295))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3308))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-6920))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(4064))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6110))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-1732))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(2423))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-2138))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3391))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-46))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(6471))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-6829))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(1391))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-8520))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-33126))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-7416))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-1621))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(5871))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7281))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-1951))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-3595))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(8373))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-7386))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-2255))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(127))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-5091))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(2896))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(6426))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-10864))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-11108))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-5181))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(7832))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-3334))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(-712))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-4986))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(8060))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(4077))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(10430))).
playerSensor(player,objectIndex(1),intPair(rotationZ(850))).
playerSensor(player,objectIndex(1),player(velocityY(-222))).
playerSensor(player,objectIndex(1),player(velocityX(-158))).
playerSensor(player,objectIndex(1),intPair(y(-2458))).
playerSensor(player,objectIndex(1),intPair(x(-6252))).
