asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-15537))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-37047))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(16908))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(21855))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-23594))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-14987))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5288))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-55016))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(5564))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(10727))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(17602))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(24956))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7055))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(14424))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(11151))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(4618))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-2433))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-13592))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1227))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-26445))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-25308))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(11528))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7545))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-7425))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-20695))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-12891))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(16391))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-11432))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(6662))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(5503))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(16))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-2561))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-464))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(4086))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3900))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-4018))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-977))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-1980))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1301))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6926))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(9040))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(1854))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(3659))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(4705))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(13215))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5070))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(3471))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(985))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(9135))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(2233))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-6726))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4365))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(2777))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-9333))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-2401))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(6703))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-10342))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(3657))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-4817))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(1889))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-4907))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(3258))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(5633))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-10552))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-898))).
playerSensor(player,objectIndex(1),player(velocityY(628))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2971))).
playerSensor(player,objectIndex(1),intPair(x(0))).
