asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(22909))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(28606))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-18612))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3542))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-38316))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(19781))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-20446))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-8532))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-18014))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(12657))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(15980))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(4082))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(29568))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8163))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-20130))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-37047))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(20936))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(39981))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7823))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(25878))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(916))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-1587))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-8262))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(18470))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(815))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(3540))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(1483))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-21241))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-72807))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(8118))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-11195))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-4028))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7678))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(15948))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(9937))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-3798))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(253))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-20255))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-4690))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(10321))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(2997))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(165))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-2172))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-5710))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-2826))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(442))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-3716))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-5859))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(4213))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-9818))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-7491))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(6000))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-4495))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(21183))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7760))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11874))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-28488))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-2180))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(30))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(6528))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1360))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(6221))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2367))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-8806))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(1631))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-1746))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(3318))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-2595))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(5620))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(5299))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-6754))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(5778))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-6158))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(4138))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-546))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5120))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(1125))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(10753))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-298))).
playerSensor(player,objectIndex(1),player(velocityY(984))).
playerSensor(player,objectIndex(1),player(velocityX(-1352))).
playerSensor(player,objectIndex(1),intPair(y(3002))).
playerSensor(player,objectIndex(1),intPair(x(-1258))).
