asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7786))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-20499))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-70493))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11295))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-36772))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-35520))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(19712))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(38026))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-17157))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(11877))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(14617))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(3553))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(638))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(27441))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-7499))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(19823))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(27174))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-17959))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3241))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-27474))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(19084))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-19464))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(22061))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(8885))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-1420))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(215))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-77))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-813))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-3834))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-18150))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(9402))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3201))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(1812))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-1211))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(1926))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1104))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-1085))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-4756))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-1480))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(-644))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-1699))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7723))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(24711))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7732))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-10072))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3673))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7580))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(15050))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7761))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-6970))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(5807))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(5414))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(16939))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-4649))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(696))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-18247))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(7476))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2412))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-9627))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(390))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(586))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-2126))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(1961))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-4016))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(7472))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(3449))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-5701))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-5176))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(4631))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-10606))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(4338))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-4981))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(3628))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-5703))).
playerSensor(player,objectIndex(1),intPair(rotationZ(145))).
playerSensor(player,objectIndex(1),player(velocityY(-9))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2396))).
playerSensor(player,objectIndex(1),intPair(x(-1011))).
