asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-3966))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-18350))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(23029))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(6082))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-63791))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6824))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(15884))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(16168))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(32366))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7434))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(21332))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-14678))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(9619))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-2285))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(14517))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(6711))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7651))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9619))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-24539))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(17066))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1543))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-2918))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-1533))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2646))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(2399))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(21281))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6596))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2449))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-5476))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-5292))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-12432))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-16068))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2369))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-32300))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-31098))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-16617))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(19606))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(10671))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2021))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-6820))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7297))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(12447))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(5840))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(779))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(3719))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(7026))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1089))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-2956))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1429))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1590))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(12507))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-7114))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(1978))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-1356))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-12416))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(6741))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4584))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-7187))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3794))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(6580))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-7081))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-2745))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(360))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(11109))).
playerSensor(player,objectIndex(1),intPair(rotationZ(965))).
playerSensor(player,objectIndex(1),player(velocityY(-154))).
playerSensor(player,objectIndex(1),player(velocityX(1))).
playerSensor(player,objectIndex(1),intPair(y(2541))).
playerSensor(player,objectIndex(1),intPair(x(-1013))).
