asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-34788))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-20143))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7675))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(24152))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(3299))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-69384))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7627))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(19171))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(26488))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-18993))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(21655))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-16747))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(11503))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(13964))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-9534))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3503))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-5057))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-17646))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3097))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-36032))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7533))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(14619))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(8382))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-1056))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-7134))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(16206))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-2182))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(19126))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(37090))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(5461))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(5681))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(360))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-554))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-442))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(8962))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(3915))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-5042))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3300))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(2601))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(1153))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(981))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(-1165))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7719))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11018))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-26989))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(18750))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(930))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(26422))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7568))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-6222))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(908))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-17285))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-3424))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-17201))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(8077))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2433))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-10020))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(-203))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-564))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-4299))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-835))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(156))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-2308))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(1311))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-4696))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(8359))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(2562))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-5197))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-733))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-4848))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(4831))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-10984))).
playerSensor(player,objectIndex(1),intPair(rotationZ(552))).
playerSensor(player,objectIndex(1),player(velocityY(-15))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2402))).
playerSensor(player,objectIndex(1),intPair(x(-1011))).
