asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-37786))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-26008))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-56076))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(5717))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(11350))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(18258))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1365))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-27153))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(258))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(12089))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(25852))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7101))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(17443))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-3076))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-684))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(9452))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(22224))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-24092))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-15360))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5384))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-13891))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-13341))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(16780))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-11824))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(7020))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(6128))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-1535))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1464))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6971))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5254))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(2755))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(1315))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(8880))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4010))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(2634))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-5815))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(11558))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(4871))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-2618))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-15877))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7558))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-7690))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-21160))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(14743))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(3779))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3781))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-3717))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-549))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(2335))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(3311))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(4426))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(14190))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(2094))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-6270))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-8867))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-2750))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(7404))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-9952))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(3454))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-5737))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(1496))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(3679))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(5506))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-10145))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-618))).
playerSensor(player,objectIndex(1),player(velocityY(406))).
playerSensor(player,objectIndex(1),player(velocityX(-1027))).
playerSensor(player,objectIndex(1),intPair(y(3193))).
playerSensor(player,objectIndex(1),intPair(x(-172))).
