asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(23944))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-20217))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4283))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-42112))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-40801))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(24993))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-20118))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(12522))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-4047))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-1464))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(5799))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(44785))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-8069))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(28746))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7829))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13296))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9153))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-12370))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(8300))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-10136))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(7506))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1992))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(1069))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-30980))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(21494))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-22862))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(22233))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-1705))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(-834))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-25192))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-6794))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-24999))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(12579))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(9848))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-9343))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-8672))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-7538))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(3186))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(4227))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(8935))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(24527))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(32124))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(14574))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(19330))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(5382))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-13956))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-4900))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(3137))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2258))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-6788))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-8055))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-6135))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-7881))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(9318))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-9049))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(5391))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-2455))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5377))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(3769))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7918))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(18158))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(34798))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(3115))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(3687))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-812))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(6654))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(896))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-11887))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(8458))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(8827))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-4081))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-10770))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-1446))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(10893))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(3274))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-1261))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(4064))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-2282))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-989))).
playerSensor(player,objectIndex(1),player(velocityY(-1642))).
playerSensor(player,objectIndex(1),player(velocityX(1969))).
playerSensor(player,objectIndex(1),intPair(y(3614))).
playerSensor(player,objectIndex(1),intPair(x(-4558))).
