asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(33496))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-20843))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4571))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-43592))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-42265))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(25117))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-4775))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(46658))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-8165))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(29865))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7856))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(23700))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-890))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(-705))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(9253))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(25831))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-2046))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(36837))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9538))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-13866))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(8991))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-10867))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(-1258))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-27117))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-10605))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13851))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-31951))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(22162))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-23804))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(25805))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(4547))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-448))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(7955))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(2258))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-8193))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(2785))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5477))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-5240))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-8012))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(19019))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(13529))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-7614))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-26896))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(13460))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(7742))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(9052))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(10698))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-10176))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(5879))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-13601))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(5436))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(8076))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(10372))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-20939))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(15321))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(20636))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(5889))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-15033))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(2238))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(1935))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-8969))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-7425))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(4157))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(11621))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-10352))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-7126))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(9416))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-3199))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-3919))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-10175))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-1479))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(3568))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(3433))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(1148))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(6435))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-1821))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(9996))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-5372))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(2466))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(-6273))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(y(2233))).
asteroidSensor(asteroidCloneClone,objectIndex(81),intPair(x(-5646))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-775))).
playerSensor(player,objectIndex(1),player(velocityY(-774))).
playerSensor(player,objectIndex(1),player(velocityX(905))).
playerSensor(player,objectIndex(1),intPair(y(2463))).
playerSensor(player,objectIndex(1),intPair(x(-3212))).
