asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-20108))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4232))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-41854))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-19975))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-40547))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(23741))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-12110))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-22699))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(24852))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(21978))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(8180))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-10009))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-5910))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-1847))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(-760))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-24857))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-6651))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(7237))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1949))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-7896))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7902))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(18008))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(12347))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-3920))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-1362))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(3346))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2265))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-6924))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(6428))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(660))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-11589))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(44460))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-8052))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(28552))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7824))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13200))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(34444))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9086))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(2934))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(3538))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-875))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(3255))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(8291))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-2325))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-1440))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(14444))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(19103))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(5294))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-13769))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-4841))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-24669))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(12426))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(5461))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-8013))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(9078))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-8853))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(5306))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5359))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(4016))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(3803))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(8879))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(24300))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(31886))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-30811))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(21378))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(1377))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(9539))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-9167))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-8336))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-7424))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(8957))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-4109))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-10873))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(10983))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(3247))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-1681))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(3652))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-2362))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-957))).
playerSensor(player,objectIndex(1),player(velocityY(-1226))).
playerSensor(player,objectIndex(1),player(velocityX(1260))).
playerSensor(player,objectIndex(1),intPair(y(3864))).
playerSensor(player,objectIndex(1),intPair(x(-4848))).
