asteroidSensor(asteroidClone,objectIndex(2),intPair(x(4915))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(4402))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-716))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-7505))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6287))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(1067))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-3150))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(2918))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-6990))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-7340))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(595))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(354))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-6368))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(2107))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(888))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6066))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(10832))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-11428))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2126))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(57))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-418))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
