asteroidSensor(asteroidClone,objectIndex(19),intPair(y(8852))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(24187))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(31766))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(12259))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(21320))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-22617))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(24781))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-19904))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-3857))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-1312))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-6580))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-20054))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4207))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-41726))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-40420))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(23639))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7894))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(17933))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(12349))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(5292))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(7102))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1928))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-7816))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-5798))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(3290))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(14379))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(18990))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(5250))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-13676))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-4811))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(21851))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-1918))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(-724))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-24690))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-24504))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(2843))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(3463))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-907))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(6315))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(541))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-8078))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(8958))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-8755))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(5263))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5351))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(3911))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(3821))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(44297))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-8044))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(28455))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7822))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13152))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-30726))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(34266))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-9052))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-11980))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(8120))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-9946))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(3451))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2269))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-6993))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(1531))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(9385))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-9079))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-8168))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-7367))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-11440))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(8208))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-2261))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(9022))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-4123))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-10925))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-1438))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(11029))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(3233))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(-1890))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(3445))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-2402))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-938))).
playerSensor(player,objectIndex(1),player(velocityY(-1087))).
playerSensor(player,objectIndex(1),player(velocityX(1044))).
playerSensor(player,objectIndex(1),intPair(y(3965))).
playerSensor(player,objectIndex(1),intPair(x(-4952))).
