asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11343))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(38189))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(24808))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7735))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(15125))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(8973))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-1483))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(588))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(27618))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(190))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-7563))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(19937))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(27293))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-18013))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3266))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7732))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7795))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-7100))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(5867))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(5368))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(4))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-877))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2408))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-20561))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-70686))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7813))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-27559))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(19142))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-19545))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(22132))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-3905))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-18315))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(9478))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3184))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-9558))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(494))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(3603))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-17229))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(11942))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(14731))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(3597))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(1674))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-1042))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(2061))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1125))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(7372))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(661))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-2094))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(2074))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-3897))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-5789))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-1867))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(4458))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-36900))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-35647))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(19814))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-10166))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3703))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7588))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(17067))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-4578))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(659))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-18414))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-1175))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-4836))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-1592))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(-553))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(7318))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-5233))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(4596))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-10541))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-5079))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(3670))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-5852))).
playerSensor(player,objectIndex(1),intPair(rotationZ(42))).
playerSensor(player,objectIndex(1),player(velocityY(-9))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2395))).
playerSensor(player,objectIndex(1),intPair(x(-1011))).
