asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2538))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(6200))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(15016))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(7022))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(16649))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(23834))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-16435))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7490))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(21989))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7667))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9945))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-15160))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(10058))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(11437))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2319))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-1164))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2845))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7352))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(12953))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(22477))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4193))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-18768))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-65092))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7011))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-33169))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-31957))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(16857))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(33466))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-25109))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(17458))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-17170))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(20083))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-7452))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-2555))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1166))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-2772))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(6432))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(352))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(2057))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6822))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-3327))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(4124))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(6713))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(919))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-2397))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(993))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1414))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-4903))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-5720))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(13368))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-6635))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(1729))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-13561))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-1837))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-13529))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(7258))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4428))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-6687))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3679))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(5654))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-5941))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-1837))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(504))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(10404))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2515))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-11543))).
playerSensor(player,objectIndex(1),intPair(rotationZ(998))).
playerSensor(player,objectIndex(1),player(velocityY(-90))).
playerSensor(player,objectIndex(1),player(velocityX(1))).
playerSensor(player,objectIndex(1),intPair(y(2477))).
playerSensor(player,objectIndex(1),intPair(x(-1012))).
