asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-5636))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-1569))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(1835))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(690))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(8558))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-3493))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-4493))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-8816))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-1451))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-4011))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-10440))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-4427))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(8179))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(1316))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-3296))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-7804))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-8139))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(83))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(4238))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-4248))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-22))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-16830))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(2734))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3678))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(4972))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-8913))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-6384))).
asteroidSensor(asteroidCloneClone,objectIndex(18),intPair(y(-1013))).
asteroidSensor(asteroidCloneClone,objectIndex(18),intPair(x(2223))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-11716))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-865))).
playerSensor(player,objectIndex(1),player(velocityY(-231))).
playerSensor(player,objectIndex(1),player(velocityX(-395))).
playerSensor(player,objectIndex(1),intPair(y(-126))).
playerSensor(player,objectIndex(1),intPair(x(-488))).
