asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-563))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(1029))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(624))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(4229))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(552))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-7875))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6714))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-8374))).
playerSensor(player,objectIndex(1),intPair(rotationZ(971))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(3622))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(3412))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-5237))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(5618))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-8929))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-7011))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(11773))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(814))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
