asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(23149))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-63983))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6852))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(15998))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-32429))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-31225))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-2325))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(14590))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(6757))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4000))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-18412))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7442))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(21429))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2676))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-16699))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(19677))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-14750))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(9684))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-2896))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-1478))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-2874))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-16122))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2394))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(10784))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2065))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-6913))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(2349))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(21458))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6629))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2579))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(6979))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1064))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-12581))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(6099))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(16270))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(32529))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1487))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(1364))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1564))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-5391))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-5355))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(6818))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4561))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-6913))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7654))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9668))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-24623))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(17124))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7305))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(12522))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(5928))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(716))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(3779))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(12634))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-7043))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(1941))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-12599))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-1427))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-7113))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3777))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(6443))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-2610))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(381))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(11005))).
playerSensor(player,objectIndex(1),intPair(rotationZ(972))).
playerSensor(player,objectIndex(1),player(velocityY(-143))).
playerSensor(player,objectIndex(1),player(velocityX(1))).
playerSensor(player,objectIndex(1),intPair(y(2529))).
playerSensor(player,objectIndex(1),intPair(x(-1013))).
