asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-1617))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-18839))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2925))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(1129))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-3048))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(-3005))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-3787))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(1814))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-4632))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3970))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-9010))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(3828))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-9250))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(12755))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-11304))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-5804))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2132))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-7160))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-28884))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(1389))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-6086))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-2943))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-8048))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(1440))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-6218))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-2173))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(7926))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-8064))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-2290))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(2888))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-5927))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(3732))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7230))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-890))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-6313))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-7874))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(6555))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-1793))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(6819))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-1765))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(-2142))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-9884))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-5955))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(10119))).
playerSensor(player,objectIndex(1),intPair(rotationZ(856))).
playerSensor(player,objectIndex(1),player(velocityY(-1272))).
playerSensor(player,objectIndex(1),player(velocityX(-904))).
playerSensor(player,objectIndex(1),intPair(y(-1409))).
playerSensor(player,objectIndex(1),intPair(x(-5506))).
