asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-22277))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-76038))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(8582))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(23082))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(30603))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(42709))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-21818))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7963))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(27507))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7799))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-12682))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(24092))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-19209))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(2711))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(32538))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-8725))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-10711))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(7534))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(2304))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-2668))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-22895))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(11603))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(4470))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-9326))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(20607))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-2610))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(-364))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(5792))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1719))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(3036))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-19523))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3963))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-40471))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-39179))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(22644))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(13745))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(17882))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(4820))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-12763))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-4523))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-23058))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-5885))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(3645))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-1216))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(5212))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-6530))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7814))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(17203))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(11405))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-3240))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-817))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-4705))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(1960))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(2734))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(7882))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-8224))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-7799))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-29903))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(20754))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2305))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-7660))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(3362))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-3690))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-7041))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-612))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-6812))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(3630))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-8719))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(7788))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(4849))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-9987))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(7396))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-1630))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5266))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(2886))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(9659))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-4260))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-11429))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-1409))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-819))).
playerSensor(player,objectIndex(1),player(velocityY(349))).
playerSensor(player,objectIndex(1),player(velocityX(-1500))).
playerSensor(player,objectIndex(1),intPair(y(4157))).
playerSensor(player,objectIndex(1),intPair(x(-4681))).
