asteroidSensor(asteroidClone,objectIndex(19),intPair(y(5516))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-15429))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-54678))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(24671))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-14869))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5258))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(11022))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(4537))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-2374))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-13497))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1183))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-7341))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-36812))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(21737))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-23435))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(10528))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(17393))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(16738))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7541))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-60))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-26220))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-25085))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(11350))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7040))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-20548))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(14322))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-12748))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(16268))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-11307))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(6548))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(5305))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-2398))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-394))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(4184))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3937))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-4113))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(-1113))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(-2121))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-1249))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-6912))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(8909))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(1700))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(3770))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(4794))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(12904))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-5011))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(3699))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(880))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(9216))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(2277))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-6871))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(4478))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(2823))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-9481))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-2289))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(6480))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-10466))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(3721))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-4524))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(2014))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-4618))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(3124))).
asteroidSensor(asteroidCloneClone,objectIndex(53),intPair(y(522))).
asteroidSensor(asteroidCloneClone,objectIndex(53),intPair(x(-1864))).
asteroidSensor(asteroidCloneClone,objectIndex(54),intPair(y(472))).
asteroidSensor(asteroidCloneClone,objectIndex(54),intPair(x(-2020))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-931))).
playerSensor(player,objectIndex(1),player(velocityY(722))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2877))).
playerSensor(player,objectIndex(1),intPair(x(0))).
