asteroidSensor(asteroidClone,objectIndex(3),intPair(y(462))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-1403))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(2988))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-4605))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(5223))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-7588))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-6776))).
playerSensor(player,objectIndex(1),intPair(rotationZ(650))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(4042))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(599))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(3803))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(661))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-8467))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6504))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-8038))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(11467))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(743))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
