asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-4819))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-9231))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-4158))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-4907))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-4586))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(1545))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(1678))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(4541))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-1169))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-4910))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(8619))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-4227))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(7954))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(80))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(752))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-15094))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(3567))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-8766))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-959))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(-162))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-9250))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-8505))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-695))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(929))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-2740))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(4640))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(5488))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-9320))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-6880))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
