asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-6325))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2689))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-1799))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-4889))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(-1561))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-4727))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-169))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(11849))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-10080))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-3686))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(1440))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-8740))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(689))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(131))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-2238))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-6162))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4325))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(8846))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-6346))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-8515))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2587))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-26280))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-5484))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-2512))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-5814))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(2419))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(5771))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-17025))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(2163))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-6697))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7198))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-239))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-687))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(5865))).
playerSensor(player,objectIndex(1),intPair(rotationZ(374))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-7272))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(4400))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-3667))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-8109))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-7007))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-802))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(-3019))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-11417))).
playerSensor(player,objectIndex(1),player(velocityY(109))).
playerSensor(player,objectIndex(1),player(velocityX(-1416))).
playerSensor(player,objectIndex(1),intPair(y(-341))).
playerSensor(player,objectIndex(1),intPair(x(-3847))).
