asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5777))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(20942))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-15116))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1930))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-30048))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-28871))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7288))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(19631))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1585))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(13222))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(5906))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-3376))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-17268))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7611))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-8775))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-23061))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(16050))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(8683))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1250))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-5182))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(x(283))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2129))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7154))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(11137))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6009))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-171))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(2667))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(7837))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-6959))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-4180))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(10274))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-8356))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(4093))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-60416))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6339))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(13901))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(14384))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(29516))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-15184))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(18370))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-13430))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(8482))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2521))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3295))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-2489))).
asteroidSensor(asteroidClone,objectIndex(36),intPair(y(1202))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(4307))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(1887))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(3286))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(18178))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1529))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-4406))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2558))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(2046))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(2624))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-9503))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-107))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-9528))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(5402))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4987))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-8481))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(8981))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-10038))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-5098))).
playerSensor(player,objectIndex(1),intPair(rotationZ(734))).
playerSensor(player,objectIndex(1),player(velocityY(-619))).
playerSensor(player,objectIndex(1),player(velocityX(7))).
playerSensor(player,objectIndex(1),intPair(y(3006))).
playerSensor(player,objectIndex(1),intPair(x(-1018))).
