asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-6821))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-20854))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-5408))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3186))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(2239))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-927))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-2742))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(528))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-9973))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-2117))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(2229))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-2931))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(3192))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(6903))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-7161))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(13763))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-12665))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-7035))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-1796))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-10940))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(5191))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7265))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-1614))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-3022))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(7879))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(4357))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(1626))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-8087))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-31776))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3575))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-7279))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(3229))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-760))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(5331))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6052))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-10517))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-5541))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(7426))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-2835))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(-1167))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-8180))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-5294))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(8715))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(10821))).
playerSensor(player,objectIndex(1),intPair(rotationZ(996))).
playerSensor(player,objectIndex(1),player(velocityY(-387))).
playerSensor(player,objectIndex(1),player(velocityX(-275))).
playerSensor(player,objectIndex(1),intPair(y(-2293))).
playerSensor(player,objectIndex(1),intPair(x(-6135))).
