asteroidSensor(asteroidClone,objectIndex(2),intPair(y(1485))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(2412))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(687))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(5267))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(286))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-7584))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(2598))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(4445))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-6780))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(6581))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-10057))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-8577))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(7228))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-9193))).
playerSensor(player,objectIndex(1),intPair(rotationZ(480))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
