asteroidSensor(asteroidClone,objectIndex(2),intPair(y(5416))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(634))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(5065))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(6428))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(806))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-9740))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(7259))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(8427))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-190))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
