asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(38393))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-37061))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-35806))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(19942))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(14873))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(3652))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(15218))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-27664))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(19215))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-19648))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(22220))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3740))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7598))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-7642))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-20638))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-70927))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7848))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7742))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(24930))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7738))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11404))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7837))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-7263))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(5942))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(5310))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(108))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-958))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3163))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(9083))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-1562))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(524))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(27840))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(159))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-3995))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-18521))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(9574))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(7241))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2403))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-9473))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(623))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(2215))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-3749))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-2077))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(20078))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(27443))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-18081))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3297))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-17318))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(12023))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-10283))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(17226))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-4490))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(613))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-18623))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(1503))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-831))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(2229))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(1152))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-1289))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-4935))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-1732))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(-440))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(754))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-2054))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(7125))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(3796))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-5899))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-5304))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(4552))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-10459))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(4608))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-5202))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(3723))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-6038))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-43))).
playerSensor(player,objectIndex(1),player(velocityY(-8))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2395))).
playerSensor(player,objectIndex(1),intPair(x(-1011))).
