asteroidSensor(asteroidClone,objectIndex(2),intPair(x(1188))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(7906))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(4307))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(4317))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(5869))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(772))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-8905))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(6697))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(-79))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-11610))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-849))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
