asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7218))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(22718))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(15570))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(7367))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(20613))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(17499))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(24729))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-16843))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2727))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7685))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10306))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-122))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-34134))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-32911))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(17622))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(34687))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-15695))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(10545))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(12289))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2649))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(1677))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(23807))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-6103))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(6330))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-8154))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3067))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7413))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(13515))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(7089))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(731))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-1776))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(509))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1218))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-2372))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-14767))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(665))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4446))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-19232))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-66539))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7553))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-25743))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(17894))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-17785))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7074))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-4303))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(4575))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(6365))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-4268))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-6197))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(14324))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(1452))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-14816))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(7832))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4255))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-6133))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3551))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(4625))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-4674))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-829))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(9619))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2487))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-11029))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(-1728))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(772))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-3127))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(819))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(-2501))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(-945))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-2775))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(-356))).
playerSensor(player,objectIndex(1),intPair(rotationZ(915))).
playerSensor(player,objectIndex(1),player(velocityY(-50))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2436))).
playerSensor(player,objectIndex(1),intPair(x(-1011))).
