asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-345))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(3367))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(1113))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-9030))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-12902))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-7854))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3452))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-4718))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-1278))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(2651))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(2546))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(5864))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-4757))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-22904))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(14787))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-14048))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-225))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(5048))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-7864))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-1414))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-11914))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(794))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(7814))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-2349))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-11805))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(-176))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-34718))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-1680))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-1203))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3173))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-6497))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6179))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(6673))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7300))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-6437))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(8311))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-4271))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(8956))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-3923))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-6449))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-4622))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(7288))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(3747))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(9969))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-6171))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-9765))).
playerSensor(player,objectIndex(1),intPair(rotationZ(596))).
playerSensor(player,objectIndex(1),player(velocityY(-115))).
playerSensor(player,objectIndex(1),player(velocityX(-82))).
playerSensor(player,objectIndex(1),intPair(y(-2565))).
playerSensor(player,objectIndex(1),intPair(x(-6328))).
