asteroidSensor(asteroidClone,objectIndex(3),intPair(y(2979))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(2179))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(712))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(5693))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-8865))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(2325))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(4869))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-7413))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(6975))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(177))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-10519))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(7439))).
playerSensor(player,objectIndex(1),intPair(rotationZ(138))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
