asteroidSensor(asteroidClone,objectIndex(2),intPair(x(2397))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(1888))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(2684))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(4649))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(699))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-7084))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(5471))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(6770))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(234))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-10279))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-8715))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(7329))).
playerSensor(player,objectIndex(1),intPair(rotationZ(377))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
