asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-7194))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(14132))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-13163))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-32837))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-21594))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(1441))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-8427))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(3886))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-2359))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(213))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-5159))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-7334))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-1658))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-11647))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(6227))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6097))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-6900))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-1815))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(2381))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-2308))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3430))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-6997))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(2959))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(6528))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-10673))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-199))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(5725))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7277))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-1879))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-10981))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-5258))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-3472))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(8267))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(4137))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3282))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(2645))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-674))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(7745))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-3227))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(-810))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-7556))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-5052))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(8201))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(10514))).
playerSensor(player,objectIndex(1),intPair(rotationZ(915))).
playerSensor(player,objectIndex(1),player(velocityY(-250))).
playerSensor(player,objectIndex(1),player(velocityX(-178))).
playerSensor(player,objectIndex(1),intPair(y(-2430))).
playerSensor(player,objectIndex(1),intPair(x(-6232))).
