asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(24043))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(6252))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-25257))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(17560))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(10171))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(17035))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(33751))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7505))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(22159))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(20206))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-15285))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(22788))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-1069))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2897))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7366))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(13084))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(880))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1368))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-6511))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-16530))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2582))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-33394))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-32180))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6881))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-3555))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(4230))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(6632))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-5832))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(13591))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-5645))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(15238))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(7160))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-4294))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-18876))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(11636))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2396))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-7615))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-2734))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(1664))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-13854))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-1962))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-13818))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-1602))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(542))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(-2323))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-65430))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7059))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(16848))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7671))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10029))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-17314))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(6585))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(241))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(1969))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(875))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-2252))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-4755))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(7392))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4388))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-6558))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3649))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(5414))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(10221))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2509))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-11423))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(1293))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-2670))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(1464))).
playerSensor(player,objectIndex(1),intPair(rotationZ(997))).
playerSensor(player,objectIndex(1),player(velocityY(-71))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2458))).
playerSensor(player,objectIndex(1),intPair(x(-1012))).
