asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11054))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-27052))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(18794))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(21708))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-17687))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3116))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-36128))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-34884))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7721))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-19054))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-1103))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(19202))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(37212))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7682))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(24225))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-16801))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(11552))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-492))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-69528))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(7647))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(19256))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(26578))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(14049))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(3333))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-9604))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-3525))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(5646))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(341))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-17325))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-20190))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(892))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(26555))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-7593))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-6320))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(5506))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(880))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-17410))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-3477))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(2498))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-2056))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(1254))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(997))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(x(-9969))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(y(-126))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(-4608))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7539))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(14675))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(8447))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-490))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-7182))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(16302))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-5004))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(9019))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(3898))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-4986))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3287))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(7999))).
asteroidSensor(asteroidClone,objectIndex(61),intPair(y(2430))).
asteroidSensor(asteroidCloneClone,objectIndex(62),intPair(x(-632))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-4359))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-919))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(-1097))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(212))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(-2284))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(1395))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(8243))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(2678))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-5263))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-859))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-4891))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(y(4805))).
asteroidSensor(asteroidClone,objectIndex(69),intPair(x(-10935))).
playerSensor(player,objectIndex(1),intPair(rotationZ(519))).
playerSensor(player,objectIndex(1),player(velocityY(-14))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(2401))).
playerSensor(player,objectIndex(1),intPair(x(-1011))).
