asteroidSensor(asteroidClone,objectIndex(2),intPair(y(5819))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(433))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(5337))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(6631))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(818))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-10044))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(7463))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(8617))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-40))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
