asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-6482))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-3090))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(1869))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-1157))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(2633))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(13427))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-12211))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(815))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-5634))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6010))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-2393))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(2090))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-3498))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(7244))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-9337))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(7135))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(1795))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-7778))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-30812))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-6763))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-1922))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-10296))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(4704))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7253))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-1373))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-2612))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(7526))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(4557))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-20183))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3099))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3706))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-7535))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(3404))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-1270))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(4516))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-10094))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-5798))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-7399))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-2478))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(-1492))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-8748))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-5515))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(9183))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(11100))).
playerSensor(player,objectIndex(1),intPair(rotationZ(981))).
playerSensor(player,objectIndex(1),player(velocityY(-576))).
playerSensor(player,objectIndex(1),player(velocityX(-409))).
playerSensor(player,objectIndex(1),intPair(y(-2105))).
playerSensor(player,objectIndex(1),intPair(x(-6001))).
