asteroidSensor(asteroidClone,objectIndex(2),intPair(y(4710))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(987))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(4589))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(6072))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(785))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-9209))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(6901))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(8096))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(-131))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-11832))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-613))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
