asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-44301))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(23091))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(35404))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-21713))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4973))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-45650))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-14623))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-33303))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-25115))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(26936))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-29794))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(26749))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(49264))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-8298))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(31420))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7893))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-8142))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(20217))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(14931))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-5788))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(244))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(-1849))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(14685))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-2857))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(39673))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-10075))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-15948))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(9953))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-8755))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-29537))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(10445))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(11203))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(x(-3174))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(9696))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(27644))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-22080))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(16361))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(22454))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(6594))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-16530))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-5713))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-11883))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(25741))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(y(2580))).
asteroidSensor(asteroidClone,objectIndex(60),intPair(x(262))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(y(-10241))).
asteroidSensor(asteroidCloneClone,objectIndex(63),intPair(x(-9219))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(y(5606))).
asteroidSensor(asteroidCloneClone,objectIndex(64),intPair(x(5743))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(y(57))).
asteroidSensor(asteroidCloneClone,objectIndex(65),intPair(x(9764))).
asteroidSensor(asteroidClone,objectIndex(66),intPair(y(4152))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(y(14088))).
asteroidSensor(asteroidCloneClone,objectIndex(67),intPair(x(-11755))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(y(-13293))).
asteroidSensor(asteroidCloneClone,objectIndex(68),intPair(x(-9104))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(y(12619))).
asteroidSensor(asteroidCloneClone,objectIndex(70),intPair(x(-11745))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(y(6559))).
asteroidSensor(asteroidCloneClone,objectIndex(71),intPair(x(-15985))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(y(10749))).
asteroidSensor(asteroidCloneClone,objectIndex(72),intPair(x(-4234))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(y(5616))).
asteroidSensor(asteroidCloneClone,objectIndex(73),intPair(x(7118))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(y(7031))).
asteroidSensor(asteroidClone,objectIndex(74),intPair(x(-3694))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(y(-9348))).
asteroidSensor(asteroidClone,objectIndex(75),intPair(x(-1526))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(y(3289))).
asteroidSensor(asteroidClone,objectIndex(76),intPair(x(9647))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(y(3654))).
asteroidSensor(asteroidCloneClone,objectIndex(77),intPair(x(4501))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(y(9734))).
asteroidSensor(asteroidCloneClone,objectIndex(78),intPair(x(-1181))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(y(9057))).
asteroidSensor(asteroidClone,objectIndex(79),intPair(x(-4610))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(y(3420))).
asteroidSensor(asteroidCloneClone,objectIndex(80),intPair(x(-8247))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(y(9645))).
asteroidSensor(asteroidClone,objectIndex(82),intPair(x(-2618))).
asteroidSensor(asteroidCloneClone,objectIndex(83),intPair(y(1525))).
asteroidSensor(asteroidCloneClone,objectIndex(83),intPair(x(-8054))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-570))).
playerSensor(player,objectIndex(1),player(velocityY(-1257))).
playerSensor(player,objectIndex(1),player(velocityX(255))).
playerSensor(player,objectIndex(1),intPair(y(946))).
playerSensor(player,objectIndex(1),intPair(x(-2561))).
