asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-21459))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-2429))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3265))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(2571))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-720))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(270))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-5204))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-11519))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(14065))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-13073))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-7126))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-1870))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(2353))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-2421))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-7280))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-1683))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(3002))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(6597))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-10546))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-301))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(6064))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-6089))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-5310))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-6948))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-7669))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(1475))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-8366))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-32644))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(3456))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-7048))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(3766))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(5628))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7275))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-1831))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-10897))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(7687))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-3390))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(8197))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-3156))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(-875))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-5096))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(8294))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(4177))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(10569))).
playerSensor(player,objectIndex(1),intPair(rotationZ(945))).
playerSensor(player,objectIndex(1),player(velocityY(-271))).
playerSensor(player,objectIndex(1),player(velocityX(-193))).
playerSensor(player,objectIndex(1),intPair(y(-2409))).
playerSensor(player,objectIndex(1),intPair(x(-6217))).
