asteroidSensor(asteroidClone,objectIndex(3),intPair(y(3750))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(747))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(6271))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(3467))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(1608))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(5445))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(-8273))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(7512))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(29))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-11148))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-948))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
