asteroidSensor(asteroidClone,objectIndex(7),intPair(y(6286))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-62007))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(6568))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-9173))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(14836))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(21926))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-15564))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2137))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-14018))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(9018))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-3117))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-31110))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-29921))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(15225))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(30860))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(9620))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1614))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(y(19641))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5921))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(13832))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-23757))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(16529))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-15860))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(18952))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-5954))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1915))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2060))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(x(5030))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(1364))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(2868))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(1321))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-3723))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(2026))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(y(1831))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-10889))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(-3654))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-17779))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-7357))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(20433))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7630))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(-2038))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-2373))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(-7222))).
asteroidSensor(asteroidCloneClone,objectIndex(38),intPair(y(11755))).
asteroidSensor(asteroidCloneClone,objectIndex(40),intPair(x(-6286))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-1245))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(3163))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(7455))).
asteroidSensor(asteroidClone,objectIndex(47),intPair(x(-6260))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-4704))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(11327))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(-7770))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(2319))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(y(-10884))).
asteroidSensor(asteroidCloneClone,objectIndex(51),intPair(x(-696))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(6033))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(y(4797))).
asteroidSensor(asteroidClone,objectIndex(55),intPair(x(-7871))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(y(3952))).
asteroidSensor(asteroidClone,objectIndex(56),intPair(x(7849))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(y(-8644))).
asteroidSensor(asteroidClone,objectIndex(57),intPair(x(-3989))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(y(1718))).
asteroidSensor(asteroidCloneClone,objectIndex(58),intPair(x(681))).
asteroidSensor(asteroidCloneClone,objectIndex(59),intPair(y(1438))).
asteroidSensor(asteroidCloneClone,objectIndex(59),intPair(x(951))).
playerSensor(player,objectIndex(1),intPair(rotationZ(878))).
playerSensor(player,objectIndex(1),player(velocityY(-322))).
playerSensor(player,objectIndex(1),player(velocityX(3))).
playerSensor(player,objectIndex(1),intPair(y(2709))).
playerSensor(player,objectIndex(1),intPair(x(-1015))).
