asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-18100))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(722))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-1870))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(-2417))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-4170))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-5255))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4114))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-8302))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(4061))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-625))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(12386))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-10805))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2317))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-6820))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-3246))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(1661))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-5919))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-2311))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-2851))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(1992))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-8785))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(y(-6595))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(y(-2500))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-5432))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2829))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-27823))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(-2540))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(1704))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-6335))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-8330))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(784))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(8301))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-7364))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-5881))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(y(3197))).
asteroidSensor(asteroidCloneClone,objectIndex(26),intPair(x(-7217))).
asteroidSensor(asteroidClone,objectIndex(28),intPair(x(-8135))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(y(6235))).
asteroidSensor(asteroidCloneClone,objectIndex(29),intPair(x(-1343))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(6431))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-1372))).
asteroidSensor(asteroidClone,objectIndex(31),intPair(x(-10509))).
playerSensor(player,objectIndex(1),intPair(rotationZ(546))).
playerSensor(player,objectIndex(1),player(velocityY(-1966))).
playerSensor(player,objectIndex(1),player(velocityX(-1398))).
playerSensor(player,objectIndex(1),intPair(y(-714))).
playerSensor(player,objectIndex(1),intPair(x(-5012))).
