asteroidSensor(asteroidClone,objectIndex(2),intPair(x(10489))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-8243))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(490))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(3269))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(6774))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(879))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-3517))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2336))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-22375))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(74))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-4801))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-3020))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-1366))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-3170))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-349))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(603))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-6137))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-8457))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(4858))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(x(-4382))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(x(10227))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(y(-3770))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-641))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-14304))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-7432))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-5073))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(3324))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-7613))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-9779))).
asteroidSensor(asteroidCloneClone,objectIndex(21),intPair(y(-2584))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-4667))).
asteroidSensor(asteroidClone,objectIndex(23),intPair(y(5258))).
asteroidSensor(asteroidCloneClone,objectIndex(24),intPair(x(-5732))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(y(-2608))).
asteroidSensor(asteroidCloneClone,objectIndex(25),intPair(x(-5646))).
playerSensor(player,objectIndex(1),player(velocityY(-23))).
playerSensor(player,objectIndex(1),player(velocityX(-410))).
playerSensor(player,objectIndex(1),intPair(y(-334))).
playerSensor(player,objectIndex(1),intPair(x(-874))).
