asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-6679))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(9331))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(7617))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-2642))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(-3964))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(x(-8263))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(y(-4007))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(-7339))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(-11986))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(3850))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(-3815))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-3810))).
asteroidSensor(asteroidCloneClone,objectIndex(12),intPair(x(-19048))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(1670))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(4313))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(-8393))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(5312))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-2348))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(2035))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-153))).
asteroidSensor(asteroidClone,objectIndex(10),intPair(y(610))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(2448))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-3734))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(-6908))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-5751))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(y(402))).
asteroidSensor(asteroidClone,objectIndex(19),intPair(x(-10413))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-10663))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-993))).
playerSensor(player,objectIndex(1),player(velocityY(-93))).
playerSensor(player,objectIndex(1),player(velocityX(-159))).
playerSensor(player,objectIndex(1),intPair(y(-264))).
playerSensor(player,objectIndex(1),intPair(x(-725))).
