asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(19897))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(13345))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-7583))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-11566))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-4974))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(3870))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-1928))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(6196))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(2360))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(5666))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-8807))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-11229))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(4417))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(19233))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1347))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-7718))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(2648))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-3799))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1362))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-9089))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2071))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-970))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3260))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-9825))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(4732))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(-7136))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-11096))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-783))).
playerSensor(player,objectIndex(1),player(velocityY(85))).
playerSensor(player,objectIndex(1),player(velocityX(23))).
playerSensor(player,objectIndex(1),intPair(y(-2334))).
playerSensor(player,objectIndex(1),intPair(x(-966))).
