asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-3718))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(15955))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(5036))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(22331))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1068))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2658))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-11004))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(22994))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(2074))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-1980))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-854))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-7657))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-7431))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-10053))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(3980))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-8598))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-14824))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(1205))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(3614))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-1558))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-4203))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-930))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1771))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-12803))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(7067))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(-4763))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-9957))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(y(9487))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(x(-4252))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-700))).
playerSensor(player,objectIndex(1),player(velocityY(15))).
playerSensor(player,objectIndex(1),player(velocityX(4))).
playerSensor(player,objectIndex(1),intPair(y(-2264))).
playerSensor(player,objectIndex(1),intPair(x(-947))).
