asteroidSensor(asteroidClone,objectIndex(5),intPair(x(899))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(9078))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(2123))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(7167))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(5770))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(-554))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2548))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-4381))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-3221))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(5918))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(923))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(6556))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(6410))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(6585))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(2442))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2557))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-10600))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-927))).
playerSensor(player,objectIndex(1),player(velocityX(-1019))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(-180))).
