asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(16463))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(34791))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-10923))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-8056))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-27934))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-1101))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2423))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13091))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(5442))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(26457))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-4217))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-24782))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-9908))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-8431))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(5226))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-10181))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3204))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-24227))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(35452))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-12679))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-1068))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(2650))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-10361))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(2289))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-3609))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2931))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(4780))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(2220))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-5374))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-760))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-7026))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-6889))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-294))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(2493))).
playerSensor(player,objectIndex(1),player(velocityY(-167))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-1897))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-5325))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-769))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(5098))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(192))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-858))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(9471))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-2270))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-4339))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-9960))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-11039))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-719))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-4632))).
playerSensor(player,objectIndex(1),intPair(x(0))).
