asteroidSensor(asteroidClone,objectIndex(3),intPair(y(14635))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(3271))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-2813))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-2900))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(20764))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1209))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-8084))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-13176))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(2364))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-8381))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-9342))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(21428))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(5623))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(1789))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(4651))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1111))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-1817))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-4593))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-8127))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-10648))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-950))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2524))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-11297))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(5886))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(-5963))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(4201))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-10533))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-997))).
playerSensor(player,objectIndex(1),player(velocityY(36))).
playerSensor(player,objectIndex(1),player(velocityX(9))).
playerSensor(player,objectIndex(1),intPair(y(-2285))).
playerSensor(player,objectIndex(1),intPair(x(-953))).
