asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-363))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(11064))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(17192))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(3370))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1591))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-6697))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(7209))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(3956))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(16528))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-4847))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3149))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(7458))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-8762))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-10008))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(4928))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-8719))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-5387))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1807))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-10340))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2518))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5647))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-447))).
playerSensor(player,objectIndex(1),player(velocityY(385))).
playerSensor(player,objectIndex(1),player(velocityX(105))).
playerSensor(player,objectIndex(1),intPair(y(-2634))).
playerSensor(player,objectIndex(1),intPair(x(-1049))).
