asteroidSensor(asteroidClone,objectIndex(3),intPair(y(2633))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-4099))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(6840))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-3419))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(6524))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2493))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(6098))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(5768))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(1805))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(762))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(8842))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(5420))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(7190))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2472))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-9982))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-844))).
playerSensor(player,objectIndex(1),player(velocityX(-1328))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(-671))).
