asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2063))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(11960))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-505))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6975))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-3213))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(4118))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(11294))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(706))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-5112))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(10925))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(6654))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(4261))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(2662))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-4982))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1799))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(9169))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-8459))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(5322))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-2666))).
playerSensor(player,objectIndex(1),intPair(rotationZ(841))).
playerSensor(player,objectIndex(1),player(velocityY(1223))).
playerSensor(player,objectIndex(1),player(velocityX(74))).
playerSensor(player,objectIndex(1),intPair(y(-3853))).
playerSensor(player,objectIndex(1),intPair(x(-1027))).
