asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-38534))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2134))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(1405))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(797))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(34948))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1668))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(-536))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2960))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-23314))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-15484))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-9461))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-1685))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-15980))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-34468))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(24060))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(12497))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-19495))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-14535))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(11183))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1645))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-1578))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-6014))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-5852))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(8817))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-1996))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-6224))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-5650))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-3903))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(8445))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-9804))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(y(-6624))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-5692))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(44866))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-16749))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-34918))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(45525))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(2577))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-2503))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-1269))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-9060))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-3834))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-22873))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(10937))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-22680))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(4414))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(7071))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-10133))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(10375))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-7147))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2661))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-6987))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-575))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(4847))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3595))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(x(719))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-1885))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(6875))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(9467))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(8171))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(8017))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-801))).
playerSensor(player,objectIndex(1),player(velocityY(-1830))).
playerSensor(player,objectIndex(1),player(velocityX(-2371))).
playerSensor(player,objectIndex(1),intPair(y(-2561))).
playerSensor(player,objectIndex(1),intPair(x(-3333))).
