asteroidSensor(asteroidClone,objectIndex(3),intPair(x(9051))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(3086))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(4763))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(5474))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2265))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(3959))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(9718))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-853))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-7401))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(6159))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(90))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(7853))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-4247))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2115))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(10009))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(4534))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-9775))).
playerSensor(player,objectIndex(1),intPair(rotationZ(332))).
playerSensor(player,objectIndex(1),player(velocityY(-2999))).
playerSensor(player,objectIndex(1),player(velocityX(123))).
playerSensor(player,objectIndex(1),intPair(y(-2135))).
playerSensor(player,objectIndex(1),intPair(x(-1316))).
