asteroidSensor(asteroidClone,objectIndex(3),intPair(y(11484))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1546))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-651))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(17691))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-9243))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(7023))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-5094))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1725))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2436))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(17026))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(4733))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-5375))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-6860))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3057))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(3184))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(7128))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(3911))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-8498))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-10110))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5523))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-9787))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-508))).
playerSensor(player,objectIndex(1),player(velocityY(292))).
playerSensor(player,objectIndex(1),player(velocityX(79))).
playerSensor(player,objectIndex(1),intPair(y(-2541))).
playerSensor(player,objectIndex(1),intPair(x(-1023))).
