asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-2147))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(1724))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(3146))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(11664))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-36278))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(46807))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-16400))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-39883))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2134))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1196))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(-1253))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1951))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-17490))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-3028))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-24614))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-20715))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-15311))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-24270))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(11913))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-6560))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(13478))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(616))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-885))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-1790))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(3771))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(7679))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-6789))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-719))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(y(-8578))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-1339))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-9676))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-35700))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(25026))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-5467))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-4785))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-3771))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(8034))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3454))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-9374))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-2049))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-16429))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-10529))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-4659))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-24465))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-10963))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(11287))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-6490))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(9621))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-1698))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(4622))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(x(387))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-1821))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(8857))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-5483))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(9052))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(7447))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(7573))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(-6968))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(8625))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(7893))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-575))).
playerSensor(player,objectIndex(1),player(velocityY(-1679))).
playerSensor(player,objectIndex(1),player(velocityX(-2538))).
playerSensor(player,objectIndex(1),intPair(y(-3935))).
playerSensor(player,objectIndex(1),intPair(x(-5150))).
