asteroidSensor(asteroidClone,objectIndex(3),intPair(y(17035))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(23612))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(952))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2157))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-4459))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-12364))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(24275))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-9017))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-16173))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(4556))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(1836))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(2764))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-643))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-7064))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-1346))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-3884))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-6862))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-9567))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-914))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1155))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-14035))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(8034))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(-3782))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(3799))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-9486))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(y(8234))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(x(-3607))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(11349))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-1828))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-1750))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(728))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-1372))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(707))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-292))).
playerSensor(player,objectIndex(1),player(velocityY(7))).
playerSensor(player,objectIndex(1),player(velocityX(2))).
playerSensor(player,objectIndex(1),intPair(y(-2256))).
playerSensor(player,objectIndex(1),intPair(x(-945))).
