asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-16750))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-41006))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-25792))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(3621))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-1850))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2206))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2134))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(1990))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-17216))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-11419))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-5346))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-6887))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-7149))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(7691))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-18107))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(14296))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(465))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-803))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(-1850))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-308))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-1877))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(3234))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(8186))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-4835))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-4064))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-3661))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-5309))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-3085))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-25698))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-21731))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-15958))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(10291))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-1450))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-6491))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-840))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(x(110))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-1767))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(10509))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(7203))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-1192))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-212))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-37411))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(47874))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-1397))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-10190))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-36726))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(25831))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(12269))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-25595))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(12522))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-11655))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(12048))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(4436))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3337))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-9016))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(y(-10207))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8706))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(6845))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(-7049))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(8082))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(7117))).
playerSensor(player,objectIndex(1),player(velocityY(-5))).
playerSensor(player,objectIndex(1),player(velocityX(-621))).
playerSensor(player,objectIndex(1),intPair(y(-4343))).
playerSensor(player,objectIndex(1),intPair(x(-6228))).
