asteroidSensor(asteroidClone,objectIndex(3),intPair(x(1290))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(5254))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(-2835))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(3553))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(2153))).
playerSensor(player,objectIndex(1),intPair(rotationZ(671))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(5746))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-1777))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(2062))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(-3171))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(9668))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2965))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(10889))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(10058))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-6543))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
