asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-1022))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(17667))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-7070))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(6703))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(12024))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(4483))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-6055))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-9918))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(2938))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(2945))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-9813))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5364))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(3550))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1488))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(18331))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(6783))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-4718))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1620))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2330))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-9502))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-11823))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-991))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(4013))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-8319))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(-8335))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-575))).
playerSensor(player,objectIndex(1),player(velocityY(204))).
playerSensor(player,objectIndex(1),player(velocityX(55))).
playerSensor(player,objectIndex(1),intPair(y(-2453))).
playerSensor(player,objectIndex(1),intPair(x(-999))).
