asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-1097))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(21671))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(32278))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(41698))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-14917))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(1244))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2833))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(9141))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-31556))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(42357))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-14942))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-7537))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-31421))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(10070))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-18749))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(9377))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(6828))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-35201))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(617))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-16480))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-12615))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-13148))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(6004))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(5567))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-8081))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-2733))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-8032))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3943))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(1170))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-3385))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-6822))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-1794))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-18938))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(8120))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-4836))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-4104))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2746))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-8261))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-218))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(9461))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(5401))).
playerSensor(player,objectIndex(1),player(velocityY(-835))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(1235))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2791))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-20099))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(888))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-3291))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-1425))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-8096))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-7787))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-4230))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-10867))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-922))).
playerSensor(player,objectIndex(1),player(velocityX(-1094))).
playerSensor(player,objectIndex(1),intPair(y(-135))).
playerSensor(player,objectIndex(1),intPair(x(-177))).
