asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-798))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-2916))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(138))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-1651))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(4070))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-11956))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-25612))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(3089))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(2532))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-6186))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2306))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-10852))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-7808))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-7620))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(3975))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(1242))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-9647))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-21884))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(33245))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-3156))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-22660))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(14798))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-7094))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-6429))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(769))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-8220))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-8524))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-297))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(1633))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-1450))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-4853))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(24596))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(32584))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-2877))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-6162))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(y(-537))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(x(905))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(6332))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-7443))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(4184))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-1287))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-677))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(10579))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-2179))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(923))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(1108))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-10577))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-132))).
playerSensor(player,objectIndex(1),player(velocityY(-3322))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-2277))).
playerSensor(player,objectIndex(1),intPair(x(0))).
