asteroidSensor(asteroidClone,objectIndex(20),intPair(x(4538))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-1275))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-1510))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-11182))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-3195))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-27793))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-12992))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-17426))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-43179))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2134))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(2504))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(15878))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(173))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(13517))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-38711))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(27388))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(2198))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(9166))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-2671))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-23696))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-17209))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-18738))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-13139))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-1072))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-3615))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3110))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-19301))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-39602))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(49939))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-44))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(-3005))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-7654))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-8288))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(11587))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-969))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(7029))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(4074))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-1664))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-6675))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-28356))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(13440))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-28157))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-5915))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-3448))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-8324))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(y(-13356))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(x(-424))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(13701))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-4973))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8037))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(5680))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(7034))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(13698))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2699))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(808))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-2047))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(6487))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(464))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(-7207))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(5617))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(1449))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(11271))).
playerSensor(player,objectIndex(1),intPair(rotationZ(375))).
playerSensor(player,objectIndex(1),player(velocityY(1214))).
playerSensor(player,objectIndex(1),player(velocityX(1841))).
playerSensor(player,objectIndex(1),intPair(y(-3305))).
playerSensor(player,objectIndex(1),intPair(x(-4923))).
