asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-14855))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-31443))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(42250))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-1091))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-7486))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-31319))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-6733))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-1726))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-8012))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(32188))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(41591))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-19991))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-16379))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-12550))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(9316))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(862))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-3349))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-4797))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-4045))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-8159))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-14907))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-35088))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(21590))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(9988))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(1260))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-18806))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(9081))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-18617))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(6058))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(5516))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(8044))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2749))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-8304))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-206))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-7859))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-4241))).
playerSensor(player,objectIndex(1),player(velocityY(-639))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(590))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(1122))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-3415))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2873))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(1295))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2786))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-13069))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-1850))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(1701))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-1416))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(6761))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-2758))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-8062))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(9495))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(5420))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3955))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-10902))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-913))).
playerSensor(player,objectIndex(1),player(velocityX(-836))).
playerSensor(player,objectIndex(1),intPair(y(-88))).
playerSensor(player,objectIndex(1),intPair(x(-116))).
