asteroidSensor(asteroidClone,objectIndex(2),intPair(x(-2524))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(3142))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(3512))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(8668))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2798))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(7376))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(4824))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-217))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(-2124))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(1661))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(10165))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(8657))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-5679))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(9357))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-200))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
