asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-1443))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-1477))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-10891))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-27179))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-18951))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-38960))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(49334))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-267))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(-2666))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-3163))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(13097))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-27406))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-1997))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-17228))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-42542))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2134))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(2354))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(4269))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-23120))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-16842))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-18292))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-12635))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(13353))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2554))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(481))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-7429))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-7954))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(11207))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-1110))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-3511))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(7223))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(4180))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3176))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(x(-267))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-1694))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(6021))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-38130))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(26932))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(15414))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(259))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-6285))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-27604))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(2502))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(8878))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-12600))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(13086))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-6084))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-1004))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-3973))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-3080))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-8526))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(y(-12433))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(12765))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-5072))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8233))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(6697))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-20))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(-7161))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(7341))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(6057))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(1431))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(11500))).
playerSensor(player,objectIndex(1),intPair(rotationZ(200))).
playerSensor(player,objectIndex(1),player(velocityY(1252))).
playerSensor(player,objectIndex(1),player(velocityX(1808))).
playerSensor(player,objectIndex(1),intPair(y(-3744))).
playerSensor(player,objectIndex(1),intPair(x(-5581))).
