asteroidSensor(asteroidClone,objectIndex(3),intPair(y(10854))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(16943))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(16278))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1613))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(5026))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-219))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-4582))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-6615))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-8457))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(7303))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3195))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-5533))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(3463))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(7623))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1848))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(3979))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-8894))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-10455))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2560))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5709))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-10119))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-410))).
playerSensor(player,objectIndex(1),player(velocityY(442))).
playerSensor(player,objectIndex(1),player(velocityX(121))).
playerSensor(player,objectIndex(1),intPair(y(-2691))).
playerSensor(player,objectIndex(1),intPair(x(-1064))).
