asteroidSensor(asteroidClone,objectIndex(3),intPair(x(30732))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-8576))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-19920))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(31394))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-11350))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-2266))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-20880))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-6046))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(517))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-3772))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-168))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(7367))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2207))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-8974))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-5973))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-5064))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(3129))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(23036))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-2112))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-3699))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-6865))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(13402))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(1671))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(2793))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(2312))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(5262))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-5321))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(2926))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-5147))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-525))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(11509))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(316))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-23664))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(1890))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-821))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-6867))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(y(1272))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(x(-26))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-1730))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-9221))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-9896))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-708))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(363))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-980))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-763))).
playerSensor(player,objectIndex(1),intPair(rotationZ(190))).
playerSensor(player,objectIndex(1),player(velocityY(-392))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-7))).
playerSensor(player,objectIndex(1),intPair(x(0))).
