asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(26449))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(3984))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-1622))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-1442))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-10583))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(14923))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(349))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-1945))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-18581))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-38280))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(48693))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-37514))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-3129))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-26529))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(134))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-22511))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-16454))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-17820))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-12101))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-12185))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(12630))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(y(-11456))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-17018))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-41868))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2134))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(2194))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-502))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(-2308))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(12988))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2401))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-6263))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-932))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-4352))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-3512))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(x(-101))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-1726))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(7666))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-5873))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-26808))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(12733))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-26611))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(2823))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(8574))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-3577))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(7428))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(4292))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3247))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(11775))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-5176))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8440))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(6383))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(1413))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(11742))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-63))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-7191))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-7601))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(10805))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-1259))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-8741))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(6919))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-535))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(-7112))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(6522))).
playerSensor(player,objectIndex(1),player(velocityY(589))).
playerSensor(player,objectIndex(1),player(velocityX(601))).
playerSensor(player,objectIndex(1),intPair(y(-4116))).
playerSensor(player,objectIndex(1),intPair(x(-6080))).
