asteroidSensor(asteroidClone,objectIndex(4),intPair(y(2692))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(6208))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(-2990))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-2557))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(365))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(4366))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(-3694))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(6125))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(10168))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(2399))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(3049))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(11251))).
playerSensor(player,objectIndex(1),intPair(rotationZ(986))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
