asteroidSensor(asteroidClone,objectIndex(2),intPair(y(5462))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-1297))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(1673))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(-2849))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(9360))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-6277))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(-2739))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(1860))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(3052))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(4718))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(2002))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2914))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(10666))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(9627))).
playerSensor(player,objectIndex(1),intPair(rotationZ(474))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
