asteroidSensor(asteroidClone,objectIndex(2),intPair(y(5214))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(2358))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2869))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(-2656))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-877))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(-2567))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(4249))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(9091))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(1869))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(10471))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(9250))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-6044))).
playerSensor(player,objectIndex(1),intPair(rotationZ(295))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
