asteroidSensor(asteroidClone,objectIndex(24),intPair(y(2134))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(26967))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(35396))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(16919))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(5243))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(2260))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(4759))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2456))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-616))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-951))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-1628))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-5095))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-5151))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-11113))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-908))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-12878))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-28571))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-13706))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-10484))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-8798))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(5569))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-10932))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-6699))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-761))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-4508))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-25364))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-6440))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(326))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-2495))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-628))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-9791))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-11273))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-24869))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(36057))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-8502))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-1573))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(5787))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(9168))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(2577))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-4001))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3635))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(2873))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-4199))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2915))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-10795))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(491))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-11820))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-823))).
playerSensor(player,objectIndex(1),player(velocityY(329))).
playerSensor(player,objectIndex(1),player(velocityX(-968))).
playerSensor(player,objectIndex(1),intPair(y(-4593))).
playerSensor(player,objectIndex(1),intPair(x(-225))).
