asteroidSensor(asteroidClone,objectIndex(9),intPair(y(686))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(14712))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(15377))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3485))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(9534))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(5639))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-6102))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-9723))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1755))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-6809))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(7889))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-6453))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(8661))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(4121))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2819))).
playerSensor(player,objectIndex(1),intPair(x(-1233))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-2920))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(4047))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-2105))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-11180))).
asteroidSensor(asteroidCloneClone,objectIndex(19),intPair(y(2928))).
asteroidSensor(asteroidCloneClone,objectIndex(19),intPair(x(-2261))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-149))).
playerSensor(player,objectIndex(1),player(velocityY(1058))).
playerSensor(player,objectIndex(1),player(velocityX(289))).
playerSensor(player,objectIndex(1),intPair(y(-3307))).
