asteroidSensor(asteroidClone,objectIndex(3),intPair(y(1823))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(7359))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(5562))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(6825))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(1017))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(6788))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(-755))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2580))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(9218))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-4548))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(5976))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-3104))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-988))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(1234))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(6229))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(2816))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2607))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-10963))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(-384))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(-15))).
