asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1607))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(16350))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-260))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(17014))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-5491))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(7576))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5692))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(10914))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(4998))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-4658))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-6638))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-8532))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(7276))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3182))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(3436))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1836))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(3972))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-8856))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-10422))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2548))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-10087))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-425))).
playerSensor(player,objectIndex(1),player(velocityY(425))).
playerSensor(player,objectIndex(1),player(velocityX(116))).
playerSensor(player,objectIndex(1),intPair(y(-2674))).
playerSensor(player,objectIndex(1),intPair(x(-1059))).
