asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3896))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6711))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-5204))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-4421))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-685))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-11))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(12636))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(8916))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(11971))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2002))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(2271))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-8062))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-11175))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(7224))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-3925))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1704))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3993))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(5070))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(10477))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-2555))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(4370))).
playerSensor(player,objectIndex(1),intPair(rotationZ(240))).
playerSensor(player,objectIndex(1),player(velocityY(1087))).
playerSensor(player,objectIndex(1),player(velocityX(-121))).
playerSensor(player,objectIndex(1),intPair(y(-3294))).
playerSensor(player,objectIndex(1),intPair(x(-1025))).
