asteroidSensor(asteroidClone,objectIndex(2),intPair(y(4433))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(1453))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(442))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(-1681))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(8244))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(9858))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-413))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(-2393))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(3925))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(2775))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2728))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(8065))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-5313))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(6923))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(8526))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
