asteroidSensor(asteroidClone,objectIndex(2),intPair(x(-2715))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(4584))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-1177))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(1576))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(-2768))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(1964))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(10610))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(5391))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(2002))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(2927))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(9283))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2901))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(9519))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-6211))).
playerSensor(player,objectIndex(1),intPair(rotationZ(437))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
