asteroidSensor(asteroidClone,objectIndex(3),intPair(y(14065))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-8624))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(20752))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(5099))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(3536))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-2422))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(5876))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1222))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-8694))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-8427))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-10904))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-10647))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(5376))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-995))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(20088))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1270))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-7863))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-12465))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(2489))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-3297))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(2042))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-1929))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-4761))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-959))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2850))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(-6481))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(4297))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-10782))).
playerSensor(player,objectIndex(1),player(velocityY(53))).
playerSensor(player,objectIndex(1),player(velocityX(14))).
playerSensor(player,objectIndex(1),intPair(y(-2302))).
playerSensor(player,objectIndex(1),intPair(x(-958))).
