asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(16836))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(16172))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(5068))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-4469))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-8344))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(7343))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-5596))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(7694))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(3989))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-10167))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(10764))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1623))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-157))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-6580))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3215))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(3503))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1865))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-8950))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-10505))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2577))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5736))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-393))).
playerSensor(player,objectIndex(1),player(velocityY(470))).
playerSensor(player,objectIndex(1),player(velocityX(128))).
playerSensor(player,objectIndex(1),intPair(y(-2718))).
playerSensor(player,objectIndex(1),intPair(x(-1072))).
