asteroidSensor(asteroidClone,objectIndex(3),intPair(y(9324))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(14463))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(830))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(15128))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-6547))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1352))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3531))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(4144))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1777))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(5736))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-2655))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-6020))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-1877))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(7983))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-6599))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(4140))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(8826))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-2146))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-9855))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-11295))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2860))).
asteroidSensor(asteroidCloneClone,objectIndex(19),intPair(y(3005))).
asteroidSensor(asteroidCloneClone,objectIndex(19),intPair(x(-1971))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-108))).
playerSensor(player,objectIndex(1),player(velocityY(1216))).
playerSensor(player,objectIndex(1),player(velocityX(332))).
playerSensor(player,objectIndex(1),intPair(y(-3465))).
playerSensor(player,objectIndex(1),intPair(x(-1276))).
