asteroidSensor(asteroidClone,objectIndex(3),intPair(y(2843))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(8744))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(6773))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(696))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(5909))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(5276))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(6705))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2471))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-3982))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(5504))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(7440))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-3501))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(1543))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(2437))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-9727))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(10863))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(4956))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-767))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(-1156))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(-843))).
