asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-15843))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-15467))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-33256))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(43959))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-1556))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-8307))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-32962))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(22879))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2877))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-21724))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-20928))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(33628))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(43300))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(1881))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-2939))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-1184))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(339))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1271))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-2425))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-7585))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(10049))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-20737))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(10290))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(7833))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-2360))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(8947))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-36886))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(1016))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(5200))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(6327))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-9119))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2703))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-7617))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-399))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(5121))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3767))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-5948))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(11297))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(1018))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2244))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-18005))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-13586))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-14329))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-8156))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-2825))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(9260))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-5432))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-4988))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-7150))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-6706))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-4065))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-10329))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(y(-4234))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(x(1125))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-1963))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(4453))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(9974))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-999))).
playerSensor(player,objectIndex(1),player(velocityY(-1232))).
playerSensor(player,objectIndex(1),player(velocityX(-1601))).
playerSensor(player,objectIndex(1),intPair(y(-1202))).
playerSensor(player,objectIndex(1),intPair(x(-1571))).
