asteroidSensor(asteroidClone,objectIndex(3),intPair(y(25737))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(33936))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(x(1585))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-12399))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-27035))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(4125))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(2341))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(4742))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-10429))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-23320))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(34597))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(15819))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-9095))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-7914))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-7426))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-9121))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(4955))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2596))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-780))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-3806))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-23960))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(5575))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2378))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-12225))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-964))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-7488))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-7522))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(1884))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-3055))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2954))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-1314))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-2276))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-5649))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-5688))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(y(-1860))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-357))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(3200))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-9300))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(2))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-788))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(9900))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-1953))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(176))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(1957))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-4538))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-10199))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-11383))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-371))).
playerSensor(player,objectIndex(1),player(velocityY(-1189))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-4410))).
playerSensor(player,objectIndex(1),intPair(x(0))).
