asteroidSensor(asteroidClone,objectIndex(3),intPair(y(12715))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-10779))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-1495))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-4237))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(4162))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-6924))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(2639))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-9139))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(18486))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-7338))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(2786))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1485))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2194))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-11512))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-9107))).
playerSensor(player,objectIndex(1),player(velocityY(129))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1414))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(19150))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(6476))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(6161))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-9435))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5160))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-980))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3620))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(4168))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(-7708))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-626))).
playerSensor(player,objectIndex(1),player(velocityX(35))).
playerSensor(player,objectIndex(1),intPair(y(-2378))).
playerSensor(player,objectIndex(1),intPair(x(-979))).
