asteroidSensor(asteroidClone,objectIndex(7),intPair(y(904))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(17485))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(4356))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-12931))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(24809))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-555))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-6818))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(3723))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(24146))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-9192))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-16734))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-1258))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-3751))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-907))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(899))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(-3373))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(x(-3339))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(11051))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-69))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(1948))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-4768))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(1738))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(2411))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-6625))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-9364))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-14548))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(8436))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-9289))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(y(7712))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-1856))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-2291))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(220))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-1809))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(106))).
playerSensor(player,objectIndex(1),player(velocityY(-559))).
playerSensor(player,objectIndex(1),player(velocityX(-458))).
playerSensor(player,objectIndex(1),intPair(y(-2305))).
playerSensor(player,objectIndex(1),intPair(x(-989))).
