asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(23457))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(22793))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1026))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-8749))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-15311))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(1988))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-1709))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-778))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-7443))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1549))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(16345))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2477))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-3986))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-11495))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(4863))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(1032))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(3307))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-1481))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-4088))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-7225))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-9878))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-924))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-13248))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(7416))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(-4409))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(3915))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-9787))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(y(9035))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(x(-4019))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(11807))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-1784))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-508))).
playerSensor(player,objectIndex(1),player(velocityY(11))).
playerSensor(player,objectIndex(1),player(velocityX(3))).
playerSensor(player,objectIndex(1),intPair(y(-2260))).
playerSensor(player,objectIndex(1),intPair(x(-946))).
