asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-174))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-4574))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(10048))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(3382))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(9636))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(4935))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(7463))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(2028))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1975))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-9190))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(5603))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2175))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(10714))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-1902))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-6384))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(4349))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(5787))).
playerSensor(player,objectIndex(1),intPair(rotationZ(815))).
playerSensor(player,objectIndex(1),player(velocityY(-2147))).
playerSensor(player,objectIndex(1),player(velocityX(264))).
playerSensor(player,objectIndex(1),intPair(y(-3688))).
playerSensor(player,objectIndex(1),intPair(x(-1152))).
