asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-12050))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-22187))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(33530))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-794))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-1580))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(6173))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-2751))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-6054))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(y(-815))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(x(1048))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-1219))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(3307))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(2491))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-6081))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-7267))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-6639))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(532))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-8313))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-234))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(1287))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(24837))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(32868))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-9812))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-25911))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2321))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11141))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-8079))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-7796))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(4346))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-8066))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-2364))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(1836))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-1556))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(766))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-4787))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-3293))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-22934))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(15013))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(3887))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-7973))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(4136))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-701))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(10436))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(1377))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-10497))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-147))).
playerSensor(player,objectIndex(1),player(velocityY(-3546))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-2853))).
playerSensor(player,objectIndex(1),intPair(x(0))).
