asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(16382))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-12644))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-1944))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-5365))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-770))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(5157))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2418))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-12983))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(2719))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-10228))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(168))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(26367))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(34684))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-10861))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-24113))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(35345))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-4166))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-24679))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-9806))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-8367))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-7977))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(5166))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-10049))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(5381))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-850))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(9525))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(2426))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-27822))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-1128))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(4698))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(2235))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-5413))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-979))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-786))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-7084))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-6968))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(2239))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-3539))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(3128))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-2231))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-235))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-4364))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-9990))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2934))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-11082))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-668))).
playerSensor(player,objectIndex(1),player(velocityY(-178))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-4621))).
playerSensor(player,objectIndex(1),intPair(x(0))).
