asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-1111))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(8574))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(13573))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1857))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(1344))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1478))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3030))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6084))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-1711))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(14238))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-5729))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-5610))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-2786))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(8316))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3696))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-7121))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(4472))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(9416))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-2292))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(4224))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-10327))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-2))).
playerSensor(player,objectIndex(1),player(velocityY(-546))).
playerSensor(player,objectIndex(1),player(velocityX(-222))).
playerSensor(player,objectIndex(1),intPair(y(-3616))).
playerSensor(player,objectIndex(1),intPair(x(-1294))).
