asteroidSensor(asteroidClone,objectIndex(2),intPair(y(6865))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-3667))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(10880))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(-3212))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(-952))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(3590))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(x(5523))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(-4439))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(7365))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(2749))).
playerSensor(player,objectIndex(1),intPair(rotationZ(881))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
