asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-38796))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(35158))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2134))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(1468))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-23567))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(45116))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-16893))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-35182))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(45774))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(2688))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-2434))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-1283))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-9180))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1576))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(-675))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2973))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-3994))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-23183))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(11079))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-22989))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(4289))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(7189))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-10295))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(10553))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(8973))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-1938))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(8365))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-16062))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-34707))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(24248))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(12687))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(762))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-19733))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-14686))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-15668))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-9669))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(11325))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1704))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-1443))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-1705))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-6106))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-5990))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-7078))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2654))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-6887))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-603))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-6077))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-5481))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-3878))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(4803))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3568))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-9720))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(y(-7004))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(x(655))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-1872))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(7261))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-5652))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(9386))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(8030))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(7931))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-778))).
playerSensor(player,objectIndex(1),player(velocityY(-2031))).
playerSensor(player,objectIndex(1),player(velocityX(-2633))).
playerSensor(player,objectIndex(1),intPair(y(-2848))).
playerSensor(player,objectIndex(1),intPair(x(-3705))).
