asteroidSensor(asteroidClone,objectIndex(3),intPair(x(19020))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1366))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-1804))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(2687))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(3953))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-7491))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-7513))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-3924))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(5807))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-9188))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-8902))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(-7299))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(13165))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(19684))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-11341))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(6276))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(2440))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1397))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2106))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5027))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-11310))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-973))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3363))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-9620))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(4570))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-720))).
playerSensor(player,objectIndex(1),player(velocityY(96))).
playerSensor(player,objectIndex(1),player(velocityX(26))).
playerSensor(player,objectIndex(1),intPair(y(-2345))).
playerSensor(player,objectIndex(1),intPair(x(-969))).
