asteroidSensor(asteroidClone,objectIndex(3),intPair(y(18025))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-13611))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(25450))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-3592))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(1697))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-5139))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(4116))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-1152))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-898))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(591))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(-2882))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(3633))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-2942))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(24787))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(846))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-9402))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-17409))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(1619))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-6521))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-6340))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-9121))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-15164))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(8919))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-9053))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(y(7085))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(x(-3016))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(10692))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-1890))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-389))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-2334))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-614))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(7264))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(9088))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(2062))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-444))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(2228))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-258))).
playerSensor(player,objectIndex(1),intPair(rotationZ(129))).
playerSensor(player,objectIndex(1),player(velocityY(259))).
playerSensor(player,objectIndex(1),player(velocityX(-737))).
playerSensor(player,objectIndex(1),intPair(y(-2489))).
playerSensor(player,objectIndex(1),intPair(x(-1276))).
