asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-36699))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(971))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-8008))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-13478))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-14198))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1228))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(33478))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(43122))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-15740))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-8222))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-32790))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(22744))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-2711))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-20707))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-4890))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(11160))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(1043))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2309))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-2521))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-1542))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-378))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-33067))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(43781))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-15408))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-17835))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(7722))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-2402))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-7634))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(9004))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-5977))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(439))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2867))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-21544))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(9134))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-5365))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(5152))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3787))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(x(1171))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(1802))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-2989))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-1174))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(5290))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(6243))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-9004))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-7255))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-6826))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-4083))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-10389))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(y(-3963))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(10032))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-998))).
playerSensor(player,objectIndex(1),player(velocityY(-1115))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(9949))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-20516))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(10189))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2708))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-7688))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-1972))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(4178))).
playerSensor(player,objectIndex(1),player(velocityX(-1452))).
playerSensor(player,objectIndex(1),intPair(y(-1074))).
playerSensor(player,objectIndex(1),intPair(x(-1404))).
