asteroidSensor(asteroidClone,objectIndex(3),intPair(y(5843))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(1726))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-250))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(10999))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(4296))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(10333))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2150))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(3218))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-2202))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(9529))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-9023))).
playerSensor(player,objectIndex(1),intPair(rotationZ(929))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(4781))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(7351))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-4667))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1935))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-6093))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(5681))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(11562))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-2824))).
playerSensor(player,objectIndex(1),player(velocityY(-1833))).
playerSensor(player,objectIndex(1),player(velocityX(226))).
playerSensor(player,objectIndex(1),intPair(y(-4003))).
playerSensor(player,objectIndex(1),intPair(x(-1113))).
