asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-9873))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(15094))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-22300))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(33636))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-12085))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(2476))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-6042))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(443))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(24927))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(32975))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-3344))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-23036))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(3389))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-7331))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-6718))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-8008))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-26024))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-1553))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(y(-920))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(x(1102))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(6113))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(3818))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-8106))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(4197))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-8234))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(-211))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-1596))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-2703))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-6014))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-792))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2327))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-11249))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-8180))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-7929))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(4407))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-1194))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-709))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(10383))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(1428))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-2433))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(1912))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(707))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(1354))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-4762))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-10467))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-155))).
playerSensor(player,objectIndex(1),player(velocityY(-3726))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-3073))).
playerSensor(player,objectIndex(1),intPair(x(0))).
