asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(25557))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(1656))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-5201))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-3565))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-9437))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-17521))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-6293))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-9081))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(y(6981))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(4076))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-897))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(539))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-9014))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-2421))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(18116))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-15267))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(9000))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(x(-2963))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(10633))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-490))).
playerSensor(player,objectIndex(1),intPair(rotationZ(182))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(24894))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(836))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-13724))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(1599))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-6472))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-1134))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(-2800))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(3618))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-1896))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-3050))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-734))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(7175))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(9020))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(1929))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(-383))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(2096))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(-197))).
playerSensor(player,objectIndex(1),player(velocityY(636))).
playerSensor(player,objectIndex(1),player(velocityX(-695))).
playerSensor(player,objectIndex(1),intPair(y(-2466))).
playerSensor(player,objectIndex(1),intPair(x(-1318))).
