asteroidSensor(asteroidClone,objectIndex(7),intPair(x(4761))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(16955))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3070))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(11424))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(17619))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-9168))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(7049))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(7175))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-610))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-6836))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-5136))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(3210))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1736))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5541))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1552))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-5300))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(3917))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-8535))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-10143))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2448))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-9819))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-498))).
playerSensor(player,objectIndex(1),player(velocityY(304))).
playerSensor(player,objectIndex(1),player(velocityX(83))).
playerSensor(player,objectIndex(1),intPair(y(-2552))).
playerSensor(player,objectIndex(1),intPair(x(-1026))).
