asteroidSensor(asteroidClone,objectIndex(3),intPair(x(15816))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(5207))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(48))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(16480))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-7970))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3281))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-9139))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(10464))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1655))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-4091))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-6463))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(7476))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-5805))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(3635))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(7930))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1924))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(4021))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-10669))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2636))).
asteroidSensor(asteroidCloneClone,objectIndex(19),intPair(y(2591))).
asteroidSensor(asteroidCloneClone,objectIndex(19),intPair(x(-3547))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5825))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-10325))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-336))).
playerSensor(player,objectIndex(1),player(velocityY(573))).
playerSensor(player,objectIndex(1),player(velocityX(156))).
playerSensor(player,objectIndex(1),intPair(y(-2821))).
playerSensor(player,objectIndex(1),intPair(x(-1100))).
