asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-32425))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(43176))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-15210))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(821))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-7931))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-32209))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(22288))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(777))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-19765))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(1534))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-3157))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-1142))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2835))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-20930))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(9844))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(32968))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(42517))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-15390))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(10697))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(1129))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-2532))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-7504))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-2321))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-19955))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(9605))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(5593))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(5956))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-8612))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(7342))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-2543))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-7803))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2724))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-7932))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-310))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(5258))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3853))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-6075))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-36062))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-17260))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-13111))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-13752))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1084))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-2849))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-1492))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(8703))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-5141))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-4556))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-7612))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-7235))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-4145))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(9198))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-10592))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(y(-3040))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(x(1328))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-2003))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(3242))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(10228))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-982))).
playerSensor(player,objectIndex(1),player(velocityY(-1237))).
playerSensor(player,objectIndex(1),player(velocityX(-1617))).
playerSensor(player,objectIndex(1),intPair(y(-706))).
playerSensor(player,objectIndex(1),intPair(x(-924))).
