asteroidSensor(asteroidClone,objectIndex(4),intPair(x(4053))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(y(6030))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(-2931))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-2257))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(721))).
asteroidSensor(asteroidClone,objectIndex(4),intPair(y(2450))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(-3493))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(5790))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(9976))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(2304))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(3017))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(11112))).
playerSensor(player,objectIndex(1),intPair(rotationZ(926))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
