asteroidSensor(asteroidClone,objectIndex(2),intPair(y(5001))).
asteroidSensor(asteroidClone,objectIndex(2),intPair(x(-2584))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(-517))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(2785))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(y(-2325))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(3847))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(8860))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(1755))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2830))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(10304))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(8927))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-5845))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-89))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
