asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-4521))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(23719))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(942))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(4516))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(1104))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-12478))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(24382))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(1817))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(2694))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-1328))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-3857))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(y(8130))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(17125))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2115))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-9052))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-16285))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-626))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-7015))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-6814))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-9526))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-912))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-14138))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(8114))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(-3700))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(3784))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-9446))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(x(-3554))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(11290))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-1833))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-1858))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(627))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-1460))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(587))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-241))).
playerSensor(player,objectIndex(1),player(velocityY(7))).
playerSensor(player,objectIndex(1),player(velocityX(1))).
playerSensor(player,objectIndex(1),intPair(y(-2255))).
playerSensor(player,objectIndex(1),intPair(x(-945))).
