asteroidSensor(asteroidClone,objectIndex(6),intPair(y(3395))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(12896))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-4898))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(8004))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1918))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(1735))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(13562))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3822))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(-931))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(6349))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-993))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-5507))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1573))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-3476))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(8569))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-7518))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(4725))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(9864))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-2403))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(4286))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-10685))).
playerSensor(player,objectIndex(1),intPair(rotationZ(61))).
playerSensor(player,objectIndex(1),player(velocityY(-796))).
playerSensor(player,objectIndex(1),player(velocityX(-324))).
playerSensor(player,objectIndex(1),intPair(y(-3367))).
playerSensor(player,objectIndex(1),intPair(x(-1192))).
