asteroidSensor(asteroidClone,objectIndex(3),intPair(x(16812))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(4817))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-5149))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-6790))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(7103))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-5220))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2471))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(11304))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1565))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-528))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(17477))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-9019))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3096))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(3264))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(7269))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1760))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(3930))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-8611))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-10208))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5577))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-9882))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-487))).
playerSensor(player,objectIndex(1),player(velocityY(329))).
playerSensor(player,objectIndex(1),player(velocityX(90))).
playerSensor(player,objectIndex(1),intPair(y(-2577))).
playerSensor(player,objectIndex(1),intPair(x(-1033))).
