asteroidSensor(asteroidClone,objectIndex(3),intPair(x(15638))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1671))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(150))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(16303))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-7783))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(7543))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-5909))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(8048))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-9233))).
asteroidSensor(asteroidCloneClone,objectIndex(19),intPair(x(-3339))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(10314))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(5276))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-3902))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-6405))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3314))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(3702))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1953))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(4037))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-10752))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2666))).
asteroidSensor(asteroidCloneClone,objectIndex(19),intPair(y(2645))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5869))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-10404))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-311))).
playerSensor(player,objectIndex(1),player(velocityY(632))).
playerSensor(player,objectIndex(1),player(velocityX(173))).
playerSensor(player,objectIndex(1),intPair(y(-2881))).
playerSensor(player,objectIndex(1),intPair(x(-1116))).
