asteroidSensor(asteroidClone,objectIndex(3),intPair(y(15235))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-13925))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(21476))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1145))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(5356))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-10377))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-10098))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(22140))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(2232))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-2482))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-994))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-8052))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-7811))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-11981))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(6423))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(y(10323))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(2992))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-3224))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-8318))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(1524))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(4180))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-1699))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-4416))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-941))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(2182))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(-5418))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(4101))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-10271))).
asteroidSensor(asteroidClone,objectIndex(25),intPair(x(-4682))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-884))).
playerSensor(player,objectIndex(1),player(velocityY(24))).
playerSensor(player,objectIndex(1),player(velocityX(6))).
playerSensor(player,objectIndex(1),intPair(y(-2273))).
playerSensor(player,objectIndex(1),intPair(x(-950))).
