asteroidSensor(asteroidClone,objectIndex(3),intPair(y(12565))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1430))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-6735))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(2706))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(18308))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(4232))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-1392))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(18972))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-7280))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-10592))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(6543))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(2819))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-4342))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(6279))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-1514))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-9517))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2224))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-5204))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-9218))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-11580))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-982))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(3705))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-8936))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(4034))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(-7845))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-617))).
playerSensor(player,objectIndex(1),player(velocityY(143))).
playerSensor(player,objectIndex(1),player(velocityX(39))).
playerSensor(player,objectIndex(1),intPair(y(-2392))).
playerSensor(player,objectIndex(1),intPair(x(-982))).
