asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-19157))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-27540))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-39338))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(49690))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-12831))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-38472))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(27200))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(15687))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(209))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(673))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-2026))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(13340))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-6515))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-28046))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(13299))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-27847))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-7561))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-8150))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3137))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(4427))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-1344))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-1496))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-11062))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(11431))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-1027))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-3474))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-136))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(-2865))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-3182))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(2323))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(9047))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(7109))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(4118))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(5820))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-17344))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-42917))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2134))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(2442))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(13556))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(2639))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-5984))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-1044))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-3763))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-2839))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-5014))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(8117))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(7160))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-23459))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-17058))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-18555))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-12931))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-8407))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(y(-12976))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(x(-359))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-1676))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(13316))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(6573))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(264))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(-7188))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(5798))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(y(1442))).
asteroidSensor(asteroidClone,objectIndex(54),intPair(x(11365))).
playerSensor(player,objectIndex(1),intPair(rotationZ(280))).
playerSensor(player,objectIndex(1),player(velocityY(1395))).
playerSensor(player,objectIndex(1),player(velocityX(2115))).
playerSensor(player,objectIndex(1),intPair(y(-3486))).
playerSensor(player,objectIndex(1),intPair(x(-5197))).
