asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-23773))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(35025))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-12539))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-24371))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(16141))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-12658))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(26097))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(34364))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-10676))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(4452))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(2280))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-5531))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-9502))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-8172))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-7741))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-7257))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(y(-7205))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-2112))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-27484))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(-1208))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-4012))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-712))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(2925))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-9830))).
asteroidSensor(asteroidClone,objectIndex(33),intPair(x(97))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-823))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(9686))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-58))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(2225))).
playerSensor(player,objectIndex(1),player(velocityY(-212))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(-2086))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-5487))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-775))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(5336))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-2401))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(4984))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-9651))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(5198))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(-862))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(2087))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-3332))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(2900))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-4439))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-10080))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(y(-2943))).
asteroidSensor(asteroidClone,objectIndex(42),intPair(x(-11211))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-521))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(-4587))).
playerSensor(player,objectIndex(1),intPair(x(0))).
