asteroidSensor(asteroidClone,objectIndex(3),intPair(x(14249))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(953))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-5950))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(y(-6724))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(1796))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(14914))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(x(-2095))).
asteroidSensor(asteroidCloneClone,objectIndex(19),intPair(y(3070))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(9144))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(5820))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-2429))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-6322))).
asteroidSensor(asteroidClone,objectIndex(12),intPair(y(1382))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(y(8063))).
asteroidSensor(asteroidClone,objectIndex(13),intPair(x(3571))).
asteroidSensor(asteroidClone,objectIndex(14),intPair(x(4220))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(y(8968))).
asteroidSensor(asteroidClone,objectIndex(15),intPair(x(-2181))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(y(4163))).
asteroidSensor(asteroidClone,objectIndex(16),intPair(x(-9968))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(y(-11394))).
asteroidSensor(asteroidClone,objectIndex(17),intPair(x(-2895))).
asteroidSensor(asteroidCloneClone,objectIndex(18),intPair(y(2999))).
asteroidSensor(asteroidCloneClone,objectIndex(18),intPair(x(-1280))).
asteroidSensor(asteroidCloneClone,objectIndex(19),intPair(x(-1722))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-63))).
playerSensor(player,objectIndex(1),player(velocityY(990))).
playerSensor(player,objectIndex(1),player(velocityX(248))).
playerSensor(player,objectIndex(1),intPair(y(-3618))).
playerSensor(player,objectIndex(1),intPair(x(-1318))).
