asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(y(-9728))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-16435))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(-39995))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(y(-15376))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(-36391))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(46913))).
asteroidSensor(asteroidCloneClone,objectIndex(22),intPair(x(-35802))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(y(25107))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(y(7730))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(x(-3034))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(y(-24722))).
asteroidSensor(asteroidCloneClone,objectIndex(27),intPair(x(-20817))).
asteroidSensor(asteroidCloneClone,objectIndex(35),intPair(x(-11033))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(y(11363))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(y(-5466))).
asteroidSensor(asteroidCloneClone,objectIndex(28),intPair(x(-16507))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(y(-10618))).
asteroidSensor(asteroidClone,objectIndex(29),intPair(x(-4727))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(y(-24598))).
asteroidSensor(asteroidCloneClone,objectIndex(36),intPair(x(-6529))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(y(-6618))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(y(7999))).
asteroidSensor(asteroidCloneClone,objectIndex(23),intPair(x(13560))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(y(601))).
asteroidSensor(asteroidClone,objectIndex(24),intPair(x(-1157))).
asteroidSensor(asteroidClone,objectIndex(26),intPair(y(-1312))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(x(-827))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(y(-1799))).
asteroidSensor(asteroidClone,objectIndex(34),intPair(x(3717))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(x(-5403))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(y(-4713))).
asteroidSensor(asteroidClone,objectIndex(44),intPair(x(-3760))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(y(-1815))).
asteroidSensor(asteroidCloneClone,objectIndex(48),intPair(x(9022))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(y(-1963))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(-17551))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(x(-1345))).
asteroidSensor(asteroidCloneClone,objectIndex(30),intPair(x(11724))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(y(-24403))).
asteroidSensor(asteroidCloneClone,objectIndex(31),intPair(x(11974))).
asteroidSensor(asteroidClone,objectIndex(32),intPair(y(1976))).
asteroidSensor(asteroidClone,objectIndex(45),intPair(x(4604))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(y(3442))).
asteroidSensor(asteroidClone,objectIndex(46),intPair(x(-9338))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(y(-8741))).
asteroidSensor(asteroidCloneClone,objectIndex(47),intPair(x(360))).
asteroidSensor(asteroidClone,objectIndex(49),intPair(x(9017))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(y(7387))).
asteroidSensor(asteroidClone,objectIndex(50),intPair(x(7536))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-532))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2134))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(y(1751))).
asteroidSensor(asteroidClone,objectIndex(20),intPair(x(3194))).
asteroidSensor(asteroidClone,objectIndex(21),intPair(y(-2117))).
asteroidSensor(asteroidCloneClone,objectIndex(37),intPair(x(9688))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(y(-1673))).
asteroidSensor(asteroidClone,objectIndex(39),intPair(x(-6760))).
asteroidSensor(asteroidClone,objectIndex(43),intPair(y(-731))).
asteroidSensor(asteroidCloneClone,objectIndex(52),intPair(x(-6976))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(y(8570))).
asteroidSensor(asteroidClone,objectIndex(53),intPair(x(7815))).
playerSensor(player,objectIndex(1),player(velocityY(-1582))).
playerSensor(player,objectIndex(1),player(velocityX(-2768))).
playerSensor(player,objectIndex(1),intPair(y(-4032))).
playerSensor(player,objectIndex(1),intPair(x(-5319))).
