asteroidSensor(asteroidClone,objectIndex(5),intPair(y(-1439))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(x(4352))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(y(7741))).
asteroidSensor(asteroidClone,objectIndex(5),intPair(x(2373))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(x(1339))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(x(9691))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(y(6676))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(x(-2133))).
asteroidSensor(asteroidClone,objectIndex(3),intPair(y(803))).
asteroidSensor(asteroidClone,objectIndex(6),intPair(y(8013))).
asteroidSensor(asteroidClone,objectIndex(7),intPair(y(2689))).
asteroidSensor(asteroidClone,objectIndex(8),intPair(x(-5113))).
asteroidSensor(asteroidClone,objectIndex(9),intPair(x(8073))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(y(5019))).
asteroidSensor(asteroidCloneClone,objectIndex(10),intPair(x(-2708))).
asteroidSensor(asteroidCloneClone,objectIndex(11),intPair(y(4090))).
playerSensor(player,objectIndex(1),intPair(rotationZ(-629))).
playerSensor(player,objectIndex(1),player(velocityY(0))).
playerSensor(player,objectIndex(1),player(velocityX(0))).
playerSensor(player,objectIndex(1),intPair(y(0))).
playerSensor(player,objectIndex(1),intPair(x(0))).
